### ISSUE TITLE
Interpolation markup

### ISSUE THREAD

**Issue by jeton** [json-schema-form/angular-schema-form#115]
Hey guys, 

Really nice job. Just a quick one, and probably edge-case. Have you guys thought about abstracting out the interpolation markup in the bootstrap decorator html files? I'm a python django user and can't use the default {{ }} syntax. 

I guess it's not a problem for me to change if I fork, edit the html files and re-gulp it.

**Comment by mayaboy** [comment]
Hi All
Sorry for reopening this.
Could you explain to me how and where replace the {{ }} ?
I downloaded  the schema-form.js but I couldn't find any trace of {{ }} , except in the var defaultMessages 
Is it something I have to change in the dependencies files?
In my app, I'm using a custom interpolation using this approach:
.config(function($interpolateProvider) {
    $interpolateProvider.startSymbol('{[{');
    $interpolateProvider.endSymbol('}]}');
  })

Thanks for your help.

**Comment by mayaboy** [comment]
I found it
I'm changing the bootstrap-decorator.js

**Comment by vishnucr** [comment]
Hey, i have the same problem, i need to change the default interpolation. because i'm using python django. what should i do, ?
