### ISSUE TITLE
Why are array fields allowed to contain undefined, but other fields aren't?

### ISSUE THREAD

**Issue by pikajude** [json-schema-form/angular-schema-form#120]
Probably the easiest way to see this is to check the "Kitchen Sink" example and see `"dislike": [null]` at the bottom. `null` is neither a valid string value nor undefined. This trips up the jsonschema library which I'm using in conjunction with this one, because it doesn't check for nulls.

I looked through the code but wasn't able to figure it out. I know that arrays get an empty item added to them if they don't have a default value, but I don't know why it ends up in the output rather than just getting filtered out, like other invalid/non-present attributes do.

**Comment by davidlgj** [comment]
It's undocumented... but you can use the form option `startEmpty`, if its set to `true` (in the array form definition it starts empty) the array start empty with just an add button. 

See https://github.com/Textalk/angular-schema-form/blob/master/src/directives/array.js#L136

**Comment by nekto0n** [comment]
Wow, thanks, @davidlgj. This option should be definitely documented.
