### ISSUE TITLE
Table view controll

### ISSUE THREAD

**Issue by zotona** [json-schema-form/angular-schema-form#150]
Could you provide a path to develop a custom control for a render collections?
And after click on some raw, opened a data form.
like a ngTable (http://bazalt-cms.com/ng-table/example/17)

**Comment by ham-360** [comment]
I think I understand what @zotona was asking for and I believe I too have a need for the same thing.

The aspect of json-schema-form which I find most compelling is the concept of using a JSON definition of a View (the Form document) which references a JSON definition of a Model (a JSON Schema), allowing the UI to present data (a JSON object) of said type (i.e. conforming to the JSON schema)

This fundamental concept gives a very powerful framework, and although json-schema-form is geared towards presentations which help _capture_ data the given format, the same concepts (e.g. using read only versions of the fields) could be used to _present_ already known data.

In this same vein, I believe @zotona and I would like a tool which:
 - takes a JSON schema, and
 - takes a JSON description of what a table should look like, giving for each column a reference to a property in the JSON schema, the combination of which:
 - allows the UI to render collections of JSON objects that conform to this schema.

In this way, you would be able to create multiple JSON views:
 - one for 'capture': as per json-schema-form today
 - one for 'edit'
 - one for 'view'
 - one for 'view many' (in table)

Meaning that with a single UI you could, with minimal effort work with constantly evolving data models by just updating JSON Schemas and JSON 'Views'...
