### ISSUE TITLE
Failed to execute 'createElement' on 'Document

### ISSUE THREAD

**Issue by chachou29** [json-schema-form/angular-schema-form#17]
Hello,
First, thank you for this fantastic work ... looks great !
I tried the example "Basic Usage" but i got an error :
Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
I missed something ?
Philippe

**Comment by ravi-patwal** [comment]
I am trying not to include bootstrap-decorator file, which I fear can mess up my existing application. Can I do without the file. I am getting the error when I am trying to remove the file.
Plus, in docs it is mentioned that bootstrap is optional.

**Comment by davidlgj** [comment]
@ravi-patwal you need at least one decorator, otherwise there will be no form rendered, an currently the bootstrap decorator is the only one. So you can't do without it until some other decorator is implemented.
