### ISSUE TITLE
The use of Javascript Reserved Keywords as Property Names

### ISSUE THREAD

**Issue by jcw007** [json-schema-form/angular-schema-form#19]
First of all, great job on the module! I am one of those poor souls who has to make his single page app work in IE8. While doing that, I got the "Expected Identifier" errors in console. Results from google search suggested Javascript reserved keywords being used as property names as the possible cause. The first of these errors was pointing to "e.default", and sure enough, after changing it to "e['default']", the error was gone. There were a few more errors pointing to places where ".enum" was used. Thanks in advance for looking into this.

**Comment by davidlgj** [comment]
Heads up, it looks like we're dropping IE8 in the future.

**Comment by stramel** [comment]
:+1: for dropping IE8 support! Angular 1.3 drops support for IE8 as well.

**Comment by davidlgj** [comment]
Yes, and so have we for every place where we use schema form. Angular 1.3 dropping support tipped the balance for us (And there was much rejoicing). 

Anyway I would really like to upgrade to angular 1.3 as a requirement so we can use bind once expressions, which should speed up things, but I have no idea what version people are still using.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
