### ISSUE TITLE
Handle 'email' type on default template

### ISSUE THREAD

**Issue by stramel** [json-schema-form/angular-schema-form#221]
Error messages are not being handled correctly with a type of `email`. It is hitting the [else case](https://github.com/Textalk/angular-schema-form/blob/master/src/services/decorators.js#L147) and outputting `[object Object]`. I have a global default error message defined too. 

It would be nice to be able to catch the invalid email and display a message.
https://docs.angularjs.org/api/ng/input/input%5Bemail%5D

**Comment by trajano** [comment]
Perhaps change the resulting `input` tag to use `type='email'`

**Comment by Anthropic** [comment]
This appears to be fixed, not sure when but I can't reproduce in the current version, please re-open with demo if you think the issue still exists.
