### ISSUE TITLE
angular validation

### ISSUE THREAD

**Issue by stramel** [json-schema-form/angular-schema-form#226]
It would be nice to add some of the angular validators to the templates. For example:
- `ng-maxlength`
- `ng-minlength`

These would prevent the user from adding more or less characters respectively.

**Comment by davidlgj** [comment]
I opted to only validating via the schema to get a consistent validation, the first versions used ng-required which led to several problems. But It could be done, however the `default.html` template probably needs to be split up into the different HTML5 input types for it to work.

**Comment by stramel** [comment]
@davidlgj I figured that was why the `ng-*` attributes were not applied. I will see if I have time to create some PRs for this.

**Comment by davidlgj** [comment]
:+1:

**Comment by davidlgj** [comment]
This should be easier now, in 0.8.0 `ngModelController.$error` codes is used by the `sf-messages` directive to display validation messages configured in the form object.

**Comment by stramel** [comment]
@davidlgj I will take a look, thanks!

**Comment by MattiJarvinen-BA** [comment]
Came across this when looking why form.$invalid isn't properly set according to required field.

In my case I would like to keep save/create button disabled until the form is valid. Currently required fields set form as invalid only after triggering validation through broadcast or if required fields had some value and it was removed.

**Comment by Anthropic** [comment]
Closing old issues because it's fun.
