### ISSUE TITLE
Manipulate Array Data

### ISSUE THREAD

**Issue by stephenreid** [json-schema-form/angular-schema-form#235]
I've been digging into ways to build a csv helper on top of the standard array class and its decorators. I'm trying to find where I can access the values already entered. I'm not seeing the values in Item or Model array and the internals make it look as though 'list' is the storage mechanism here.

Is there a way to access these items without overriding the standard array.js?

**Comment by nicklasb** [comment]
They should be in the model, actually. Is this still a problem? 
Can you perhaps provide an example of what you are trying to do?

**Comment by Anthropic** [comment]
Please re-open if you can provide information to help is assist you.
