### ISSUE TITLE
Updating from 0.7.7 to 0.7.8(and later) causes this error to appear.

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#236]
Hi,
I have started to get this error when clicking anywhere in a form. It doesn't affect anything that I can see except that the error is raised and the debugger stop(which is annoying as I always use the debugger..).

    jquery.js:1626 Uncaught TypeError: undefined is not a function
    jquery.js:1626 Sizzle.selectors.filter.TAG
    jquery.js:2143 i
    jquery.js:2361 superMatcher
    jquery.js:2531 Sizzle.select
    jquery.js:850 Sizzle
    jquery.js:4475 jQuery.event.handlers
    jquery.js:4412 jQuery.event.dispatch
    jquery.js:4116 jQuery.event.add.elemData.handle

I could not reliably discern what specific change is behind the error being raised. Any ideas?

**Comment by nicklasb** [comment]
Just a note for those that gets e-mail updates or similar, I had the wrong versions in the first post, the change is between 0.7.7 and 0.7.8, nothing else. Got confused by bower here for a second. :-) 
Sorry about that.

**Comment by davidlgj** [comment]
Hi @nicklasb,

I'm having problems reproducing, do you get the same error on the demo page? 
What version of angular? What version of jQuery and what browser?

**Comment by nicklasb** [comment]
Hi @davidlgj,
Well, I suppose the relevant versions are: 
jquery#2.1.3
angular#1.3.11
angular-sanitize#1.3.11
objectpath#1.1.0
tv4#1.0.17

The Chrome version is Version 40.0.2214.93 (64-bit)

On Firefox 35.0.1 I am getting the same error:
Error: TypeError: elem.nodeName.toLowerCase is not a function
Source File: https://127.0.0.1:8080/admin/bower_components/jquery/dist/jquery.js
Line: 1626


Ok, I managed to debug a little bit better this time, and I am now quite confused, the offending element is a form element, or rather the main form element ("<form.ng-pristine.ng-valid ng-isolate-scope ng-valid-schema>"). 

What is strange is that the element according to the debugger *has* a nodeName value of "FORM". Why they cannot call .toLowerCase on it is because nodeName according to the debugger isn't actually a string at all, but rather "<input.form-control.ng-valid-schema>", which upon closer inspection is the object I clicked.

So, somewhere it seems that the nodeName of the main form holds the clicked control, not a string value. Or I am just not getting it, which seems about as likely. :-)

**Comment by nicklasb** [comment]
Again, forgot to preview, the mail might not contain the element representations.

**Comment by davidlgj** [comment]
Do you get the error on the demo page or just in your code? 

If not on the demo page could you give an example schema and form? Do you use sf-options? 

I'll try to match version and reproduce when I get the time, but it looks weird. :-) AFAIK there's very little event handlers in schema form, mostly ng-click directives. So the question is what kind of event it is?

**Comment by nicklasb** [comment]
No, I cannot reproduce on the example form. 
It is the same without or with `{ formDefaults: { ngModelOptions: { updateOn: 'blur' } }}`, which was what I had.
I don't know where to begin with a sample application, but will see if I can try and elliminate my way closer to that by removing parts of the form. I'll be back.

**Comment by nicklasb** [comment]
Wow. This is FUBAR. 
It took me a while, but the winning combination is:
1. Using bootstrap.js (the actual component: /bower_components/bootstrap/dist/js/bootstrap.js, haven't tried using angular-bootstrap.)
2. Having an JSON field/attribute named "nodeName".
3. Having a debugger on so it stops on errors.

See this plnkr example:
http://plnkr.co/edit/SdGYrALWvk9WHMPa0710

If you either change the field to be called something else than nodeName or stops using bootstrap.js, the error doesn't happen.

I have tried to find out which of the 0.7.7-0.7.8 commits it is that causes things to be stored in the property with the same name as the field, but I haven't. It must be some secondary consequence.

I would say that even though this bug isn't seen in production as there is no debugger, it is a little bit scary; it could be causing very hard to track down problems down the line. And other name conflicts might yield completely different results.

**Comment by nicklasb** [comment]
Oh, silly me, here is a *public* plnkr, is a bit new to that tool:
http://plnkr.co/edit/SUk7vY

**Comment by davidlgj** [comment]
Wow, that is weird indeed!

Ok, I haven't really confirmed this, but this is what I believe happens: The last property of a key gets used as the name attribute for the input, so we end up with something like this: `<input name="nodeName">`. The form html element has a nice feature of having all of its child accessible as attributes, and those attributes take their names from the input name attribute, hence the form elements `form.nodeName` is no longer a string but and DOM element!

See http://stackoverflow.com/questions/22942689/form-elements-with-a-name-attribute-that-is-the-same-as-a-form-property-shadow for a better explanation.

**Comment by nicklasb** [comment]
That is my theory as well. It feels somewhat shaky.

**Comment by nicklasb** [comment]
The problem is that bootstrap certainly isn't a very unusual thing for people to use. And in a tree structure, nodeName is what you call names of nodes. And of course since nodeName is just one of the names that can't be used. 

Anyway. this means that something, somewhere, isn't used the way it is supposed to, and except for that this may cause bugs and issues, it means that the angula-schema-form depends upon using something the wrong way and stop working completely if browsers, or some framework, tightens something up so.

**Comment by nicklasb** [comment]
@davidlgj :
I am not sure if you considered this a problem or not.. Did I make sense? 
Also, as this behaviour is clearly introduced in 0.7.8, it is likely that the bug is in schema strap select.

**Comment by nicklasb** [comment]
If form field names are to be used dynamically, they must be prefixed as to not conflict with all the other possible values.

**Comment by davidlgj** [comment]
We intentionally set name to the attribute and not full key so that the
browser could fill in the field automatically and this works best with
simple field names like "street", "email" etc

But this and other issues (the pr on names in radios for instance) has made
it clear that this is not enough, so think we need a form option to set
name to whatever you like + a global option to let it default to attribute
or full key (which would never clash).

Would that work for you?

sön 1 mar 2015 15:00 Nicklas Börjesson <notifications@github.com> skrev:

**Comment by nicklasb** [comment]
I am not sure I understand, what do you mean by setting the name to the attribute? Or 
full key?

Automatically, you are talking about browser MRU-values being dependent on form field names? 
If so, isn't that usually something one do not want in these circumstances? In any case, a prefix would only restrict MRU:s to those from schema form entries, for example schemaform_street or  schemaform_email. Which I would prefer, personally. Or perhaps follow some [convention](http://stackoverflow.com/questions/6365395/is-there-a-naming-convention-for-html-form-fields-for-good-auto-completion-acros). 

With having a form value I presume you mean keeping the current way and override the name with that value. Would that not effectively make the developer to always have this conflict in mind? I would try and stay away from such solutions as they cause unnecessary support issues. Not to mention annoyances as it may seem like a weak design choice for a really central part of the functionality.

**Comment by nicklasb** [comment]
I edited the last post (if you just look at e-mail)

**Comment by davidlgj** [comment]
Sorry, writing on my phone. Doesn't lend itself to long answers :)

I should have written "property" instead of attribute. I meant the last part of the form definition key. 

The full key would then be the entire key used in the form definition.

We do want the user to be able to fill in the form, in this case their adress, without having visited the site previously.

But you are right that the default should be safe and not end up in clashes nor the nodeName problem, i.e a prefix.

**Comment by nicklasb** [comment]
Still not sure about what you mean with "last part", or do you not mean the string value of the key property?

I agree about the conclusion though. With us both, that is. :-)

**Comment by nicklasb** [comment]
This is resolved. By myself, for myself. :-)
