### ISSUE TITLE
How to set form pristine after previous form data loaded?

### ISSUE THREAD

**Issue by ulion** [json-schema-form/angular-schema-form#243]
form.$setPristine() do not work, since it only setup $pristine on all inputs, but angular-schema-form use some decorator scope to check the ngModel's $pristine status.

I guess either because the scope, or the way form.$setPristine() does not set $pristine of the model caused the problem. But how to resolve it?

I do not want the green border when the form loaded with existed model data. how to do that?

**Comment by ulion** [comment]
found the reason is at the scope.hasSuccess function of src/directives/schema-validate.js, which currently is:
```
scope.hasSuccess = function() {
    return ngModel.$valid && (!ngModel.$pristine || !ngModel.$isEmpty(ngModel.$modelValue));
};
```

all non-empty value forced be has success marker, which maybe not what we want when load existed model data.

**Comment by rexebin** [comment]
one way to get ride of the green border would be go to bootstrap-decorator, and alter the default template: <div class="form-group" ng-class="{'has-error': hasError(),  'has-success': hasSuccess(), 'has-feedback': form.feedback !== false}">, get ride of the 'has-success': hasSuccess(),

It would be lovely if we could overwrite the template so we do not have to worry about updating and lose what we have changed in the code.

**Comment by ulion** [comment]
But I'd like to change the hasSuccess() behavior with some way, if you can
supply some way to adapt it to do not consider non-empty as same as dirty
with some model level or controller level setting or tag?

2015-02-10 2:43 GMT+08:00 rexebin <notifications@github.com>:

> one way to get ride of the green border would be go to
> bootstrap-decorator, and alter the default template:
> , get ride of the 'has-success': hasSuccess(),
>
> It would be lovely if we could overwrite the template so we do not have to
> worry about updating and lose what we have changed in the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/243#issuecomment-73564600>
> .
>



-- 
Ulion

**Comment by rexebin** [comment]
hasSuccess() open add and remove the bootstrap css class "has-success" to the element, that is all the behavior. 

If I was to change the look of the green box, I would just simply overwrite bootstrap css class "has-success".

**Comment by ulion** [comment]
No, I do want hasSuccess, but I want it only for dirty fields, what I want is:
```
scope.hasSuccess = function() {
    return ngModel.$valid && !ngModel.$pristine);
};
```

OR
```
scope.hasSuccess = function() {
    return ngModel.$valid && (!ngModel.$pristine || !ngModel.$isEmpty(ngModel.$modelValue) && !theForm.$pristine);
};
```

NOT
```
scope.hasSuccess = function() {
    return ngModel.$valid && (!ngModel.$pristine || !ngModel.$isEmpty(ngModel.$modelValue));
};
```

that means, I do want the success marker only when anything changed of the form, but I do not want it has success marker when we load an existed data there without user touch it.

**Comment by davidlgj** [comment]
@ulion I think we need some kind of option here, because we have the exact opposite requirement, pre-filled fields should *not* have a success marker.

**Comment by ulion** [comment]
David, it's not opposite requirement, it's exactly same requirement with
me, pre-filled fields should not have a success marker.

2015-02-20 23:25 GMT+08:00 David Jensen <notifications@github.com>:

> @ulion <https://github.com/ulion> I think we need some kind of option
> here, because we have the exact opposite requirement, pre-filled fields
> should *not* have a success marker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Textalk/angular-schema-form/issues/243#issuecomment-75255542>
> .
>



-- 
Ulion

**Comment by cjroth** [comment]
I agree with @ulion. I'm trying out angular schema form and this issue immediately stood out to me. IMO, it shouldn't show inputs as valid unless they are dirty out of the box. This feels like the expected/standard for form validation.

**Comment by mlegenhausen** [comment]
+1

**Comment by raoulus** [comment]
+1
having the same issue with a custom dropdown directive which has the success class although the user didn't touch/change it

**Comment by raoulus** [comment]
As @ulion I also wonder as well why this check `scope.ngModel.$isEmpty(scope.ngModel.$modelValue)` is there?

**Comment by Anthropic** [comment]
@ulion this function now looks like the below can you confirm if it works for you in the alphas or you still have an enhancement request here? I will close it until someone responds as I'm cleaning out old issues, but please let me know if it is still something do discuss here. A plunker of what people want to see would help if re-opening :)

```js
scope.hasSuccess = function() {
  if (!scope.ngModel) {
    return false;
  }
  if (scope.options && scope.options.pristine &&
      scope.options.pristine.success === false) {
    return scope.ngModel.$valid &&
        !scope.ngModel.$pristine && !scope.ngModel.$isEmpty(scope.ngModel.$modelValue);
  } else {
    return scope.ngModel.$valid &&
      (!scope.ngModel.$pristine || !scope.ngModel.$isEmpty(scope.ngModel.$modelValue));
  }
};
```
