### ISSUE TITLE
[Feature Request] - Intra Form Linking / Key Path on ID

### ISSUE THREAD

**Issue by quietlyconfident** [json-schema-form/angular-schema-form#252]
It would be nice to be able to link to a location / field / etc. within a form.

There is already a [Help](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#help) field that a link could be inserted into.  You could also link from a button. 

The only issue is that there is currently nothing unique to link to.  `<input>` divs  have an ID attribute which is the name of their key; however, these are non-unique.  E.g. in the Array example the 'name' field can be repeated so there are non-unique IDs.  This is not permitted in HTML5 standard, but doesn't seem to cause any other problems so far.

One way to partially solve this would be to cause the ID of the form elements to be the full key-path (e.g.
`fieldobj.subfield.name` rather than just name).  This would narrow it down considerably.  For arrays, the index could be used (e.g. `fieldobj.arrayobj[2].name`).  In the case of multiple forms being created on the page, the form name could be appended to the beginning of the field path.

If ASF created the IDs on the elements this way then intra form linking would be a snap.

**Comment by Anthropic** [comment]
Hi @quietlyconfident what are you trying to do exactly?

You can select elements using the document query selector which allows you to search by the ng-model value which ASF inserts the key into.

Alternatively you can add in a css value that you can then create a directive to match against and act upon.

Failing that you can also modify the decorator to manipulate the value put into id as well.

I guess I can help better if I know exactly what the desired end result is, perhaps with example code?

**Comment by quietlyconfident** [comment]
Sure, thanks for taking a look at this and sorry if the question was unclear.

What I would like is a way to be able to put a link (e.g. `<a href="#someplace_on_this_form">...</a>`) into a ["Help" field on a form](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#help), so that if the user clicks on the link the browser zooms down to that spot on the form.

I don't have an example form available publicly (though I'll create one if this still doesn't make sense), but imagine, for example, if the Title Map Example on the [Demo Page](http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html) was 30 or 40 questions long, so the form scrolls down below the bottom of the screen.

In question number 25, I might put some help text in to inform the user, "This answer should have something to do with your answer to question number 6."  It would be great to be able to make "number 6" a link that would scroll the browser up to question 6.  Similarly, in the description to question 6, I could say "remember this, because you'll need it in question 25."  And make 25 a link, and so on.

Regarding your options, I think you're saying that there are ways I could programmatically find the form element I'm looking for using selectors and so on, and I think you're right.  However, those methods are not of use at the time of form creation (other than possibly, creating a directive which returns a link, and using the directive in the form text?).  

In other words, when I'm creating the form and I write out the help text, I can't type out `<a href="#name"> Go to the Name entry </a>` because elements having that ID are non-unique (e.g. there could be several elements with the id="name" in an array situation).

To sum up, the desired end result is (one or more of) the following:

1. ASF changes the way it assigns ID attributes to form field elements, so that (in keeping with the HTML spec) it does not repeat IDs amongst elements.

2. ASF assigns the ID attribute of form field elements in a predictable way, so that an ordinary muggle writing a form / schema and corresponding help text can write an HREF attribute in that help text that will navigate the user to another place within the form, if the form is very long, preferably just having knowledge of the form and schema.

**Comment by Anthropic** [comment]
This can be done with the new builder functions, an add-on could provide a link to a field. The new alphas correctly provide a long variant of the field path via a function which could also be a way to look for an item by id. A builder could append such a tag to desired items. A little complex, but possible. If you still want help with this let me know and I can help you with it.
