### ISSUE TITLE
onChange doesn't fire when form type is array

### ISSUE THREAD

**Issue by whoadave** [json-schema-form/angular-schema-form#295]
As the title says, if I add an onChange handler to an array field, and then add or remove an item to that array, the handler doesn't fire.

**Comment by nicklasb** [comment]
Fixed, closing.

**Comment by nicklasb** [comment]
This is not fixed, the pull request in #295 has not been merged.

**Comment by Anthropic** [comment]
I believe this is fixed in the latest updates (alphas) for the eventual 1.0.0 release.

Please re-open if there are still issues in these versions.

**Comment by Anthropic** [comment]
Hmmm the test case in the originally proposed PR fails, re-opening just in case it isn't fixed.

**Comment by Anthropic** [comment]
Nope just fixed the test and it does pass. All good.

**Comment by santhoslokanath** [comment]
Hi Team,

In which version of release this patch is available. I am using bower to install and after running bower install. the patch code mentioned in this case(i.e onChange for array) is not available.

Please, let me know what I have do to get patch through bower.

Thanks,
Santhosh Lokanath

**Comment by Anthropic** [comment]
@santhoslokanath as mentioned above it is fixed in the alphas, it is not in a release yet, I suggest using npm and pulling the alpha version. Bower won't be supported much longer I expect as they recommend using yarn on their own homepage https://bower.io/
