### ISSUE TITLE
schema editor?

### ISSUE THREAD

**Issue by koo9** [json-schema-form/angular-schema-form#304]
is it in the road map in the near future?

**Comment by Dervisevic** [comment]
Not that I'm aware of, @davidlgj is the one with the grand plans but it's not something I've heard of. I'll let him answer.

**Comment by koo9** [comment]
dynamic form generation is higher level of page creation. programming language like js/c#/java is the best configuration tool and IDE UI designer is ultimate editor. with this framework, instead of write code at the primitive level, it's now *configuring* with JSON, let's call it JSON programming, the JSON schema become Domain Specific Language. I think an editor will be very beneficial in term of easy form creation.

**Comment by Knuckles9090** [comment]
I am planning on making this sometime later this year.

**Comment by mike-marcacci** [comment]
For what it's worth, I'm in the process of designing a schema/form builder right now (my main project that uses schema-form is in desperate need of one) and I'll probably really get into the code in a couple weeks. I initially thought this was going to be a huge undertaking, but as I'm laying it out, it looks surprisingly (deceptively?) straightforward. 

I loosely planned to get it working for my needs, then release it (as I tend to do), but if there's a lot of demand, I'd be more than happy to develop in the open.

**Comment by davidlgj** [comment]
@mike-marcacci I'd love to see it!  

We also are going to have to build something to generate form definitions and at least parts of schemas, but it's a bit down the line for us, but if you get something going we might be able to help!

**Comment by mike-marcacci** [comment]
Awesome – I'll post a link here when I get something alpha-quality up (will probably be in a couple weeks).

**Comment by davidlgj** [comment]
Cool :)


ons 18 mars 2015 kl 08:48 skrev Mike Marcacci <notifications@github.com>:

**Comment by nicklasb** [comment]
I have also considered this an is also very interested in something like this. That would make it possible not only for developers, but for users themselves to customize their interfaces.

**Comment by nicklasb** [comment]
(so I've edited my response, I realize that is not going to show in your emails)

**Comment by mike-marcacci** [comment]
Hey guys – I just started working on this, and [added a repo](https://github.com/mike-marcacci/angular-schema-form-builder) to start collecting thoughts. I think this project is made much easier by heavily relying on schema-form for the registry of possible form types, and also for the configuration of form items based on their type.

This would require a change to the form-type definition/mapping (what is the best word for these units, btw?) to allow each type to declare its configuration options. This would have the side-effect of fixing #113.

(from [here](https://github.com/mike-marcacci/angular-schema-form-builder#changes-to-schema-form))
```js
// old style (should maintain backwards-compatibility)
schemaFormDecoratorsProvider.addMapping(
    'bootstrapDecorator',
    'datepicker',
    'directives/decorators/bootstrap/datepicker/datepicker.html'
);

// new style defining title, description, schema, and form for configuration
schemaFormDecoratorsProvider.addMapping(
    'bootstrapDecorator',
    {
        type: 'datepicker',
        title: 'DatePicker',
        description: 'Datepicker add-on for Angular Schema Form using pickadate!',
        form: ['*'],
        schema: {
            type: 'object',
            properties: {
                minDate: {
                    type: ['string', 'null']
                },
                maxDate: {
                    type: ['string', 'null']
                }
            }
        }
    },
    'directives/decorators/bootstrap/datepicker/datepicker.html'
);
```

I'd love to hear your thoughts on these changes or the builder project in general.

**Comment by nicklasb** [comment]
I started an issue(and made a pull request) at that repo:
https://github.com/mike-marcacci/angular-schema-form-builder/issues/2

**Comment by rowino** [comment]
Hi all, built a simple builder for schema form using schema-form. Please have a look, I'd love to get your feedback. http://ralphowino.github.io/schema-form-builder

**Comment by nicklasb** [comment]
Cool stuff!

**Comment by nicklasb** [comment]
Well done indeed. I think this could be a great starting point, it is already quite usable.

@rowino, I added you to a planning gitter chat for Angular Schema Form, it would be great if you wanted to join and you and your project to be involved?

**Comment by rathahin** [comment]
This feature is cool!

**Comment by ThomasPe** [comment]
I'm in need of a form builder as well and would love to chip in! what is the current status? is there an official repo / branch already?

**Comment by nicklasb** [comment]
Hi @ThomasPe,
Good to hear!
With regards to status, I suppose you'd have to ask @rowino, as he is the main guy on that project. I don't know much more than that the demo looks good. :-)

Yes, there is, here is the repo: https://github.com/json-schema-form/json-schema-builder

**Comment by ThomasPe** [comment]
thanks! is there already a discussion going on about this? roadmap, how to help etc? @rowino @nicklasb

**Comment by nicklasb** [comment]
No roadmap yet. @rowino  has basically only created the repo and put the code there just a short while ago.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
