### ISSUE TITLE
events and dependencies

### ISSUE THREAD

**Issue by koo9** [json-schema-form/angular-schema-form#305]
i have evaluated other dynamic UI framework, alpaca support events and dependencies e.g. when select certain item in a select, other control will be visible or enabled. is this current supported with this  framework?

**Comment by Dervisevic** [comment]
What you're looking for sounds like conditions, check out the documentation and let us know if that's what you're looking for. https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#condition

**Comment by koo9** [comment]
condition is for show/hide, things like when select certain item in a select, then enable/disable other control. guess that would need to be done though onChange handler. is there  such example somewhere?

**Comment by koo9** [comment]
so in terms of control interaction, events like keypress. keydown, is it currently supported?

**Comment by Dervisevic** [comment]
It is not currently supported, and we haven't really seen a use case for those types of events. Of course you can write an addon where you have these types of events.

Regarding hide/show and enabled/disabled. As the documentation notes you can use angular expressions so you can set up the conditional to work when the select has a specific value. @davidlgj noted that this can be used (a bit hackingly) to support enabled/disabled by hiding the real field and showing a different field with readonly, by creating it in the form section but using the same schema key.

**Comment by martinsbreno** [comment]
Imagine I'm getting information about vehicles. I have a _select_ to pick the kind of vehicle (car, truck, bike). There's also a field for the vehicle licence plate however it doesn't make sense to ask for a bike's licence plate. Therefore, the license plate field should be hidden when _bike_ is selected.

**Comment by Anthropic** [comment]
@koo9 condition is not just for show/hide, you can add condition to any field definition and duplicate that condition with the reverse. That way you have two copies of the field and only one will show at a time, but the definitions can vary as little as readonly or as much as the entire type template used.

@martinsbreno that is exactly what conditions are for.

@koo9 please re-open if you do not feel the question has been answered sufficiently.
