### ISSUE TITLE
Properties of type 'integer' don't display a default validation message

### ISSUE THREAD

**Issue by peluja1012** [json-schema-form/angular-schema-form#321]
In previous versions, a default error message appeared for 'integer' properties like this:

![image](https://cloud.githubusercontent.com/assets/616158/6838665/8daa945a-d333-11e4-8f06-4160745ccebf.png)
In version 0.8.0, this default error message doesn't get displayed. I have put together a [plnkr](http://plnkr.co/edit/jw8mMB1pMuNZl0wduXFa?p=preview) that shows this.

**Comment by oatkiller** [comment]
:+1: I'm having the same problem

**Comment by davidlgj** [comment]
Yeah that is a regression, I overhauled the validation messages and that one isn't from tv4.

**Comment by Anthropic** [comment]
I tried this in a plunk of the latest code for the alpha https://embed.plnkr.co/WwBHmh/ and it seems to be ok. Please re-open if any further issues still exist in relation to this.
