### ISSUE TITLE
Checkbox inside an array for more than one level doesn't work

### ISSUE THREAD

**Issue by divyunsf** [json-schema-form/angular-schema-form#330]
This works 

<pre>
Schema = {
    "type": "object",
    "title": "Comment",
    "properties": {
        "Level1": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Level2": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "Text1": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</pre>

Form =  "*"

This doesn't

<pre>
Schema = {
    "type": "object",
    "title": "Comment",
    "properties": {
        "Level1": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Level2": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "Checkbox1": {
                                    "type": "boolean" //Doesn't work if its a boolean
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</pre>

Form =  "*"

Console

TypeError: undefined is not a function
    at Scope.link.i.$watch.i.appendToArray (schema-form.min.js:1)
    at $parseFunctionCall (angular.js:12404)
    at angular-touch.js:472
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$apply (angular.js:14565)
    at HTMLButtonElement.<anonymous> (angular-touch.js:471)
    at HTMLButtonElement.eventHandler (angular.js:3032)

**Comment by miqdadalik** [comment]
Same issue here also.. Getting same error for 2nd level of an array

**Comment by davidlgj** [comment]
Yep, that is definitely a bug.

**Comment by spallesen** [comment]
Im hitting the same bug in my project ... this bug got my up vote ... however thanks for a great framework in general :-)

**Comment by chiewmey** [comment]
Any fix update?

**Comment by Anthropic** [comment]
I believe this is fixed in the latest updates (alphas) for the eventual 1.0.0 release.

Please re-open if there are still issues in these versions.
