### ISSUE TITLE
Missing concept related to dynamic/conditional data?

### ISSUE THREAD

**Issue by a-laughlin** [json-schema-form/angular-schema-form#339]
If I understand schema-form correctly, there are three main structures:

* schema
* model
* form

Schema describes the model's structure.  To dynamically add model data, we add to model.

The part I'm unclear about is the difference between form and form-schema.

What makes sense to me is that there would be a form-schema that describes the form structure.  We should be able to prepopulate things like select options by adding to form.

Explicitly, something like:

* sf-model-schema
* sf-model-data
* sf-form-schema
* sf-form-data

Since that differs from the three main objects passed in, I'm curious.  Does it exist somewhere I'm missing, or perhaps I need to think about the form data differently?  Digging through the code now.

**Comment by davidlgj** [comment]
Hi @a-laughlin,

I'm not sure that I'm following you, with a 'form schema' do you mean a JSON Schema that describes the the possible form definitions? 

As I see it the schema describes and validates the model, the form definition describes the form and how it should look, i.e its the presentation, and it gets defaults from the schema as well as validation. 

It's all built as a pipeline, the schema is transformed into a "default form definition",  and then the user supplied form definition is extended with the defaults from the "default form definition", resulting in a final canonical form definition with links to the schema for validation purposes. 

So that is one reason just adding to the form definition doesn't update the form, it has been processed, also I've opted out of trying to watch for changes in the form definition since that would be very complicated to do and probably would end up having a lot of "watches" that cold be detriment to performance. Instead I opted for making it easy to extend with add-on:s of field types for those scenarios when you need to dynamically update the view.  This can of course be debated if that was the best decision :)

Hope that makes some kind of sense!

**Comment by a-laughlin** [comment]
Thanks for the explanation @davidlgj.  Understanding the pipeline aspect helps, as did stepping through the rendering this morning.  I'm putting together some pseudocode to explain it further, but have to head out for the day.

**Comment by a-laughlin** [comment]
Okay.  Hopefully this helps.

Starting HTML
```html
<div ng-controller="someController">
  <form
    sf-form-schema="formSchema"
    sf-form-model="formModel"
    sf-data-schema="dataSchema"
    sf-data-model="dataModel">
  </form>
</div>
```

Related controller
```js
function someController(){
  $scope.dataModel = {};
  
  // define our schema object
  $scope.dataSchema = {
    type:'object',
    properties:{
      foo:{type:'string'},
      bar:{
        type:'array',
        items:{type:'string'}
      }
    }
  };
  
  // define the form schema.  Responsibility is providing a form structure
  // and mapping the data schema to the form model
  $scope.formSchema = [
    {type:'template',template:'<h1>{{formModel.title}}</h1>'},
    {key:'foo',type:'text'},
    {
      key:'bar',
      type:'array',
      items:{type:'select'}
    }
  ];
  
  // Now let's prepopulate the form
  $scope.formModel = {
    title:'Hi!!',
    foo:'n/a',
    bar:[
      [{key:'a',val:'A'}, {key:'b',val:'B'}, {key:'c',val:'C'}]
    ]
  };
```


Then our dataSchema -> formSchema ... pipeline runs, generating an HTML template
```html
<h1>{{formModel.title}}</h1>
<input type="text" ng-model="dataModel.foo" value="{{formModel.foo}}"/>
<select ng-repeat="barOptions in formModel.bar" ng-model="dataModel.bar[$index]">
  <option ng-repeat="(key,val) in barOptions" value="{{key}}">{{val}}</option>
</select>
```

Then our sf directive links it, and the result is:

```html
<form
  sf-form-schema="formSchema"
  sf-form-model="formModel"
  sf-data-schema="dataSchema"
  sf-data-model="dataModel"
  pre-render="preRender">
  <!-- start generated html -->
  <h1>Hi!!</h1>
  <input type="text" ng-model="dataModel.foo" value="n/a" />
  <select ng-repeat="barItem in formModel.bar" ng-model="dataModel.bar[0]">
    <option value="a">A</option>
    <option value="b">B</option>
    <option value="c">C</option>
  </select>
  <!-- end generated html -->
</form>
```

Note the pre-render="preRender" attribute on the form.  That's where dynamic values and conditions get easy.  If this function were to run pre-link-phase...
```js
$scope.preRender = function (formModel) {
  // execute any arbitrary conditions
  if(formModel.bar[0].length === 3){
    formModel.bar[0].pop();
  }
  return $http.get(someUrl)
  .then(function(data){
    // data === [{key:'d',val:'D'}, {key:'e',val:'E'}, {key:'f',val:'F'}];
    formModel.bar.push(data);
  });
};
```

The directive can filter, make http requests, etc, and generate:
```html
<!-- start generated html -->
<h1>Hi!!</h1>
<input type="text" ng-model="dataModel.foo" value="n/a" />
<select ng-repeat="barItem in formModel.bar" ng-model="dataModel.bar[0]">
  <option value="a">A</option>
  <option value="b">B</option>
</select>
<select ng-repeat="barItem in formModel.bar" ng-model="dataModel.bar[1]">
  <option value="d">D</option>
  <option value="e">E</option>
  <option value="f">F</option>
</select>
<!-- end generated html -->
```

Even after the form renders, applying conditions and dynamic values is
as easy as adding or removing them from formModel. Angular handles the rest.

Does that make sense?

**Comment by a-laughlin** [comment]
What tripped me up was the identical `"foo.bar[]"` syntax for array and property references, yet they behave differently when you add `"foo.bar["+ i +"]"` in a loop.

**Comment by buzzvamsi** [comment]
I am trying to use the ng-repeat in the following scenario. Any advice how it can be done.

I have an employee multi-select. For each employee selected, email and join date needs to repeat.
Any ideas how this can be done? 

Snippet:
{

"form":[
  {
      "key": "EmployeeMultiGet",
      "type": "strapselect",
      "placeholder": "Select a Employee",
      "options": {
          "multiple": "true",
          "httpGet": {
              "url": "data/employees.json"
          }
      },
      "validationMessage": "Hey, you can only select three items or you'll see this!"
  },
  "email",
  {
    "key": "joindate",
    "dateOptions": {
      
    }
  }
],
"schema": {
  "type": "object",
  "title": "Employee",
  "properties": {
    "EmployeeMultiGet": {
        "title": "Employee Dynamic",
        "type": "array",
        "items": {"type": "string"},
        "maxItems": 2,
        "description": "This titleMap is asynchronously loaded using a HTTP get. "
    },
   "email": {
      "title": "email",
      "type": "string"
    },
    "joindate": {
      "title": "Join Date",
      "type": "string",
      "format": "datepicker"
    }
  }
}
}

**Comment by Anthropic** [comment]
@a-laughlin I think it is usually common for the sort of things you are suggesting to be done on the server side before it reaches the front end. Alternatively there are ways to use decorators/custom add-ons to achieve some elements, but I admit I don't fully follow what your goal is.

I have been throwing around the idea of passing in an additional scope which could then be accessed by conditions, would this cover some of your use case?

Feel free to re-open if you wish to discuss further or feel there's something specific we need to look at, but other than what I wrote above I don't have much more to add sorry.

@buzzvamsi create your own issue for discussion please, you wont get help in an unrelated thread like this.
