### ISSUE TITLE
enum  is reserved word. Closure compiler and so on have problems with it.

### ISSUE THREAD

**Issue by rusxakep** [json-schema-form/angular-schema-form#346]
WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
                            enum: ['dr','jr','sir','mrs','mr','NaN','dj']
                            ^

**Comment by rusxakep** [comment]
workaround: enum => 'enum'

**Comment by davidlgj** [comment]
Hi @rusxakep, do you get where and in what file? Because I cannot find any...

**Comment by Anthropic** [comment]
As this is old and JSON should ideally be quoted I'm closing this issue.

Please re-open if you do not feel the question has been answered sufficiently.
