### ISSUE TITLE
Feasibility to integrate Angular-UI's Datepicker & Timepicker

### ISSUE THREAD

**Issue by benoror** [json-schema-form/angular-schema-form#355]
Datepicker: http://angular-ui.github.io/bootstrap/#/datepicker
Timepicker: http://angular-ui.github.io/bootstrap/#/timepicker

* Is there a straightforward way to use them with **schema-form**?
* Or should I consider developing 3rd party extensions?
* **Would anyone be interested?**

**Comment by Dervisevic** [comment]
No straight forward way of using them except building an addon. As for interest, depends on if one doesn't find [this](https://github.com/Textalk/angular-schema-form-datepicker) meets their requirements. The timepicker part of pickadate.js hasn't been implemented in the addon, as we had no need for it.

So it's up to what you feel :)

**Comment by davidlgj** [comment]
@benoror you can always try out just using the `template` form field type, but anything that plays nice with `ng-model` should be easy to do a add-on off, basically you just need a template in that case. But we love to see new add-ons!

**Comment by brettahale** [comment]
This is quick and dirty for what I needed but can be build upon. Use how ever you would like. https://gist.github.com/brettahale/5fe67b3ea3de915537e0

**Comment by davidlgj** [comment]
Thanks for sharing @brettahale!

**Comment by benoror** [comment]
Thanks @brettahale !

**Comment by Anthropic** [comment]
@brettahale @benoror it would be great to see this as an add-on if it progressed that far, please consider it! Closing now as there is a fairly acceptable answer :)

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by milanpatel-parkstreet** [comment]
Hi @brettahale 
We have use uib-datepicker-popup but the issue is data not bind in a model.
It would be great to provide ready add-on.
