### ISSUE TITLE
Multiform support?

### ISSUE THREAD

**Issue by aczapszys** [json-schema-form/angular-schema-form#357]
This is a question.

I have a project where I want to provide some basic edit screens around some $resource modules.  Currently, I'm using ng-grid for list view and angular-schema-form for the detail view.  This means that I have duplicate logic for grabbing related data and doing validation.  I want to somehow combine these and use the schema-form validation in the ng-grid layout.

Do you have thoughts on where to start?

**Comment by davidlgj** [comment]
Hi @aczapszys, 

I'm not entirely sure on why you have duplicate logic for grabbing the data or why you need to do validation in the list view, presumably anything saved is also valid? 

One way would be to do an `ng-grid` add-on, but you're just displaying the data right? For validation you can use [tv4](https://github.com/geraintluff/tv4) with the same schema that you use for the details view, that way you have one validation logic.

**Comment by aczapszys** [comment]
@davidlgj 
Displaying data?  No, it's the same logical edit form definition in either list or detail view.

Thanks for the tip!

**Comment by davidlgj** [comment]
Is it one form and schema per item in the ng-grid? you can always just run
schema form inside each of them in that case.

fre 17 apr 2015 17:27 aczapszys <notifications@github.com> skrev:

**Comment by Anthropic** [comment]
@aczapszys it's been a while so I'm closing this, please re-open if you do not feel the question has been answered sufficiently.
