### ISSUE TITLE
How to sort tabarray like array elements (via drag-drop)?

### ISSUE THREAD

**Issue by minutephp** [json-schema-form/angular-schema-form#360]
Hi,

For simple arrays I see it's pretty simple to sort them via drag-drop. But last I checked, this doesn't seem to work for tabarrays.

Are there any plans to implement this? How difficult it is to do it. 

I'm going to dig in the ui-sortable code to see how the array sorting is implemented but if anyone can give me a few pointers how to go about it wrt tabarray, that would be really awesome!

thanks,
san

**Comment by davidlgj** [comment]
I think it can be as easy as slapping on the ui-sortable directive here https://github.com/Textalk/angular-schema-form/blob/development/src/directives/decorators/bootstrap/tabarray.html#L8

Try it out! :)

**Comment by nicklasb** [comment]
Closing
