### ISSUE TITLE
How to set form-wide configuration per type

### ISSUE THREAD

**Issue by dwikle** [json-schema-form/angular-schema-form#361]
I am working on a project where the schema is not known ahead of time and whose properties can vary.  So far I'm just using `"*"` as the form definition because I don't know the schema properties.  Is there a way to specify a configuration based on the property type that will apply to all properties from the schema?

For example, say I want to configure all booleans to use radio buttons instead of a checkbox, along with some custom labels.  I see how to do this if I know the property name but I'd like to apply that to all boolean fields.

The only thought I had was inspecting the schema and generating the form definition programatically.  Is that the recommended approach or is there a way to do configuration based on the property type?

**Comment by davidlgj** [comment]
Hi @dwikle, you can change the default rules for form definition if you like, or rather add new ones.

It is the `schemaFormProvider` (and its corresponding service `schemaForm`)  that decides what a schema should have as "default" form definition. 

It works like this:
1. First we match the type of the schema (i.e. object, string, number etc) against a map of types to arrays, you can see it defined here: https://github.com/Textalk/angular-schema-form/blob/development/src/services/schema-form.js#L232
2. Then we loop over the array and call each function in turn until one of them returns a form definition, then that's the one we use. 

So for you to change that you just need to prepend functions (so they get called first) onto the right arrays in `schemaFormProvider.defaults`. You can use the function `schemaFormProvider.stdFormObj` to take care of most of the common things a form object needs. Check the code for the other types for inspiration.

Ex: String with maxLength larger than 32 should be a textarea
```js
angular.module('myModule', ['sfSchema']).config(['schemaFormProvider','sfPathProvider', function(schemaFormProvider, sfPathProvider) {

  schemaFormProvider.prependRule('string', function(name, schema, options) {
    // Schema type is either a type or an array with null + a type (see JSON Schema docs)
    if (schema.type === 'string' || (Array.isArray(schema.type) && schema.type.indexOf('string') !== -1)) {
      var f = schemaFormProvide.stdFormObj(name, schema, options);
      f.key  = options.path;
      f.type = 'textarea';
      options.lookup[sfPathProvider.stringify(options.path)] = f;
      return f;
    }
  }); 

}]);
```

**Comment by nicklasb** [comment]
Answered, closing.
