### ISSUE TITLE
type image

### ISSUE THREAD

**Issue by fredlatorche** [json-schema-form/angular-schema-form#364]
Is there a simple way to use image type in angular schema form ("type": "image") ?
I need to admin a gallery with some standard type (Title, Description, ....) and image.
Perhaps a magick add-on ?

**Comment by Dervisevic** [comment]
It's not a default type, but it would be super simple to build. I built a similar one internally for an image uploader that shows the image as a preview. Basically the type should be string, have a url and then just use that URL in an img tag. 

Documentation on how to build an addon: https://github.com/Textalk/angular-schema-form/blob/development/docs/extending.md

Example addon: https://github.com/Textalk/angular-schema-form-colorpicker
