### ISSUE TITLE
Async Validator not called?

### ISSUE THREAD

**Issue by PhilBroadbent** [json-schema-form/angular-schema-form#365]
Hi, as per my question on SO Im having problems with validation.
In that case I don't have any specical validation, and am just leaving it up to schema-validate however it doens't behavior as i'd expect. 
I've tried to look into using custom validation, but Async validator doesn't seem to get called on my custom component. 

I crudely add asyncValidator into formDefinition like so:

      data.formDefinition[3][0].validationMessage = {
        'async': "Woah that number is too big!"
      };

      data.formDefinition[3][0].$asyncValidators ={
        'async': function(stopprice) {
          window.alert("blahblah");
          var deferred = $q.defer();
          $timeout(function(){
            if (angular.isNumber(stopprice) || stopprice > 20) {
              deferred.reject();
            } else {
              deferred.resolve();
            }
          }, 500);
          return deferred.promise;
        }
      };

The example in my SO question is a bit outdated, and I now have the dropdown and 2 fields which should be numbers (to allow for range search) - only one of the fields seems to get validated (and shows my custom message above) , the other field is not validated, and neither call the $asyncValidators? 

![image](https://cloud.githubusercontent.com/assets/7779879/7252574/5091963a-e82e-11e4-9724-c32bfe348175.png)

Can you please advise?

**Comment by davidlgj** [comment]
Is this in a custom field addon? Then I'd need to see the template and any other code to help :)

**Comment by PhilBroadbent** [comment]
Template:	

        <div class="form-group {{form.htmlClass}}" ng-class="{'has-error': hasError()}">

	  <div style="height: 45px;!important">

		<label class="control-label" ng-show="showTitle()">{{form.title}}</label>

		<div ng-class="{'input-group': (form.fieldAddonLeft || form.fieldAddonRight)}">
		<span ng-if="form.fieldAddonLeft"
			  class="input-group-addon"
			  ng-bind-html="form.fieldAddonLeft"></span>

		  <input style="float: right; width: 37.5%; background-color: white; " ng-show="form.key"
				 type="number"
				 class="form-control"
				 schema-validate="form"
				 ng-model="$$value$$.to"
				 integer/>

		  <select ng-model="$$value$$.operator" style="float: left; width: 25%;" class="form-control"
				  ng-options="operator as operator.label for operator in $parent.$parent.$parent.mappingUsedByDropdown[form.title]">
		  </select>

		  <input style="float: right; width: 37.5%; background-color: white; " ng-show="form.key"
				 type="number"
				 class="form-control"
				 schema-validate="form"
				 ng-model="$$value$$.from"
				 integer/>


		<span ng-if="form.fieldAddonRight"
			  class="input-group-addon"
			  ng-bind-html="form.fieldAddonRight"></span>

		</div>
	  </div>

	  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description }}</span>

	</div>

**Comment by davidlgj** [comment]
I don't know if this is what stops the async from working but one issue is that you use a `ng-model` and a `schema-validate` together, but that they "point" to different values.  

i.e: 
```html
     schema-validate="form"
     ng-model="$$value$$.from"
```

The `form` has a key that matches what gets replaced by `$$value$$` and so does `form.schema`. So basically it will try to validate with the wrong part of the schema. 

So there are several solutions to this:
* Skip schema-validate and do validation on your own, as long as you require the `ngModelController` and hook into that validation in a standard angular way then you'r all good. 
* Just use one `ng-model` with just `$$value$$` and a `schema-valdiate="form"` with it on top level that validates the entire object. (This is probably the easiest way)
* Construct a proper form object for `schema-validate` that has a key and schema that matches the path in the `ng-model`. But this has several traps, error messages being one of them. Look into the source of `schema-validate` if you are going with this. 
* Let the subfields be their own form types (with small templates) so that your "master" add-on includes them (much a fieldset, tabs etc does)

**Comment by PhilBroadbent** [comment]
Thanks David.

I'm not sure I follow some of the options - here is my feedback/questions for each:

1) Haven't done any schema validation before - I was hoping to use async but I will have to try this approach if the below options don't work. 

2) If I use only ng-model then I can't have 2 fields as each one will overwrite the model - this is why I gave the model a sub object...if that makes sense?

3) Proper form object - If I made teach one separate then they would take up a full slot rather than just 33% surely? But you advised against this one anyway. By this one, would that be where form has got a mapping for $$value$$.operator (e.g. model[price].operator) etc right?

4) For the subfields how would you put that into the form?? Very confused by this one - is there an example please?

**Comment by davidlgj** [comment]
Ok, let me try to answer you:
1) What I mean is that you should not validate against the schema but do it the "angular way", i.e. add validation with `ng-required`, `ng-min` etc and create a directive that requires the `ngModelController` and add your async validator to it. 

2) I guess you'll end up with three ng-models in this case, one for the entire object, i.e. $$value$$, and that is the one with schema-validate on it. The other ones are the ones you have today, but without schema-validate on them.

3)  33%? what do you mean by slots? I'm talking about the schema-validate directive, the "form" object you give it has a schema, and that must match whatever value you have in the ng-model, so when you do a sub property of $$value$$ that must have a matching form.

4) Checkout `fieldset` type, it use "items" but you can call them whatever you like, then you just invoke them by using the `<sf-default form="">` directive.

Let's say you create four form types, "stopprice", "from", "operator" and "to", then the form object for "stopprivr" could look something like this: 
```js
{
  type: 'stopprice',
  key: 'theObj',
  items: [ 
    { type: 'comp',   key: 'theObj.to' }, 
    { type: 'comp',   key: 'theObj.operator' }, 
    { type: 'value', $asyncValidators: {....},   key: 'theObj.from'} ]
} 
```

And the form something like this:
```html
  <div class="form-group {{form.htmlClass}}" ng-class="{'has-error': hasError()}">

  <div style="height: 45px;!important">

    <label class="control-label" ng-show="showTitle()">{{form.title}}</label>

    <div ng-class="{'input-group': (form.fieldAddonLeft || form.fieldAddonRight)}">
    <span ng-if="form.fieldAddonLeft"
          class="input-group-addon"
          ng-bind-html="form.fieldAddonLeft"></span>

         <sf-default form="form.items[0]"></sf-default>       
        <sf-default form="form.items[1]"></sf-default>
         <sf-default form="form.items[2]"></sf-default>


    <span ng-if="form.fieldAddonRight"
          class="input-group-addon"
          ng-bind-html="form.fieldAddonRight"></span>

    </div>
  </div>

  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description }}</span>

</div>
```

Of course the other types needs small templates as well.

**Comment by PhilBroadbent** [comment]
Sorry for slow respones David. I have not started work on this task yet so haven't looked into it.  
These solutions look pretty complicated! 1 is probably what I'll have to do,  4 seems okay but still confused by 2 and 3.

2) Not sure how entire object would have a model - if the other parts have a separate model, then when you insert any data the "entire object model" won't get updated at all....I will have to try.
3) By slot i mean one form element.  Take this picture for example. You can see that Transaction Time takes up 1 "slot", then Stop price takes up another "slot", but it is split up into a 25% dropdown, and 75% input field...and in the one in my original message, the sections take up 33% of a slot. So I meant instead of being just 1 slot split up, it would take up several surely
![image](https://cloud.githubusercontent.com/assets/7779879/7516209/82d388c6-f4c5-11e4-9d4d-c8838814339d.png)

**Comment by nicklasb** [comment]
Can we close this?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
