### ISSUE TITLE
List/array of all form validation errors?

### ISSUE THREAD

**Issue by souluniversal** [json-schema-form/angular-schema-form#376]
Looking for a way to get a list of all form validation errors. We tried what was suggested here:  http://stackoverflow.com/questions/22322925/angularjs-list-all-form-errors however... the outout on $error etc. was strange/unusable (i.e. key names of "{{form.key.slice(-1)[0]}}"). 

Is there a way to get an array of the errors (especially error messages) after validation?

We have a large form and would like to use growl to present a list rather than have the user have to hunt up and down the page exclusively to locate each of the error fields.

**Comment by davidlgj** [comment]
Yo can do some angular black magic and use the `sfErrorMessages` to get the actual error messages from the error code. Something like this:

```js

var errors = [];
$('[schema-validate]').each(function() {
  // schema-validate directive puts the ngModelController on scope as `ngModel`
  // from that we can get error codes
  var scope = $(this).scope();
  var sfErrorMessage = $(this).injector().get('sfErrorMessage');
  var errs = angular.copy(scope.ngModel.$error);
  delete errs.parse;
  var error = Object.keys(errs)[0];
 
  if (error) {
    errors.push({
      title: scope.form.title,
      error: error,
      msg: sfErrorMessage.interpolate(
                error,
                scope.ngModel.$modelValue,
                scope.ngModel.$viewValue,
                scope.form,
                scope.options && scope.options.validationMessage
              )
    });
  }
});

console.log(errors);
```

**Comment by punknroll** [comment]
When i put this code inside my controller $('[schema-validate]') is empty. So nothing to "each" about.

**Comment by punknroll** [comment]
I had to wrap that inside a $timeout function to make this work!

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
