### ISSUE TITLE
Inserting $index into titles of array items

### ISSUE THREAD

**Issue by TrevorPage** [json-schema-form/angular-schema-form#382]
I am creating an array of controls, such as an array of selects.

I would like to have the `title` of each control interpolated with the current array `$index` such that the captions for the select controls are "Item 1", "Item 2", and so on. On reading the documentation, it seems that only the `title` used in a `tabArray` is interpolated, but not for `array`. Is there any way to do this? I have tried inserting `arrayIndex`, `$index`, `{{$index}}` etc. but without any success.

**Comment by marcussaad** [comment]
@TrevorPage, not sure if It's the best approach but what I've done was to create a variable to hold it in my custom directive, such as ```{{form.orderingNumber}}```, and when generating the form, I simply pass an index that is being looped over. Hope it helps.

**Comment by TrevorPage** [comment]
Thanks @marcussaad, the tip is much appreciated! Is there any possibility you could please show a small example to illustrate this? Is this something that you are somehow using within a custom input directive?

**Comment by TrevorPage** [comment]
Ah, it looks like what you're doing is explained in this issue quite well: https://github.com/Textalk/angular-schema-form/issues/375

**Comment by marcussaad** [comment]
@TrevorPage  indeed! In the form definition, just make sure you provide ```"orderingNumber": $index``` or whatever your index variable might be :D

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
