### ISSUE TITLE
Divide array in 3 columns

### ISSUE THREAD

**Issue by subhendupsingh** [json-schema-form/angular-schema-form#383]
Can we divide "type":"array" in 2 or 3 columns and have a tabarray with horizontal tabs? Please suggest a workaround.

**Comment by davidlgj** [comment]
I don't think I understand, do you want the same array flowing over three columns? 
Columns can be achieved by using standard bootstrap classes, see http://schemaform.io/examples/bootstrap-example.html#/4fa8967ae5596fe8b0c0

`tabarray` type has support for horizontal tabs, just set `tabType` to `"top"`, here are the docs https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#tabarray

**Comment by arteme** [comment]
In my project I achieve columns by splitting the items array in half using a custom fieldset decorator like:
```html
<fieldset ng-disabled="form.readonly" class="schema-form-fieldset schema-form-fieldset-columns {{form.htmlClass}}">
  <legend ng-show="showTitle()">{{ form.title }}</legend>
  <div ng-show="form.description" ng-bind-html="form.description"></div>
  <div class="column">
    <div class="row">
    <sf-decorator ng-repeat="item in form.items|arrayHalf" form="item"></sf-decorator>
    </div>
  </div>
  <div class="column">
    <div class="row">
    <sf-decorator ng-repeat="item in form.items|arrayHalf:1" form="item"></sf-decorator>
    </div>
  </div>
</fieldset>
```

The `arrayHalf` filter is really easy to implement...

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
