### ISSUE TITLE
Key-Value object support

### ISSUE THREAD

**Issue by dstelter** [json-schema-form/angular-schema-form#385]
I would like to create a form for a key-value object, i.e. where the user can specify both key and value. Unfortunately this doesn't seem to be supported yet.

So far my workaround is to transform the object to an array of `{key: ..., value: ...}` objects, which works well, but feels kind of wrong. Is there a better way to handle key-value objects?

**Comment by davidlgj** [comment]
Your workaround sounds like the one I'd use. Other than that you can always create an add-on for it (or maybe use `template` form type + custom directive). Then you could have a schema with an object that has `additionalProperties` set and any kind of UI you want.

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
