### ISSUE TITLE
Custom validation doesn't work with 'schemaFormValidate' event

### ISSUE THREAD

**Issue by aantipov** [json-schema-form/angular-schema-form#388]
Hi there!
I use 0.8.2 version of schema-form.
I created custom validator with the help of `$validators` property as described at https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#validators
The problem is that the validator is not called on `schemaFormValidate` event.
In other cases it works well.

It that is a bug?

**Comment by davidlgj** [comment]
Yes I believe it should do that, right now it just calls the JSON Schema validation. Marking it as a bug

**Comment by MattiJarvinen-BA** [comment]
:+1:

**Comment by riggerthegeek** [comment]
Is there any progress with this issue?

**Comment by shravanmahankali** [comment]
is this fixed?

**Comment by Anthropic** [comment]
@shravanmahankali I believe it is in the alphas, please re-open if tit needs more work though, thanks for pointing it out.

**Comment by binodgrg** [comment]
Any idea when this will be fixed and is there a way to trigger the $validators separately?

**Comment by Anthropic** [comment]
@binodgrg you mean in 0.8.13? Have you tried the alpha release? It's called alpha as feature set is not locked yet, however in many ways it is as stable as 0.8.13 depending on requirements.
