### ISSUE TITLE
Home Page Color Scheme - Bad for color blind, vision issues

### ISSUE THREAD

**Issue by mikeerickson** [json-schema-form/angular-schema-form#389]
Hey gang

Just wanted to let you know that the color scheme you have used for home page makes it literally impossible to read for those with vision issues (such as myself).

Typically, I need dark themes for optimal viewing.  However, when this is not available I have to use 'Invert Color' mode.   When doing this adjustment on your site, the inverted color is also impossible to read.

Should you wish to address this issue and need some feedback, please let me know.

**Comment by Dervisevic** [comment]
This sounds interesting to me and something I could adress with an alternate theme. More information about what kind of colors would work and any general info is appreciated.

**Comment by mikeerickson** [comment]
I have cataracts in both eyes as well as damanaged lenses.   So, when I look at a page with a lot of high contrast, it is almost impossible to read unless I switch to inverted color mode.

It the case of your site, the initial color (turquoise as I believe) is very difficult to see the text on the default background.

When I invert the colors, that background switches to dark red with black text and believe it or not, that is even harder to read.

If you need any further details, or want to run some designs by me, I would be happy to help.

BTW, this package looks pretty sweet :-)

**Comment by Dervisevic** [comment]
So i started playing around with the colors, and i got hung up on one thing you mentioned:

>  So, when I look at a page with a lot of high contrast, it is almost impossible to read...

I always thought high contrast was good for low visibility, so I'm wondering, do you prefer low contrast? Ie colors that are close in the wheel, the "not effective" part of this image: 
![color_wheel_contrast](https://cloud.githubusercontent.com/assets/541475/7680282/30a5da42-fd65-11e4-83cf-eab6d16c3618.gif)

I have some mockups here, take a gander at them and say what works and what doesn't, and any guidelines you have. 

![screen shot 2015-05-18 at 13 49 45](https://cloud.githubusercontent.com/assets/541475/7680297/4ea6aaa8-fd65-11e4-974c-80d351682324.png)
![screen shot 2015-05-18 at 13 49 54](https://cloud.githubusercontent.com/assets/541475/7680298/4ea6d870-fd65-11e4-9dfa-bf9b7eba69f1.png)
![screen shot 2015-05-18 at 13 50 13](https://cloud.githubusercontent.com/assets/541475/7680299/4ea76a6a-fd65-11e4-91d1-cd1cb0c6ae07.png)

**Comment by mikeerickson** [comment]
@Dervisevic Sorry for confusion, my statement about contrast was "backwards"  it is worse with the higher contrast.    

With regards to these examples, all are visible when viewed "Inverted" but the last page is somewhat harder to read (but still legible)

If I had to pick the best theme, it would be the second one.  Either 1 or 2 are good though as they are primarily black background

**Comment by Dervisevic** [comment]
Ok i think i have something to go on, will get to finalizing it whenever i can.

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
