### ISSUE TITLE
Unexpected end of expression: model.

### ISSUE THREAD

**Issue by stephenbaidu** [json-schema-form/angular-schema-form#391]
When using the `template` type, I get the error below
`Error: [$parse:ueoe] Unexpected end of expression: model.`

I used the below example in the docs and the same error occured.

```javascript
$scope.form = [
  {
    type: "template",
    template: '<h1 ng-click="form.foo()">Yo {{form.name}}!</h1>',
    name: 'Ninja',
    foo: function() { console.log('oh noes!'); }
  }
];
```

**Comment by Dervisevic** [comment]
When i run the code in the [examples page](http://schemaform.io/examples/bootstrap-example.html#/782015f4246022f5d17f) it works (except for the click but that's cause the input is JSON not JS.) So it has to be a local setup issue, straight off the bat, do you have a sf-model attribute on the directive?

**Comment by nicklasb** [comment]
No answer, closing.
Please re-open if you do not feel the question has been answered sufficiently.
