### ISSUE TITLE
value of field rendered with templateUrl is not passed in the parent sf-model

### ISSUE THREAD

**Issue by subhendupsingh** [json-schema-form/angular-schema-form#392]
Value of field rendered with templateUrl is not passed in the parent sf-model although i am sharing the same model with this field as with other sf fields. Also this field is not getting validated on submit.

My template is select2 dropdown  and i am using ng-model="model" same as in sf-model="model"

**Comment by davidlgj** [comment]
Could you paste your template type?

**Comment by Anthropic** [comment]
Please re-open if you still need help and can provide a plunker or gist.
