### ISSUE TITLE
How to differ type of errors in validation Messages

### ISSUE THREAD

**Issue by franciscopuyo** [json-schema-form/angular-schema-form#411]
Hi, how are you?
The fact is that validation messages are modifiable but I can not set an specified error depending of the cause.

For example: if a string is very long I wanna say: "Sorry, your string is very long", and if it's bad written (not support a pattern) "Please check what you've written" 

Anything tell me,
Thanks 

Francisco

**Comment by Dervisevic** [comment]
The validation messages can be overloaded on a case to case basis, i.e. you set an object with messages for every type of validation error that can occur. Read more about how to do it in the [documentation](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#validation-messages).

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
