### ISSUE TITLE
Fieldset with checkboxes

### ISSUE THREAD

**Issue by lucas-ribeiro** [json-schema-form/angular-schema-form#416]
This is basically a follow-up to #400, but it raises the question if this is an actual bug, or a misconception from my part.

The main issue relies on the fact that I have a form and some of the questions have predefined options (displayed as checkboxes) and an optional text field for the user to write its own answer ("If other, please identify" - check #400 for images)

After going through the docs, I realized that the best solution for our case would be to have a `type: "object"` schema for the question, defining two properties: `Options` as an array (later to be mapped as checkboxes), and `Answer` as a string. Here's the relevant snippet of the schema object:

```javascript
{
    "type": "object",
    "title": "Survey",
    "properties": {
    
        "4": {
            "type": "object",
            "title": "Magazine Subscriptions?",
            "items": {
                "properties": {
                    "Options": {
                        "type": "array"
                    },
                    "Answer": {
                        "type": "string",
                        "title": "If other, please identify"
                    }
                }
            }
        }
    }
}
```

and here's the form object for that question:

```javascript
[
    {
        "key": "4",
        "title": "",
        "disableSuccessState": true,
        "type": "fieldset",
        "items": 
        [
            {
                "key": "4.Options",
                "title": "Magazine Subscriptions?",
                "type": "checkboxes",
                "titleMap": [
                    {
                        "value": "16",
                        "name": "Men's Health"
                    },
                    {
                        "value": "17",
                        "name": "Women's Health"
                    },
                    {
                        "value": "21",
                        "name": "None"
                     }
                ]
            },
            {
                "key": "4.Answer",
                "title": "If other, please identify",
                "type": "string",
                "htmlClass": "col-md-6"
            }
        ]   
    }
]
```

Maybe I'm doing something wrong, because even though the form is displayed correctly, when I click any of the checkboxes, I get the following error:

```
TypeError: Cannot read property 'length' of undefined
    at schema-form.js:1613
    at Object.fn (angular.min.js:109)
    at h.$get.h.$digest (angular.min.js:110)
    at h.$get.h.$apply (angular.min.js:113)
    at HTMLInputElement.<anonymous> (angular.min.js:187)
    at HTMLInputElement.n.event.dispatch (jquery-1.11.0.min.js:3)
    at HTMLInputElement.n.event.add.r.handle (jquery-1.11.0.min.js:3)
```

Can someone point me in the right direction?

**Comment by davidlgj** [comment]
I think the problem might be the key  `"4"`. Using just a number might confuse  `ng-model` and `sfSelect`, mistaking it for an index in an array when updating the model. Try switching that out our just add some character, like "option4".

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by brandontrabon** [comment]
I'm just wondering if there is a way to use dot notation with the fieldset object? In our system we must use dot notation and I have created a custom ASF control that works like fieldset and makes ASF work with dot notation. I really don't want to have to create a custom "fieldset" object just to make this work so if anyone has an idea I would appreciate it.
