### ISSUE TITLE
Model does not match condition

### ISSUE THREAD

**Issue by ymarcon** [json-schema-form/angular-schema-form#425]
When a condition is set on a field, there can be situations where the model has a value for this field but the condition is not valid.

To reproduce, this is the schema:

``` javascript
{
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "title": "Name"
        },
        "eligible": {
            "type": "boolean",
            "title": "Eligible for awesome things"
        },
        "code": {
            "type":"string",
            "title": "The Code"
        }
    }
}
```

and this is the form:

``` javascript
[
    "name",
    "eligible",
    {
        "key": "code",
        "condition": "model.eligible"
    }
]
```

The steps are:
- check "eligible": the field "code" becomes visible
- enter a value for "code"
- uncheck "eligible": the field "code" is hidden but the model still contains the value

The resulting model is:

``` javascript
{
  "eligible": false,
  "code": "a code value"
}
```

**Comment by ymarcon** [comment]
I see in #371 that it will be fixed in the next release, thanks!

**Comment by ymarcon** [comment]
I just tested with the latest commit and the example provided still does not work. It works with arrays but not with that simple example.

**Comment by xArthasx** [comment]
I have the same issue.

**Comment by saiacn** [comment]
I have the same issue.

**Comment by ryantehbaker** [comment]
hi

**Comment by Anthropic** [comment]
@ryantehbaker I tried @ymarcon's example on the example [plunker](https://plnkr.co/edit/C9mM5feGGZ0N7povA84G?p=preview) and it worked fine.
