### ISSUE TITLE
Plug-in community and Angular 2.0

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#426]
Hi,
I have a proposition and a question.

## Plug-in community repo

It seems like there are quite a lot of plug-ins for ASF now, however, I don't feel that there is any place to talk about plug-in development particular, and a place to share information, tools, examples and snippets.
So I created a repository to sort of show what that could be like. It has a:
* Repo for branch specific docs, tools, examples and snippets
* A gitter room for discussion(just invite all plug-in devs)
* A wiki for non version specific information, like guidelines or whatever.

In short, a normal github repo has all the things needed for this, nothing else has to be done.
The repo is here:  https://github.com/OptimalBPM/angular-schema-form-add-ons

This could either be organized under Textalk's umbrella, or if you wanted, It could stay there and I take the responsibility for it. Either way, something like this would have been very helpful during the [ASFDS](https://github.com/OptimalBPM/angular-schema-form-dynamic-select)-development, where I felt that there was no real place for the plug-in ecosystem.
Also, plug-in development feels like a slightly different thing than what is mainly supposed to be discussed in the main gitter for ASF. 

So I would like to help lower the bar for plug-in development, not only to get more people making PRs for ASFDS, but because I feel that there are many promising plug-ins that aren't getting the love they need. More of that love would be useful for me. 

## Angular 2.0

So, Angular 2.0 will be out next year. To begin with, to successfully move to that, it is important to coordinate with the plug-in developers(these are very hard lessons from the Python 2 to 3 transition).

But the question is if moving to that is something being considered?
(I should not be *that* hard?)
 
-- Rock on

**Comment by davidlgj** [comment]
Hey nice idea! I think its fine with the repo you created, to be honest I'm having a hard time keeping up  as it is so I don't want more work :) 

Regarding Angular 2.0, I got my eye on it. The first step I think will be to de-couple the parts that are not actually that bound to angular to a "vanilla" js lib, i.e. the form and schema parsing and validation helper methods, the DOM builder (when I'm done with it). Because let's face it Angular 1.x isn't going away anytime soon at it would be nice if we could support both with as much common code as possible.

**Comment by nicklasb** [comment]
1. Well, I guess I had sort of anticipated that answer, let's say it was in the stars. :-) 
I'll evolve that a little further and get back to you.

2. No, 1.x wont leave soon, sadly. On the other hand, the ones pushing 2.0 is  *Google*, not some Guido van Rossum-guy-in-basement. Ok. Not that he actually was in a basement. :-) 

My lesson from following Py 2-3 is this people who lumber on for years without moving on to the new version are sort of involved in open source for the wrong reasons, the run projects with such a large focus on satisfying business needs that they simply don't give very much back to the community, where the need is more of a technical one. That is when their normal use cases work. Also, and honestly, they are even more hesitant to change framework altogether, so "losing" them is quite unlikely. Better to push them on.

I have actually seen these people kill projects by constantly posting angry stuff about betrayal and abandonment. This because they often haven't touched their own code for years and no longer are very familiar with it, so they get super-agitated when someone suggests that the time is up, and if the project leaders aren't tough enough, its the end of that project because everyone hates supporting old crap and be restricted.

So I'd say, one year of supporting 1.x, tops.  
Because first, ASF is big enough to move like that but not too big to have a huge internal 1.x investment(i'd say Textalk seems alright in that regard), and second, during a year it is acceptable to maintain a 1.x bug fix branch. Because they are fundamentally incompatible, at least in the view code, so I am not sure if there is that much of a point with maintaining both at the same time. Schema form is already so close to feature-"alright" that most users with existing investments are rather involved in developing business features than new UI concepts. 

Either way, the most important part is to clearly and early communicate one's intentions.

So that was *all* I know about major version-migration in frameworks/languages and my conclusions. I have no more information of views. Do with it/them what you may. :-)

**Comment by nicklasb** [comment]
Ok, so now I have done a little more with the add-ons dev-repo, among other things I renamed it as I realized it is not called plug-ins in ASF. 

I hope that it now is a little more apparent what the goal of it is and how I am thinking it is supposed to be used. I also hope that other add-on devs see it the way I do, at least I have now invited all those that seemed add-on-project-manager-y.

I am not sure what to do with the "extends.md"-article, though. I have put it under /documentation and all, and I assume it is not a document that is frequently edited. I have started writing some general stuff on the wiki, but with regards to the technical, it will stay in the repo-based docs so it is the easy to just switch branches. 

Also, is there some minimalistic example of a plugin somewhere that I can use in the examples?

**Comment by Dervisevic** [comment]
Maybe there are ones that are more minimal but the smallest one i have is the colorpicker, as it uses a jquery based lib, so it's pretty small. https://github.com/Textalk/angular-schema-form-colorpicker

**Comment by nicklasb** [comment]
Thanks. So far, though, I have received exactly *zero* feedback from anyone except you, so perhaps I am wrong about this whole thing. 
It's just that add-on ecosystems are very important to most frameworks, if there is no interest from the ASF add-on devs to communicate(at least in some way) and help ease others into it, I become a bit worried.

**Comment by mike-marcacci** [comment]
Hey @nicklasb, just to chime in on behalf of some other external users who are heavily invested into ASF. I think you're probably far ahead of the curve regarding angular 2.0, and I imagine most of us have been holding off until we might have something useful to contribute to the conversation. Up until today, I simply haven't had the time to even get a good first good look, and I doubt I'm alone.

I think as Angular 2.0 approaches beta you'll see rapidly increasing interest in this topic. Also, I have a sense that Angular's audience is much more hungry for change than the Python community was back in 2009, so I think your 1 year plan seems appropriate.

I agree that an ecosystem is extremely important to the adoption curve of any framework and do feel that ASF has enough momentum in that regard.

**Comment by nicklasb** [comment]
Thanks for your response. 
I would not say that starting planning development for something significant that known to happen just a year later is being ahead of the curve, but each to ones own, I guess.

WRT to hunger and vs python, obviously, I cannot say for certain. 
But a large number of commercial projects are likely currently being built on 1.3. This is a mixed blessing, as many of those one now feel are so much behind the momentum of 1.3 might not behind the momentum of 2.0 at all, but rather putting their efforts into the opposite, keeping 1.3 viable. 

It is really hard to sell a significant rewrite to management for purely technical reasons in most companies, the gains are far to long-term and why not wait until everyone else tried it and so on. 
So this will demand very strong leadership from Google(probably Microsoft will have to get in there, too). 

And I am not a pessimist or alarmist, I assure you.

Also, perhaps I should have been more clear, I was asking for feedback on the concept of an external location for the add-on community and if other add-on devs would be interested in partaking, AngularJS 2.0 was more of an example of a topic.

**Comment by nicklasb** [comment]
(heavily edited the above post, as there were some traces of these really heavy midsummer's eve celebrations in Sweden, that occurred yesterday) :-)
