### ISSUE TITLE
Onchange update the Schema not working 

### ISSUE THREAD

**Issue by senthilsendhil** [json-schema-form/angular-schema-form#428]
I like to update my schema after Form loader through onChange, 

but schema not getting updated, Please refer the below controller code.
```javascript
 $scope.testOnchange = function() {
    console.log('came here');
    $scope.schema.properties.profileDetails.properties.address.properties.
    addressDetails.items.properties.addressFormat = ['dym', 'dym1'];
    $scope.$broadcast('schemaFormRedraw');

  };
  $scope.schema = {
    "type": "object",
    "title": "Comment",
    "properties": {
      "profileDetails": {

        "type": "object",
        "properties": {
          "address": {
            "type": "object",
            "properties": {
              "addressDetails": {
                "title": "Contact Person",
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object",
                  "properties": {
                    "addressType": {
                      "title": "Contact Type",
                      "description": "Select",

                      "type": "string",
                      "default": "test",
                      "enum": ["test", "test1"]
                    },
                    "addressFormat": {
                      "title": "Address Format",
                      "description": "Select",
                      "type": "string",
                      "default": "test",
                      "enum": []
                    }
                  }
                }
              }
            }
          }
        }
      }

    }
  };


  $scope.form = [{
      "key": "profileDetails.address.addressDetails",
      "title": "The array",
      "type": "array",
      "items": [{
          "key": "profileDetails.address.addressDetails[].addressType",
          "onChange": "testOnchange()"
        }, {
          "key": "profileDetails.address.addressDetails[].addressFormat",

        }



      ]
    }, {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    }

  ];

**Comment by davidlgj** [comment]
So you've hit this bug: https://github.com/Textalk/angular-schema-form/issues/395

Try doing an angular copy of the form definition whenever you update the schema, something like:

```js
$scope.testOnchange = function() {
    console.log('came here');
    $scope.schema.properties.profileDetails.properties.address.properties.
    addressDetails.items.properties.addressFormat = ['dym', 'dym1'];
    $scop.form = angular.copy($scope.originalForm);
    $scope.$broadcast('schemaFormRedraw');

  };
  $scope.schema = {
    "type": "object",
    "title": "Comment",
    "properties": {
      "profileDetails": {

        "type": "object",
        "properties": {
          "address": {
            "type": "object",
            "properties": {
              "addressDetails": {
                "title": "Contact Person",
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "object",
                  "properties": {
                    "addressType": {
                      "title": "Contact Type",
                      "description": "Select",

                      "type": "string",
                      "default": "test",
                      "enum": ["test", "test1"]
                    },
                    "addressFormat": {
                      "title": "Address Format",
                      "description": "Select",
                      "type": "string",
                      "default": "test",
                      "enum": []
                    }
                  }
                }
              }
            }
          }
        }
      }

    }
  };


  $scope.originalForm = [{
      "key": "profileDetails.address.addressDetails",
      "title": "The array",
      "type": "array",
      "items": [{
          "key": "profileDetails.address.addressDetails[].addressType",
          "onChange": "testOnchange()"
        }, {
          "key": "profileDetails.address.addressDetails[].addressFormat",

        }
      ]
    }, {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    }

  ];
  $scop.form = angular.copy($scope.originalForm);
```

**Comment by senthilsendhil** [comment]
@davidlgj below error I am getting

Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"schemaForm.form[0]","newVal":{"title":"profileDetails","schema":{"type":"object","properties":{"address":{"type":"object","properties":{"addressDetails":{"title":"Contact Person","type":"array","minItems":1,"items":{"type":"object","properties":{"addressType":{"title":"Contact Type","description":"Select","type":"string","default":"test","enum":["test","test1"]},"addressFormat":["dym","dym1"]}}}}}}},"ngModelOptions":{},"type":"fieldset","items":[{"title":"address","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Person","schema":"<<already seen>>","ngModelOptions":{},"type":"array","key":["profileDetails","address","addressDetails"],"items":[{"title":"addressDetails","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Type","description":"Select","schema":"<<already seen>>","ngModelOptions":{},"key":["profileDetails","address","addressDetails","","addressType"],"type":"select","titleMap":[{"name":"test","value":"test"},{"name":"test1","value":"test1"}]}]}]}]}]}}],[{"msg":"schemaForm.form[0]","newVal":{"title":"profileDetails","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"address","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Person","schema":"<<already seen>>","ngModelOptions":{},"type":"array","key":["profileDetails","address","addressDetails"],"items":[{"title":"addressDetails","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Type","description":"Select","schema":"<<already seen>>","ngModelOptions":{},"key":["profileDetails","address","addressDetails","","addressType"],"type":"select","titleMap":[{"name":"test","value":"test"},{"name":"test1","value":"test1"}]}]}]}]}]}}],[{"msg":"schemaForm.form[0]","newVal":{"title":"profileDetails","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"address","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Person","schema":"<<already seen>>","ngModelOptions":{},"type":"array","key":["profileDetails","address","addressDetails"],"items":[{"title":"addressDetails","schema":"<<already seen>>","ngModelOptions":{},"type":"fieldset","items":[{"title":"Contact Type","description":"Select","schema":"<<already seen>>","ngModelOptions":{},"key":["profileDetails","address","addressDetails","","addressType"],"type":"select","titleMap":

**Comment by shikshik** [comment]
@senthilsendhil There is typo
"$scop.form" should be "$scope.form" (might be the issue for your case)
Cheers.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
