### ISSUE TITLE
Compact side-by-side layout

### ISSUE THREAD

**Issue by lobetuf** [json-schema-form/angular-schema-form#432]
Hi - i can't seem to find anything in the doc or examples showing if it's possible to layout the form such that the labels are to the side of the field, instead of above.  I'd like that for space saving purposes.  Can anyone shed some light on this?  I hope I'm just not looking in the right spot.

Thanks!

**Comment by davidlgj** [comment]
There isn't a compact side by side layout implemented. Basically you can either use CSS to force it around or make a copy of the "bootstrap decorator" part of the project and modify the templates.

**Comment by jbsaff** [comment]
The boostrap grid layout can be applied by setting a htmlClass of row, labelHtmlClass as col-xx-* and fieldHtmlClass. One caveat: radio and checkbox lists apply the fieldHtmlClass to each input tag, so you may need to leave the fieldHtmlClass undefined for those types of questions. Unless you need something complicated, that'll get you most of the way there.

**Comment by Anthropic** [comment]
Please re-open if you feel the answers were insufficient and you require more information.
