### ISSUE TITLE
Validation not working on custom type

### ISSUE THREAD

**Issue by azadacme** [json-schema-form/angular-schema-form#438]
i have added new type. all working well. bt i hv one problem schema-validate directive is not working on my new custom type. 

my htm with custom typel:
```html
<div class="form-group" ng-class="{'has-error': hasError()}">
  <label class="control-label" ng-show="showTitle()">{{form.title}}</label>

<input 
         type="text" 
         class="form-control" 
         schema-validate="form" 
         ng-model="$$value$$" 
         default-location
         name="{{form.key.slice(-1)[0]}}" />
         
      <span class="help-block" sf-message="form.description"></span>
</div>
```

**Comment by nicklasb** [comment]
You need to explain this better, and perhaps add a plunkr/gist for debugging.

**Comment by Anthropic** [comment]
@azadacme I updated your question to format it correctly, but I can't see anything obvious without the rest of the code, can you create a plunker if this is still an issue and re-open please?
