### ISSUE TITLE
Minimal example based on colorpicker

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#439]
Hi,
So I am creating a minimal [example](https://github.com/OptimalBPM/angular-schema-form-add-ons/tree/master/examples) for a ASF add-on based on the colorpicker add on.

Of course, I am trying to do it correctly, following any conventions, and I realized am not completely sure about the naming of javascript file, it is called bootstrap-colorpicker, and I am not sure why, as it more jquery-based than bootstrap-based. Also, not many other add-ons use the bootstrap-xxx.js naming scheme.
It feels a little bit confusing to me, its path in the template cache should be enough?

**Comment by Dervisevic** [comment]
I don't quite remember why that is, probably didn't give it much thought. Should probably be changed to follow some sort of standard.

**Comment by nicklasb** [comment]
If I may make a suggestion, I would propose that the standard would be the same as the full name of the add-on, as that:
1. Can't be all that wrong.
2. Is common already
3. Easy to remember. The same as the containing bower_components-folder.
4. Makes it easier to see where one is while debugging. Also, for example, "main.js", or a subset of the name may conflict with code that interact with the the component.

**Comment by nicklasb** [comment]
Next question:

According to most style guides and documents, the common unit of indentation of JS, and also the upcoming Typescript, is 4 spaces. And personally, I am a four space guy. 

However, ASF seem to use 2 spaces. And I know that this, for some reason, is a somewhat contentious subject. Some people think 2 spaces looks better.

The problem is that most IDE:s are preset to four spaces for .js files, and they constantly complain of the indentation. And it seems a little bit crappy when an example immediately triggers negative responses.

Is it OK to use 4 spaces in the example? To get people to adhere to these standards, it could be a good form to follow the others, just sayin'.

**Comment by nicklasb** [comment]
Question 3:
When returning the schemaFormProvider provider for the default, can't the caller of the function add the key to the options.lookup dict? It seems strange that you always have to do the `options.lookup[sfPathProvider.stringify(options.path)] = f;`. And then return f to something that probably could be able to do that itself as it is obviously passing the options parameter. Are there situations where you do not wan't that to be done?

**Comment by nicklasb** [comment]
Hi,
So now I have created an [example](https://github.com/OptimalBPM/angular-schema-form-add-ons/tree/master/examples/camelcase).
It wasn't as *super-minimal* as I thought it would be, but it contains some important tricks.

I am thinking of creating a *really* minimal version, with just an input and a label, or something.

**Comment by nicklasb** [comment]
Whatever, I made a [minimal example aswell](https://github.com/OptimalBPM/angular-schema-form-add-ons/tree/master/examples/minimal).

**Comment by nicklasb** [comment]
I have now started a make-over of the extending ASF documentation, the goal is to make it more easy to understand, consequently I have another question.

Question 4:
It uses the expression "field", "type of field", as in "adding a new field". I cannot see anything happening other than adding form types, not fields or field types. Have I misunderstood something?
If not, I will unify to only talking about field types.

**Comment by nicklasb** [comment]
So now I have made a rewrite of the extending article, in addition to trying to make it a little bit more easy to follow, I have used the "minimal" and "camelCase" examples throughout, instead of datepicker, as they have only the data that is needed:
https://github.com/OptimalBPM/angular-schema-form-add-ons/blob/New_Extending/documentation/extending.md

I do have another question:

Question 5:
What is the typical use case for the "add a new decorator"-way of extending ASF?

**Comment by nicklasb** [comment]
I would be grateful if someone could proofread it and give me some feedback.

**Comment by nicklasb** [comment]
I have now also added a Python script that creates a new add-on based on one of the examples:
https://github.com/OptimalBPM/angular-schema-form-add-ons/tree/master/tools
