### ISSUE TITLE
Problem: when use $scope.$broadcast('schemaForm.error.key', errorCode, true) the field still marked invalid.

### ISSUE THREAD

**Issue by ulion** [json-schema-form/angular-schema-form#440]
here's my usecase:

2 date field, one for begin date, one for end date, the custom validator try to notify user the beginDate should less than endDate, and both of them are required fields.

```
$validators: {
              beginLessThanEnd: function (v) {
                // following just sample code, not real working code
                var valid = beginDate < endDate
                $scope.$broadcast('schemaForm.error.' + (key === 'endDateTime' ? 'beginDateTime' : 'endDateTime'), 'beginLessThanEnd', valid);
                return valid;
              }
}
```

When I set beginDate larger than endDate, it does correctly mark 2 fields with the error message I setup, when I set beginDate back to smaller date, it get both fields valid, it's good. but, if instead, I set the endDate to a larger date then the beginDate, the endDate will be valid, but the beginDate is still invalid.

The reason of these is that the beginDate field got the "undefined" value at the initial validation failure, when the endDate get larger, the beginDate is still have "undefined" modelValue (but the viewValue is what you see in browser), then it use the undefined value to check validation (inited by the "scope.$broadcast('schemaFormValidate');" call inside the schemaForm.error broadcast handler), it will result an 302 required error of tv4.

Any ideas to resolve this? I'm using the current master branch code. with angular 1.3.14

**Comment by ulion** [comment]
The key reason is, when an angular validator decide the value is invalid, it will set the modelValue to undefined, but when it become valid (caused by outside changes, e.g. other field value's change), the original validator make the field invalid was not called, that means the modelValue was not updated for such case, then finally, the validate with tv4 think the required field are missing, though it's not, its viewValue is correct, just the modelValue was not refreshed by re-apply those validators.

Problem is, how to resolve this?

**Comment by ulion** [comment]
It seems, I can only rely on use form.ngModelOption to allowInvalid to always get 2 date values even if any of them fails on any validator, then the judge invalid can be more accurate.

**Comment by punknroll** [comment]
I have the same problem. How can I resolve this?

**Comment by punknroll** [comment]
The fix ulion provided works for me. Will there be a pull request?

**Comment by Anthropic** [comment]
#642 is reported as fixing this issue
