### ISSUE TITLE
custom styling of validation messages is not available

### ISSUE THREAD

**Issue by prabhatsharma** [json-schema-form/angular-schema-form#443]
Validation mesages were appearing a bit crazily in our application due to various styles and I realized that help-block class is hard coded for styling of validation messages. We need support for custom styling of validation messages.

I have forked the repository and provided a fix for this. Will be raising a pull request.

**Comment by prabhatsharma** [comment]
Have added following pull request
https://github.com/Textalk/angular-schema-form/pull/444

**Comment by nicklasb** [comment]
Closing, the discussion may continue at the PR.
