### ISSUE TITLE
Template access to schema form scope

### ISSUE THREAD

**Issue by Anthropic** [json-schema-form/angular-schema-form#446]
I have the below where I have a button that triggers an action and I want to display the result in the form beneath the button. However, I **do not** want the result to pollute my model as it is quite large and at the moment I have no need to strip anything out prior to sending to the server.

The workaround I found was as follows using **$parent.$root.$$childHead.vlanCheckResponse** which makes me feel like I have totally missed something obvious as that can't be the 'easiest' way to do this.

```javascript
      { "type": "button", "title": "Check VLAN", "onClick": "checkVlan(form)" },
      {
        "key": "product.logicalResources.outervlan",
        "type": "template",
        "condition":"$parent.$root.$$childHead.vlanCheckResponse",
        "template": "<div ng-bind-html=\"$parent.$root.$$childHead.vlanCheckResponse\"></div>"
      },
```

So if it is the easiest way, can I suggest that we add a method for accessing the form scope within a template and condition? I tried the **eval** options but they would only output what the original value was.

**Comment by nicklasb** [comment]
Isn't the cleaner way to move the button into the template?

**Comment by Anthropic** [comment]
Well I want the whole response block to not appear if there is no result and I was hoping not to pull everything into the template as I didn't really like the idea of using a template in the first place. It could work of course, I was just more interested in knowing an easier path to top level data though I guess. Thanks Nicklas.

**Comment by nicklasb** [comment]
Ok. Templates becomes a little more workable and nicer if you choose to use a templateUrl instead or having the raw code in the form. 

I would rather not like to have my user code traverse around the ASF internal scopes like that even if I had access to the form(which is *possible* to reach). It turns ugly and unstable quickly. You would have to trust that ASF doesn't move those scopes around.

**Comment by Anthropic** [comment]
Yeah I don't want to have to do it, I would like to see one of the provided eval functions return the object referenced so that you can then watch the object for changes ideally.

**Comment by nicklasb** [comment]
Then I don't think I understand completely. What eval function is you are referring to? The condition? The condition is not needed if you do it in the template. 
And checkVlan(form) doesn't have to set anything, you can have another step that actually sets the model value when you click a button or something.

If you could, make a plunkr of it.

If you want to minimize what you put in the template, perhaps a directive would be more in line?

**Comment by Anthropic** [comment]
I'll try a different approach to the question...
The core of what I am after is that I want to have text defined in my root scope controller displayed on the form, and bound, so that if the value changes the text in the form changes.

1. It isn't part of the form it is just the content so doesn't have a key.
2. I don't want to alter the schema or form to add this in as I don't want the form to reload.
3. I'm using a template because I couldn't get help text to display a variable like I had expected it to.
4. The **evalInScope** function can return me my variable fine, but I can't seem to bind it.

**Comment by nicklasb** [comment]
Ok, maybe I am a bit daft...that seems like a different thing, but perhaps I didn't get the first example at all. I thought that "product.logicalResources.outervlan" was part of the model.

1. So if you with content do not mean the model, the text is just in a  general variable in the root controller scope? 
2. I don't think you can make any significant changes to the resulting UI of ASF without changing the form, as you did in your first post. Unless of course you manually manipulate the DOM from the outside in some way. If you add your stuff to the form from the beginning, nothing will reload?
3. Ok.
4. A watch expression doesn't trigger?

In general, and no offence, but it is my experience that one should not veer to far away from how UI - components usually work, it adds so much complexity to the solution. I would consider if putting all this time into this specific functionality is really required for your solution. An ASF update might break it completely.

**Comment by Anthropic** [comment]
That's why I want it updated in ASF to include access to the top level scope so that I don't need to risk anything breaking. The best outcome for me would be an ability to bracket bind to a top level scope value from within a help text. But as in number 4 above, I can't bind to my value with a watch properly. I could try creating an object at the top level and then bind to a variable on that object, that may work for me, but it would still feel hacky.

**Comment by nicklasb** [comment]
Any luck on any approach here? As more people use ASF for more and more advanced application, the use case where editing one field will affect the content of another(like [here](https://github.com/Textalk/angular-schema-form/issues/504)) is becoming more frequently asked for. 

Now this is very common in desktop apps, but currently, the onChange event doesn't supply any such route. Perhaps something should be added, I suppose this would help you as well, I suppore that is would become available the  add-ons implicitly.

**Comment by Anthropic** [comment]
No other options, really need something to avoid my hack still.

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently. ;-)
