### ISSUE TITLE
Required not working in parent properties

### ISSUE THREAD

**Issue by franciscopuyo** [json-schema-form/angular-schema-form#450]
Hi, I created a form using the following schema (not exactly this but I created this to exemplify the error)
```
{
    "type": "object",
    "properties": {
        "name": {
        "type":"string",
        "minLength": 3
        },
        "id": {
        "type":"object",
        "properties":{
            "dni": {
                "type":"number"
            },
            "country": {
                "type":"string",
                "minLength": 5
            }
        },
        "required": ["dni","country"]
        },
    "required":["name"]
    }
}
```
The fact is that the form doesn't validate the name field. It seems that the module doesn't "understand" the last required attribute. In the child attribute id, It does validate both fields (country and dni). 

Anything you need tell me,

Francisco

**Comment by stramel** [comment]
This seems related to #251 and #270. Are you just saying that the name of the parent doesn't get the feedback coloring applied to it?

**Comment by franciscopuyo** [comment]
I've read them and it seems it's the same problem. It's not just about the color, the fact is that "name" field is not taken as a required one, so it's not well validated. I can modify the color or signals but only if it's take as required.

**Comment by davidlgj** [comment]
This is a bit strange... 

First off, I think the schema is wrong, `required: ["name"]` should not be inside the `properties` object, but outside it like this: 
```js
{
  "type": "object",
  "properties": {
      "name": {
          "type":"string",
          "minLength": 3
      },
      "id": {
          "type":"object",
          "properties":{
              "dni": {
                   "type":"number"
               },
               "country": {
                   "type":"string",
                   "minLength": 5
              }
          },
         "required": ["dni","country"]
      }
  }
  "required":["name"]
}
```

But it still fails for me, when testing with Angular 1.3... or at least I think it does. Angular 1.4 works though. Test it here (with schema form 0.8.3): http://schemaform.io/examples/bootstrap-example.html#/a002a02a3dc8cc27b8bc

I'm going to investigate a bit more

**Comment by davidlgj** [comment]
Ok, so above test gist, required fails on Angular 1.3.0, which up till today was the version used on the example page. But it works in 1.2.28, 1.3.16 and 1.4.1! 

 I'm not sure whats going on but mu guess it's related to a bug in angular that they fixed. What version of angular are you using @franciscopuyo?

**Comment by franciscopuyo** [comment]
sorry, I modify the example to make it clearer and change the order of the required tag. The same happens to my other schema. Sorry for make you loose your time

**Comment by nicklasb** [comment]
Closing.

**Comment by robinspollak** [comment]
Hi!
Just ran into this same issue by running it with 1.3.0 which was brought in automatically for some reason when I did `npm install angular-schema-form`. Would it be reasonable to update the package.json to reflect that a version newer than 1.3.0 should be used? (despite the fact that it works on 1.2.28)
Cheers
