### ISSUE TITLE
reference other scope model value (bound)

### ISSUE THREAD

**Issue by Gompje** [json-schema-form/angular-schema-form#451]
I've looked through the document but I don't think it is possible (yet) to add a "readonly" or just plain text field that is bound (ng-model or {{}}) to a field outside the scope?

example:
in the "condition" field I can state something like "ctrl.ux.show == 4"; which works perfectly; the expression gets evaluated on the right scope so "ctrl.ux.show" has a value.
but now I want to show the actual value of "ctrl.ux.show" in another field, in this form (bound so it updates).

is this possible atm?

**Comment by nicklasb** [comment]
Not without an onChange, i don't thing.

**Comment by Anthropic** [comment]
@Gompje no, at the moment you're best off having the field twice with alternate versions based on the condition, this obviously doesn't work for many scenarios at which point onChange is the only remaining option for now, but this is on the radar and something we are looking at.

Please re-open if you do not feel the question has been answered sufficiently.
