### ISSUE TITLE
custom-validators

### ISSUE THREAD

**Issue by chachou29** [json-schema-form/angular-schema-form#452]
hello,
Custom validators look great, check schemaform.io/examples/custom-validators.html.
But, the form definition in this example is javascript, not JSON.
The problem is that I store forms in database serialized as string ...
Any idea ?
Thank you !
Philippe

**Comment by nicklasb** [comment]
You can just encode the JSON into a javascript object. Actually I think this is done automatically by $http.get...

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
