### ISSUE TITLE
JSON object type with dynamic properties

### ISSUE THREAD

**Issue by awhitty** [json-schema-form/angular-schema-form#455]
My current project involves a module to dynamically build simple json schemas for user-created forms.

The current implementation involves a form built off a scary schema that looks like this:
```js
{
  type: 'object',
  properties: {
    properties: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: {
            title: 'Title',
            type: 'string'
          },
          type: {
            title: 'Type',
            type: 'string',
            enum: ['string', 'number', 'integer', 'boolean']
          }
        }
      }
    }
  }
}
```

And this gets me so far, but I'm hitting a little wall since json schema's spec expects a schema's `properties` property to be an object of property definitions, not an array. However, I need to use the array type to convince ASF to enable adding/removing properties.

My workaround involves converting the properties array to and from an object on the fly, but I'm wondering if there are plans to support using an array-like decorator to edit objects? Otherwise, do you have any suggestions on how to go about this a bit better?

**Comment by nicklasb** [comment]
I am not sure what you mean here, there is a schema and a form, the form is an array, schema object properties aren't:http://schemaform.io/examples/bootstrap-example.html

**Comment by Anthropic** [comment]
@awhitty from a quick read I think you are perhaps referring to anyOf, oneOf capability in json-schema? This is on the planning list for ASF but not sure on exact timelines. Is this still an issue for you anyway? If it is, please re-open if you do not feel the question has been answered sufficiently or you have more info to add.
