### ISSUE TITLE
0.8.3 breaks custom datepicker

### ISSUE THREAD

**Issue by deyceg** [json-schema-form/angular-schema-form#456]
Placeholder for me to update code example

TL;DR Day/Month/Year picker (3 drop downs) when all selected writes datestring in DD-MM-YYYY format to ngModelController for $$value$$.

```ngModel.$setViewValue('01-01-1970')``` no longer triggers $viewValue -> $modelValue

**Comment by nicklasb** [comment]
Can you close this when you are done?

**Comment by Anthropic** [comment]
Please re-open if you can provide more information (gist/plunker) to help us to help you :)
