### ISSUE TITLE
Is it possible to instruct a field to be placed into a new row?

### ISSUE THREAD

**Issue by ricklxm** [json-schema-form/angular-schema-form#461]
Thanks for the great work.
I'm using asf in my project. I'm wondering if it's possible to instruct a field to be placed into a new row?
let's say I have the schema as below, and I want to place the 'realEstateList' section in a new row.
The desirable UI may look like:
```javascript
<div class='row'>
    <div class='col-md-3'>name field</div>
   <div class='col-md-3'>email field</div>
   <div class='col-md-3'>sex field</div>
</div>
<div class='row'>
    <div class='col-md-3'>address field</div>
   <div class='col-md-3'>boughtPrice field</div>
   <div class='col-md-3'>boughtDate field</div>
</div>
```
schemas:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "customer detail",
  "type": "object",
  "properties": {
    "name":
    {
      "title": "Name",
      "type": "string",
      "x-schema-form": {
        "htmlClass": "col-md-3"
      }
    },
    "email":
    {
      "title": "Email Address",
      "type": "string",
      "x-schema-form": {
        "htmlClass": "col-md-3"
      }
    },
    "sex":
    {
      "title": "Sex",
      "type": "string",
      "enum": ["male", "female"],
      "x-schema-form": {
        "titleMap": [
          { "value": "male", "name": "Male" },
          { "value": "female", "name": "Female" }
        ],
        "htmlClass": "col-md-3"
      }
    },
	"realEstateList": {
		"type": "array",
		"items":{
			"type": "object",
			"properties": {
				"address":{
					"type": "string",
					  "x-schema-form": {
						"htmlClass": "col-md-3"
					  }
				},
				"boughtPrice": {
					"type": "integer",
					  "x-schema-form": {
						"htmlClass": "col-md-3"
					  }
				},
				"boughtDate": {
					"type": "string",
					  "x-schema-form": {
						"htmlClass": "col-md-3"
					  }
				}
			}
		}
	}
  }
}
```

Sorry, for some reason, I cannot upload screenshot successfully. Please copy the schema to http://schemaform.io/examples/bootstrap-example.html#/4fa8967ae5596fe8b0c0 to see the result.

Because my real schemas is very large, and in mutiple json files (using $ref), and some part are reuseable. So I don't want to add a placholder field to eat the rest columns of the first row.

Any suggestion is appreciated!

Thanks in advance!

**Comment by Dervisevic** [comment]
Someone may have solved it nicely but i can't think of a nice way now, what you can do is use the form definition and the template type to wrap your fields, example: http://schemaform.io/examples/bootstrap-example.html#/4565d1a66ea21bf90f76

**Comment by ricklxm** [comment]
Dervisevic, thanks for your quick reply! Your solution seems enough for me for now.

**Comment by ricklxm** [comment]
I'd like to keep it open to wait a more graceful solution, if there is...

**Comment by nicklasb** [comment]
I think that we should close this now?
Please re-open if you do not feel the question has been answered sufficiently.
