### ISSUE TITLE
Is it possible to set default Standard Options?

### ISSUE THREAD

**Issue by TrevorPage** [json-schema-form/angular-schema-form#467]
I intend to make use of `labelHtmlClass` and `fieldHtmlClass` to apply the classes `col-sm-2` and `col-sm-10` to labels and fields respectively, so that once the `form` has class `form-horizontal`, I have a horizontal form layout. 

Is there any way I can set these as defaults either on a form basis or global basis so that I can avoid having to define them separately for each field in the `$scope.form`?

**Comment by nicklasb** [comment]
I can't see any really nice way of doing that. But on the other hand, defaults on those could be useful either way. ASF would have to rewrite the form. In schema-form.js, stdFormObj already sets the title to schema.title if not set. I guess it could set labelHtmlClass and fieldHtmlClass as well, and defaultLabelHtmlClass and defaultFieldHtmlClass attribute could be added to the directive.

**Comment by davidlgj** [comment]
@TrevorPage yes there is, you can set the global option `formDefaults`, its an object that is used as the default for all form fields.  See the docs: https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#global-options

**Comment by nicklasb** [comment]
Cool!

**Comment by TrevorPage** [comment]
@davidlgj thank you. Is it possible to set this programmatically however, in a single config block?

**Comment by TrevorPage** [comment]
The reason I ask this is because I have many forms, and for almost every single field in those forms I would like to achieve the following:

- Set default `labelHtmlClass` and `fieldHtmlClass` as mentioned above, and
- Set the `validationMessage` to be the result of a function that supplies the word "required" in the appropriate language. 

I could use `sf-options`, but presumably I would have to copy and paste this into all forms. Furthermore, I'm not sure if it's possible to supply a function for the `validationMessage` through this attribute. 

At the moment, I have the following in every single form property:

                {   
                    "key" : someKey, 
                    ...
                    labelHtmlClass: "col-sm-3",
                    fieldHtmlClass: "col-sm-9",
                    validationMessage: myTranslateFunction('REQUIRED')  
                },

It would be nice to be able to define these as default in one place for all forms. If this is not possible at the moment, then no worries at all; it would just make things cleaner if I could! :)

**Comment by MattiJarvinen-BA** [comment]
Actually there's a stupid little problem with the Bootstrap horizontal forms. Input (and everything related straight into that) should be contained in a div with the class. So fieldHtmlClass is not quite enough.

```
<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
```

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
