### ISSUE TITLE
Problem with array objects

### ISSUE THREAD

**Issue by ynarid1** [json-schema-form/angular-schema-form#476]
Hello!
First of all, thank you for this awesome module!

I was testing some custom json schema and form templates, when i encountered that the array type in form wasn't displaying well. In my example, it was only showing the title and the "add" button, but not the properties of the object array, so it was always empty and whenever i click the add button i get the following error in the console:

"Error: list is undefined
.link/once</scope.appendToArray@/bower_components/angular-schema-form/dist/schema-form.js:1587:17
Parser.prototype.functionCall/<@/bower_components/angular/angular.js:10847:15
ngEventHandler/</callback@/bower_components/angular/angular.js:19136:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@/bower_components/angular/angular.js:12702:16
....

So i tried to test the "Array" example from http://schemaform.io/examples/bootstrap-example.html but i was surprised to get exactly the same behaviour and error (notice that i don't use the drag and drop plugin as i don't need it, i just need the basic functionality of the array type with the add button).

I'm using version 0.8.3 of angular-schema-form and version 1.2.26 of angularjs. I'm also using, among other dependencies, version 0.11.2 of angular-bootstrap. Any help will be greatly appreciated!

**Comment by davidlgj** [comment]
Hi @ynarid1, yes it was a problem with Angular 1.2, I found the bug and it's now fixed in the development branch. Thank you for reporting it!

**Comment by ynarid1** [comment]
Hi @davidlgj , thank you for your answer!
Using the development branch works fine, although now i'm facing a different problem. When loading the schema-form for a custom schema, i get the following error:

"Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations:

I put a breakpoint inside the following watch: 

//Since we are dependant on up to three
        //attributes we'll do a common watch
        scope.$watch(function()

And confirm that it is getting called a lot of times, while rendering the form. My form have nested fieldsets and other elements, but i really think that it isn't so complex overall. Do you know how i can prevent this from happening?

**Comment by davidlgj** [comment]
hi @ynarid1, it should not be happening... could you try the schema and the form on the demo page? Does it work there?

**Comment by ynarid1** [comment]
Yes, i just tried and in the demo page works fine! 
Perhaps this is related with the angular version i'm using...

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
