### ISSUE TITLE
My form is always showing green text and checkmarks.

### ISSUE THREAD

**Issue by Mooser** [json-schema-form/angular-schema-form#477]
I tried setting "disableSuccessState" on all the properties in the schema, but it has no effect.

It is applying the "success" bootstrap classes and causing my input title's to be green and a checkmark displayed inline.  I'd like it to not display this stuff, especially since it is a readonly form.

**Comment by Mooser** [comment]
$scope.schema = {
    type: "object",
    properties: {
      name: {
        type: "string",
        title: 'Name',
        minLength: 3,
        readonly: true
      },
      onlineDate: {
        type: 'string',
        readonly: true,
        title: 'Online Date'
      },
      totalReadings: {
        type: 'number',
        readonly: true,
        title: 'Total Readings'
      },
      sampleRate: {
        type: 'number',
        readonly: true,
        title: 'Sample Period (in seconds)'
      },
      offset: {
        type: 'number',
        readonly: true,
        title: 'Timezone Offset'
      },
      url: {
        type: 'string',
        readonly: true,
        title: 'URL'
      },
      username: {
        type: 'string',
        readonly: true,
        title: 'Username'
      },
      uuid: {
        type: 'string',
        readonly: true,
        title: 'UUID'
      }
    }
  };

  $scope.form = [
    {
      "type": "section",
      "htmlClass": "row",
      "items": [
        {
          "type": "section",
          "htmlClass": "col-sm-6",
          "items": [
            "name","onlineDate","totalReadings", "sampleRate"
          ]
        },
        {
          "type": "section",
          "htmlClass": "col-sm-6",
          "items": [
            "uuid", "offset", "url", "username"
          ]
        }
      ]
    }
  ];

**HTML**
```
<form sf-schema="schema" sf-form="form" sf-model="selectedMeter"></form>
```

**Comment by TrevorPage** [comment]
I know it's a hack around the problem, but literally just now I added this to my custom Less to remove it:

.has-success .control-label {
    color: #333333;
}

**Comment by Mooser** [comment]
Fair enough Trevor.  Do you have a hack to remove the green checkmark as well?  :+1:

**Comment by Anthropic** [comment]
@Mooser can you provide a demo data set and make a plunker?

You could start with this one: http://plnkr.co/edit/KU5QOC and fork it to a new plunker and edit the app.js files for schema, form and model.

**Comment by Anthropic** [comment]
Please re-open if you can provide more information (gist/plunker) to help us to help you :)
