### ISSUE TITLE
Custom CSS directive not being executed

### ISSUE THREAD

**Issue by jbsaff** [json-schema-form/angular-schema-form#479]
Possibly similar to #453, I have a custom directive that I want to apply via the htmlClass property for form. I can verify that my directive alone does what I want, but when trying to incorporate it with ASF it appears that the linker is never called. 

https://gist.github.com/jbsaff/0ed0678ae3fe42244293

Is this just overboard, trying to have the ASF apply a css class and then expecting angular to pick up on that to run the directive?

Thanks.

**Comment by Anthropic** [comment]
@jbsaff you could maybe have this work with the new builder, have you tried? It compilsles the full form earlier so it may be done early enough in the cycle. I haven't tried it though.

As this is old I will close it, but please feel free to re-open if you want to discuss further!
