### ISSUE TITLE
How bind a function/ajax call to the titlemap of the Select?

### ISSUE THREAD

**Issue by techrich** [json-schema-form/angular-schema-form#483]

**Comment by nicklasb** [comment]
Add a watcher on the titleMap? I am sorry, but you need to elaborate further to get a response.

**Comment by techrich** [comment]
While the controls are rendered onto the view I would like to bind data for a dropdown from a REST/Service/AJAX call. 'TitleMap' allows me only to set them only at the schema level as a static list. I want this binding more configurable and rendered derived at runtime.

**Comment by nicklasb** [comment]
There are several add-ons for that, feel free to try the one I am maintaining, [ASFDS](https://github.com/OptimalBPM/angular-schema-form-dynamic-select)?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
