### ISSUE TITLE
Validate larger than another form input?

### ISSUE THREAD

**Issue by MattiJarvinen-BA** [json-schema-form/angular-schema-form#489]
I have two selects with year values (startYear, endYear) I can easily add a validator for one two check if it's larger than the other. 

Problem is that validators for a model are only run when that model changes. So if I select startYear to 2015 and endYear to 2014 I get the validationMessage but if I change startYear to 2010 validationMessage doesn't go away.

Should I add onChange for both of these fields or what would be the preferred way of doing this? Extending schema form seems to be somewhat overkill for this simple use case.

**Comment by nicklasb** [comment]
That sounds strange. IMHO, validation should be run even if a validation has previously failed, otherwise it would be really difficult to use the interface. 
You say "select", is it the date picker you are using?

**Comment by MattiJarvinen-BA** [comment]
Just two separate HTML selects. Values are numeric 1970 - 2030

**Comment by davidlgj** [comment]
@MattiJarvinen-BA yes doing something "onChange" is probably the easiest route, although a bit more hackish. Maybe you can clear the old validation message with an event https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#inject-errors-into-form-aka-backend-validation

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
