### ISSUE TITLE
Weird behaviour removing array elements

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#490]
I have a form with a single array in it, I am looking for the same behaviour as in the 'dislikes' example on the kitchen sink demo page. I am seeing odd behaviour when removing elements. Instead of the element just being removed, it is being removed, then a null element is being added to the end of the array.

Here is my form definition:
```
[{
    "key": "categories",
    "title": "Global category headings",
    "type": "array",
    "required": true,
    "ngModelOptions": {
        "debounce": 2000
    }
}]
```
and my schema definition:
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://site.test.com/api/preferences/categories",
    "type": "object",
    "properties": {
        "categories": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "title": "Category",
                "type": "string"
            }
        }
    }
}
```
Have you seen this behaviour before?

**Comment by AndrewIsh** [comment]
I should add that i have a watcher on the model and logging the model when it changes, this is what I'm seeing when I remove an element (the watcher gets called twice for some reason):
Call 1:
Old: ["One", "Two", "Three"]
New: ["One", "Two"]

Call 2:
Old: ["One", "Two"]
New: ["One", "Two", undefined]

So it seems to be whatever is making the second change to the model that's causing the problem. No idea why there is a second change to the model though, as far as I can see from the source, all you're doing is a splice. Is there anything anywhere else which might be appending a null value?

**Comment by nicklasb** [comment]
I put you thing into the example page, and I could not recreate it:
http://schemaform.io/examples/bootstrap-example.html#/da0a1281b7beedf22c0d

At what point is the last item added?

**Comment by AndrewIsh** [comment]
I've not been able to replicate it on the example page either, which makes it even stranger. I'm not sure what your question means, as far as I can see something is making two changes to the model, as illustrated in the above example, the second change is adding the last item.

**Comment by nicklasb** [comment]
My question was perhaps not very well phrased, I was wondering if you could see more precisely when the undefined is added, using the debugger between call 1 and 2. But that is perhaps not possible,

I would recommend you to create plunkr with some setup that replicates the error. It is good to have one for troubleshooting stuff like this anyway.

**Comment by Anthropic** [comment]
@AndrewIsh did you manage to solve this?

Please re-open if you do not feel the question has been answered sufficiently.
