### ISSUE TITLE
Is there any better way to configure multiple form definition for a single schema defintion

### ISSUE THREAD

**Issue by balangovindaraj** [json-schema-form/angular-schema-form#494]
Hi ,

I have a requirement like, form should be generated based on schema definition and that form will be having different styling and fields based on the page where it is displaying.

My Schema 

   		{
		    "type": "object",
		    "title": "Product Details",
		    "properties": {
			"productName": {
			    "title": "Product Name",
			    "type": "string",
			    "validationMessage": "Please enter the product name"
			},
			"productDescription": {
			    "title": "Product Description",
			    "type": "string",
			    "description": "Description of the Product",
			    "validationMessage": "Please enter the product description "
			},
			"productReview": {
			    "title": "Product Review",
			    "type": "string",
			    "maxLength": 20,
			    "validationMessage": "Review is empty !!!"
			}
		    },
		    "required": [
			"productName",
			"productDescription",
			"productReview"
		    ]
		}

In the Product details page, I would like to display the all the three fields, So my form definition goes like this 

      [
	  "productName",
	  "productDescription",
	  {
	    "key": "productReview",
	    "type": "textarea",
	    "placeholder": "Please review this product"
	  },
	  {
	    "type": "submit",
	    "style": "btn-info",
	    "title": "OK"
	  }
	]

In some other page I need to have only reviews, So I have separate form definition for this 
              
          [
		  {
		    "key": "productReview",
		    "type": "textarea",
		    "placeholder": "Please review this product"
		  },
		  {
		    "type": "submit",
		    "style": "btn-info",
		    "title": "OK"
		  }
		]

Do I need to have the different(10 to 15 my application needs) form definition as my application needs it. Currently I am putting this form definition and schema definition to JSON file and getting it. 

Is there any better option does schema form has to achieve this

**Comment by nicklasb** [comment]
If they doesn't differ too much, you can use a `condition` to hide or show a field based on an angular expression:
https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#standard-options

But if they differ considerably, maintaining all the conditions might become more complex than maintaining the different forms. On the other hand, you don't have to productName in fifteen different places. You can also "inherit" from a base json, and add parts when needed. Or possibly combine these approaches. 

(I am also thinking that general advise on stuff like this could be in the documentation somewhere.)

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
