### ISSUE TITLE
Exception on array types

### ISSUE THREAD

**Issue by vicary** [json-schema-form/angular-schema-form#497]
I have initiated the form scope with an empty object `{}`, one of it's properties are of array type with simple string as items.

When I click on the "Add" button it returns the follow error,

```
TypeError: Cannot read property 'length' of undefined
    at n.angular.module.directive.link.scope.$watch.scope.appendToArray (/assets/scripts/schema-form.js:1587:27)
```

Inspecting `list` and `scope.modelArray` shows and empty array during form initialize, but `list.length` loses reference and turns into `undefined` in line 1587 `appendToArray()`.

**Comment by trajano** [comment]
The workaround is to have an empty array object in your "default" structure.  For example.
```
{
   "items":[]
}
```

**Comment by trajano** [comment]
Without the default array, angular-schema-form will not be able to find it and thus give an `undefined` when accessing the list variable.

However, my attempts of setting it to `[]` makes it behave incorrectly, it appears to swap the array with an object whose indices are integers.  Not exactly sure which part of the code does that but I did see something about it earlier.

**Comment by vicary** [comment]
I have been heading into this for twice in a week. The real cause of this is the `sf-model` pointing to an empty reference, or missing altogether. Looks like ASF fail to initialize the array without it, maybe add the attribute as required?

**Comment by trajano** [comment]
I was thinking something along the lines of `scope.model.$watch` for `{}` then initialize it to have the empty arrays.  At least that would work for the top level ones, but we need it to work on the arrays within arrays.

**Comment by vicary** [comment]
Can it be done in `render()` (line 2157) instead?

**Comment by vicary** [comment]
I have a general purpose form that works on multiple models, all default values are not applied when I assign an empty object `{}` into `sf-model`. I have to make my own creation method for each model at this moment.

**Comment by nicklasb** [comment]
I am gettings this too now, it seems like a pretty serious problem.

**Comment by nicklasb** [comment]
Obviously this is not a solution for anyone, but I just realised that [angular-scheme-form-dynamic-select add-on](https://github.com/OptimalBPM/angular-schema-form-dynamic-select) is not affected by this. I use that everywhere (I am the maintainer), so was basically a mistake that made me encounter this problem.

So if you use that, you are out of the woods on this one. You also get a ton of other features, but I have seen no negative performance impact of the component so far.

**Comment by vicary** [comment]
The select-external plugin I am currently using also shims the value in some cases, but that's best taken care of in the core.

**Comment by nicklasb** [comment]
That is correct, of course. I was not suggesting that it shouldn't, it certainly is a serious bug. 
That said, it feels like most new users almost immidiately needs the kind of functionality the select add-ons provide anyway, so I'd mention it. (i would also want to call them plugins instead)

**Comment by DDuTCH** [comment]
+1

**Comment by Anthropic** [comment]
@vicary this should work in the latest alphas.

**Comment by vicary** [comment]
@Anthropic Thank you!
