### ISSUE TITLE
tabs and clearing form after submit

### ISSUE THREAD

**Issue by noahwallach** [json-schema-form/angular-schema-form#498]
Hi there,

I am not having luck clearing out the values of the form and returning them to an empty or default value.

Here is my code.  This routine clears all the values in the model except the array.

                var fields = ["value1", "value2", "value3"];
                for (index = 0; index < fields.length; ++index) {
                    var current = fields[index]
                    $scope.model[current] = '';
                };

If I clear out the array with the following line - but the result is the inability to add fields corresponding to the array.

$scope.model.array = [] 

Any ideas about the best way to reset the model.

**Comment by davidlgj** [comment]
Hi there @noahwallach, can you give me an example schema and form definition to try? To just clear it should be as simple as `$scope.model = {}`.

**Comment by noahwallach** [comment]
Doing $scope.model = {} blanks out my arrays in the forms.  This is not the best method.

**Comment by admiralobvious** [comment]
You also get the following error in the console if you do it like @davidlgj suggested:

```
TypeError: Cannot read property 'length' of undefined
    at schema-form.js:1670
    at Object.$watchCollectionAction [as fn] (angular.js:15550)
    at Scope.$get.Scope.$digest (angular.js:15683)
    at Scope.$get.Scope.$apply (angular.js:15951)
    at HTMLFormElement.<anonymous> (angular.js:23303)
    at HTMLFormElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLFormElement.jQuery.event.add.elemData.handle (jquery.js:4121)
```
schema-form.js:1670:
```
while (arr.length > 0) {
  arr.pop();
}
```

**Comment by davidlgj** [comment]
If you do a `schemaFormRedraw` after clearing the model it should work ASF will set all defaults again. See https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#updating-form

Something like this:
```js
scope.model = {};
scope.$broadcast('schemaFormRedraw');
```

**Comment by admiralobvious** [comment]
@davidlgj I just tried `$scope.$broadcast('schemaFormRedraw')` and it does not set my defaults again.

**Comment by chiewmey** [comment]
@admiralobvious How about $rootScope.$broadcast('schemaFormRedraw'); ?

**Comment by nicklasb** [comment]
It this still a problem?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
