### ISSUE TITLE
Is there anyway to add directives to Form Types?

### ISSUE THREAD

**Issue by ngabello** [json-schema-form/angular-schema-form#500]
For example I would like to do this:
 "birthDate": {
                                "type": "string",
                                "directive":['ui-mask']
                            },

**Comment by MattiJarvinen-BA** [comment]
Yes there is https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md

**Comment by nicklasb** [comment]
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by d1b1** [comment]
Reopen please. I have reviewed the examples and am not finding any examples for how to specifically add in directives that add on features like input masks. A little more in the docs would be great.

**Comment by nicklasb** [comment]
Actually, I'd say that @MattiJarvinen-BA is right. Just adding a directive like that is not possible AFAIK without adding that as a feature to ASF, you will need to create an add on that creates an input that uses ui-mask.

There is a guide here: https://github.com/json-schema-form/angular-schema-form-add-ons

I would think that is a valid case for an add-on.

**Comment by Anthropic** [comment]
@d1b1 you can also use the builder functions to add directives to the templates as they are being processed.

**Comment by nicklasb** [comment]
@Anthropic Did not know that, I am not sure I get how that would happen from the documentation?

**Comment by Anthropic** [comment]
@d1b1 @nicklasb I've updated the documentation further, please let me know if there is anything that you require further information on https://github.com/json-schema-form/angular-schema-form/blob/development/docs/extending.md
