### ISSUE TITLE
Conditional constraints

### ISSUE THREAD

**Issue by rsantos200771** [json-schema-form/angular-schema-form#501]
Hi,

I want to perform conditional constraints in a schema and for that I need to have access to the all schema and model.
What's the best way to access this?

Thanks

**Comment by nicklasb** [comment]
The schema and model you provide yourself to ASF. Not sure what you mean here.

**Comment by Anthropic** [comment]
There are some options like evalExpr(), they seem to have been removed from the documentation so I am checking on why, but for now you can try them and see if they help.
https://github.com/json-schema-form/angular-schema-form/blob/4c25e86a96e8ed476c12c11e44bd8db36eeefe27/docs/extending.md

Please re-open if you do not feel the question has been answered sufficiently.
