### ISSUE TITLE
Multiple field inline with a single label

### ISSUE THREAD

**Issue by leader80** [json-schema-form/angular-schema-form#502]
Hi All,

is there a way or did somebody manage to build multiple inline fields with a single label?

something in that form:
![label](https://cloud.githubusercontent.com/assets/73665/9217707/3d742a22-40cb-11e5-860d-f04b4db91f09.jpg)

Configuration:
 {
      "type": "address-inline",
      "labelHtmlClass": "col-xs-12 col-md-3",

      "items":[
        {
          "type": "string",
          "key": "zip",
          "title":"PLZ_PLACE",
          "placeholder": "ZIP place",
          "feedback": false,
          "fieldDivClass": "col-xs-12 col-md-2",
          "pattern": "^\\d{4}$",
          "validationMessage": "Zip need 4 number",
          "required": true
        },
        {
          "type": "string",
          "key": "city",
          "title": "ORT_PLACE",
          "placeholder": "Ort place",
          "feedback": false,
          "pattern": "^\\s*$",
          "fieldDivClass": "col-xs-12 col-md-7",
          "required": true
        }
      ]
    },
Thanks

**Comment by TrevorPage** [comment]
As it happens, I spent much of yesterday working on exactly this. I managed to succeed using standard Bootstrap and ASF library without any custom CSS.

First, the inline row of fields (with single label) had to be split into its own dedicated element and form definition. (Of course if this is part of a larger form, as it is in my case, then you can place sibling elements above or below to contain the rest of the form objects. They can all share the same model if you want.)

The HTML. (Note the `.row` class.)

```
<div sf-schema="schema" sf-form="form_inlineexample" sf-model="model" class="row"></div>
```

The `form` definition (I've started to use some keys and labels etc. from your example):

```

        $scope.form_inlineexample = [
            {
                "key": "zip", 
                "title": "Zip",
                labelHtmlClass: "col-sm-3",
                fieldHtmlClass: "col-sm-2",
                htmlClass: "form-horizontal"
            },
            {
                "key": "city", 
                notitle: true,
                "fieldAddonLeft": "ORT_PLACE",
                htmlClass: "col-sm-3"
            }             
        ];  
  
```

Note: I don't understand what your `fieldDivClass` is. Is it something custom? It sounds like it's equivalent to the `htmlClass` field.

The bottom row here is the kind of thing achieved. (The rows above are created using separate form definitions and form element.)

![image](https://cloud.githubusercontent.com/assets/1771636/9220259/12cd791e-40d9-11e5-914a-f1b568f7588b.png)

**Comment by TrevorPage** [comment]
(Just another comment to make you aware I've made several edits above, in case you get it by email.)

**Comment by leader80** [comment]
Hi Trevor,
thank you so much for your reply, I was working on a custom directive that's why the custom parameter.
I'm going to reproduce your solution, it's much more maintainable than mine.

**Comment by TrevorPage** [comment]
Really pleased it has helped. I must admit that I came very close to using a custom template, too.

**Comment by nicklasb** [comment]
I am glad you didn't. :-)

**Comment by shikshik** [comment]
I just made it by adding a fieldset (or section) with items, each fieldset got "htmlClass: 'row'" and each item object got "htmlClass: 'col-md-6'" (or any other grid size you wish to use).

That's it. works (not perfect but close enough).
I still need a customized decorator and template to build it properly in later stage. seems like it's the right (and hard) way.

Cheers :dancer:

**Comment by sgarbesi** [comment]
A simple fix to allow of this would be if the field elements were wrapped in divs where a class could be set.

The main issue with this is that the label and field elements are living within the same container, which is not Bootstrap friendly.

The `form-control` class override the width attribute, so you cannot use the `col-..-..` classes in conjunction with the field elements.

So the output now looks like this:

```html
<div class="form form-horizontal">
    <label class="col-xs-4">abc123</label>
    <input class="col-xs-8 form-control" type="text" />
</div>
```

When really it needs to be this:

```html
<div class="form form-horizontal">
    <label class="col-xs-4">abc123</label>
    <div class="col-xs-8">
        <input class="form-control" type="text" />
    </div>
</div>
```

**Comment by Anthropic** [comment]
@sgarbesi if you feel this needs a change to the boostrap decorator, now it has been separated, please log an issue on the decorator https://github.com/json-schema-form/angular-schema-form-bootstrap

Otherwise I think the original question was answered @leader80 please re-open if you think there is more required on this issue.
