### ISSUE TITLE
I18n form

### ISSUE THREAD

**Issue by a58az** [json-schema-form/angular-schema-form#503]
Helllo, can I make i18n fields for from? 
I didn't find any information in documentation

**Comment by Dervisevic** [comment]
Here is some information: #213

**Comment by a58az** [comment]
Now I want use function which will translate word, and all work perfectly except label for field is empty(in sf-form name has value). So I think I need to refresh data ($apply()) but it doesn't work.

**Comment by nicklasb** [comment]
Is this still a problem for you?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
