### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by DeividasK** [json-schema-form/angular-schema-form#516]
Hello,

I really like angular-schema-form, but I can't seem to find the best way to work with label translations.

I am using angular-translate library. Both schema and form are built in a factory. Currently, I have to use $translate.instant('title') to get my form titles translated.

There are 2 problems with that:
1. If I change the language I need to refresh the whole page for the form to update translations (values are updated appropriately where I used "translate" directive or filter);
2. If browser's back / forward buttons are used after page refresh, translations for form titles don't load appropriately (again, values with "translate" directive or filter work as expected).

What is the best way to solve this?

**My prior research**
The most useful stuff I foung on Google:
- Famous "Translation support?" issue - #213.
- Stackoverflow post detailing similar problems - [SO post](http://stackoverflow.com/questions/30076221/call-translation-service-from-a-callback-registered-in-an-app-config-section).

**Solutions that were suggested**
- Using gettext. If I understand correctly, this means switching from angular-translate entirely or adding another library on top of it.

My question:
**How would one go about in creating similar translation experience for schema-form labels as with "translate" directive / filter from angular-translate?**

**Comment by HeidemannMarkus** [comment]
+1

**Comment by jftsaraiva** [comment]
+1

**Comment by aferre** [comment]
+1

**Comment by Anthropic** [comment]
The best I can offer is #834 or the user supplied demo #865 that still needs some work, follow that issue till it is completed perhaps, I'll close this one in favour of that one.
