### ISSUE TITLE
Draggable array elements, drag handle

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#522]
It would be useful to have an optional, styleable drag handle for ui-sortable arrays. This would serve as a useful hint to users who may not know that the array is re-orderable.

**Comment by Anthropic** [comment]
@AndrewIsh can you check if https://github.com/json-schema-form/angular-schema-form-bootstrap/pull/19 solves your issue?

Please re-open if it does not :)
