### ISSUE TITLE
Question: How to use schemaFormRedraw and remain current active tab?

### ISSUE THREAD

**Issue by chiewmey** [json-schema-form/angular-schema-form#526]
I have a form with tabs and external submit button, the submit button will trigger schemaFormRedraw to reload the schema and value. Question is how can I keep the existing active tab when the page reload?

**Comment by nicklasb** [comment]
You would need to find a way to store which tab to return to.
We are considering implementing a state storage model. I suppose they could.

**Comment by Anthropic** [comment]
@chiewmey the easiest way I would suggest is to have a field in your schema/form that you can store the value in and pass that in the model. As Nickas mentioned we are looking at an additional data set option to handle this.

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by sirius2013** [comment]
@chiewmey 
I got same problem, how did you fix this issue?
Thank you
