### ISSUE TITLE
Wrong validation message on schemaForm.error broadcast

### ISSUE THREAD

**Issue by w0lph** [json-schema-form/angular-schema-form#528]
Hello,

I have created a custom type and a directive to validate the object associated with it:

```javascript
app.directive('schemaFileValidate',function() {
  return {
    restrict: 'A',
    link: function (scope, element, attrs) {
      var form = scope.form;
      var file = scope.$eval(attrs.file)
      scope.$on('schemaFormValidate', function() {
        if ((!file || !file.newName) && (form.required)) {
         scope.$broadcast('schemaForm.error.' + form.key,'tv4-302',false);
        }
        else {
         scope.$broadcast('schemaForm.error.'+form.key,'tv4-302', true);
        }
      })
    }
  }
});
```

However, the error message that appears on the custom type is "Field does not validate" instead of "Required".

Any help would be greatly appreciated. 

PS.: I am open to an alternative solution. My use case is that I need to make an object required (the object must not be empty or undefined). I have tried simply putting the field key in the required array in the schema, but it doesn't seem to work on custom types, that led me to create this custom validation.

Best Regards,
William

**Comment by davidlgj** [comment]
Hi @w0lph , would you mind sharing the template to your custom type? And example schema and form. It's hard to see whats going on here :) Where does the  "Field does not validate" come from for instance?

**Comment by Anthropic** [comment]
Please re-open if you can provide more information (gist/plunker) to help us to help you :)
