### ISSUE TITLE
Supporting allOf and 

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#532]
So, I doesn't seem like ASF supports allOf when it comes to properties, it assumes that the properties are in a top "property"-attribute:

```js
          scope.$watch(function() {
            var schema = scope.schema;
            var form = scope.initialForm || defaultForm;
            if (form && schema && schema.type && (lastDigest.form !== form || lastDigest.schema !== schema) && Object.keys(schema.properties).length > 0) {
              lastDigest.schema = schema;
              lastDigest.form = form;
              render(schema, form);
            }
          });
```

But the common approach to inheritance in JSON-schema seems to be:
```json
"allOf": 
[
    {properties: {"$ref": "def.json/properites"}},
    {properties: {"field": "string"}}
]
```

So something should perhaps pre-parse the schema properties into something more digestable for the above code? Or is there some other approach? Actually I think it is a little bit difficult to interpret the standards with regards to remote $refs.

**Comment by nicklasb** [comment]
I have currently worked around it by [having my backend resolve it](https://github.com/OptimalBPM/mbe/blob/master/mbe/schema.py#L231) the schemas into having just properties instead. I suppose that this could be done at the frontend(in ASF as TV4 doesn't seem to mind allOf) as well, obviously.

**Comment by AndreNel7** [comment]
[example workaround](https://github.com/Textalk/angular-schema-form/issues/69)

**Comment by nicklasb** [comment]
ASF will get *Of-support any of in a 1.x version.
