### ISSUE TITLE
Success page

### ISSUE THREAD

**Issue by leader80** [json-schema-form/angular-schema-form#536]
Hi everybody,

do you mind sharing with me your experience with successpages?
I'm trying to create a conditional successpage based on input (selectbox) of the customer but I'm quite stuck.
Do you have any good idea?

Thanks
G.

**Comment by Anthropic** [comment]
@leader80 do you mean like a wizard, can you provide more information on what you wish to achieve?

**Comment by Anthropic** [comment]
Please re-open if you can provide more information and still need help.
