### ISSUE TITLE
Number types do not set 'min' and 'max' atributes

### ISSUE THREAD

**Issue by otherkade** [json-schema-form/angular-schema-form#539]
When my field is generated as a type number with a minimum and maximum, the min and max correctly validate input, but the min and max attributes aren't set on the input, so the up/down arrows still let a user go above/below the boundaries.

**Comment by davidlgj** [comment]
Hi @otherkade, good idea!

All templates with an input as base use the same template. I think the number types maybe  should be moved to their own template.

**Comment by Anthropic** [comment]
Moved this to the bootstrap repo:
https://github.com/json-schema-form/angular-schema-form-bootstrap/issues/18

**Comment by Anthropic** [comment]
This has been done and added to webpack (v1.0) branch
