### ISSUE TITLE
Port from Angular to React

### ISSUE THREAD

**Issue by stevehu** [json-schema-form/angular-schema-form#551]
I've been a fan of this project and used it a lot in my own projects and even contributed several custom fields:
https://github.com/networknt/angular-schema-form-ui-ace
https://github.com/networknt/angular-schema-form-ui-select
https://github.com/networknt/angular-schema-form-marked
https://github.com/networknt/angular-schema-form-strapselect
https://github.com/networknt/angular-schema-form-file-writer
https://github.com/networknt/angular-schema-form-file-reader

Recently, I've switched from Angular to React and couldn't find anything equivalent in React world. Finally, I created a new project react-schema-form as sister project to port what we have here into React. It is in early stage and only partially working as I have to learn how angular-schema-form works internally. If any expert here wants contribute, it would be much appreciated.

https://github.com/networknt/react-schema-form

**Comment by davidlgj** [comment]
Cool!

With the new builder it should be possible to extract the parts that parses the form definition and the DOM builder, i.e. the services schema-form.js and builder.js into "vanilla" js functions that could be shared with your react port.

**Comment by stevehu** [comment]
@davidlgj that is a great idea. I've got hard time to refactor the code due to lack of understanding. Currently I am working on your 0.7.12 code base that I am familiar with. Still need time to understand your new builder and array.

**Comment by Dervisevic** [comment]
![e37ee46435a7ab7ed33b1858888545f3](https://cloud.githubusercontent.com/assets/541475/10038521/7166ced0-61c7-11e5-9d5b-fa00a8e73bc4.jpg)

**Comment by davidlgj** [comment]
@stevehu I would really recomend basing it of the new builder. The main difference being that the builder creates the entire DOM in one go and does not need anything angular at all really. Check out the blog posts on it if you haven't seen them https://medium.com/@SchemaFormIO/the-new-builder-pt-1-61fadde3c678

**Comment by stevehu** [comment]
@davidlgj I've read your three blogs and they are fun to read:) I am going back to the development branch now. Last time I checked it out, the examples were not working and I needed it to debug and compare. Hopefully, you could extract all the common functions into a library so that I can just install it as a node module. 
@Dervisevic your picture is so cool!!!

**Comment by Anthropic** [comment]
Wonder if it is worth creating a repo of schema-form for the base functionality and builder to be used as a bower library/npm module to pull in and then leveraging that in angular-schema-form and react-schema-form. It could focus on validation and building forms from schema and perhaps make server-side validation easier in future...

**Comment by stevehu** [comment]
@Anthropic Totally agree. My current implementation is just focusing on the simple fields as I had hard time to get Array sorted out. After switching from Angular to React, I feel npm is much better than bower with webpack support and it is the same way nodejs manages modules. It will be great if someone can extract all common features so that it can be shared.

**Comment by mderazon** [comment]
awesome stuff @stevehu !
btw, just as a reference, there's also this lib:

https://github.com/mozilla-services/react-jsonschema-form

**Comment by Anthropic** [comment]
@stevehu I'm going to mark this closed given our discussions continue in Gitter and you're aware of what is going on regarding the new core, by all means re-open if you prefer to keep it open, just trying to do some house keeping with the massive outstanding issue count :)
