### ISSUE TITLE
Defining callbacks using a string.

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#561]
In ASFDS, definitions of callbacks can be strings, which it very usable when forms are stored/generated as pure JSON server side. I would very much like that for ASF, too. 

The code is straightforward, ASFDS simply looks in the form scope:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/src/angular-schema-form-dynamic-select.js#L232

(I guess "callbackScope" could be an a setting, but so far, no requests for that has surfaced).

Any objections?

**Comment by Anthropic** [comment]
@nicklasb onChange can take a string with the function inside, which callback were you referring to with this one, anything specific or just in general? This is a goal I have now, so over time I do want to reduce/remove having javascript in schema directly.

Let me know if there was anything else to this one or I will close it given it is a project goal now.
