### ISSUE TITLE
Weirdness with "type" arrays in schema

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#562]
This is a simplified version of my schema:
```
{
    "type": "object",
    "properties": {
        "number-of-volumes": {
            "type": [
                "string",
                "number"
            ]
        },
        "volume": {
            "type": [
                "string",
                "number"
            ]
        },
        "issue": {
            "type": [
                "string",
                "number"
            ]
        }
    }
}
````

I am experiencing some strange behaviour with the properties defined with type: [ 'string', 'number'].

Part of my application workflow allows the user to dynamically switch form types from within the application, when the form definition switches, the model is preserved through the use of:
```
sf-options="{ formDefaults: { destroyStrategy: 'retain' }}
```
The form definition switching is performed in the controller by simply changing the value of the variable that contains the form definition, which is bound to by the sf-form property.

The strange behaviour I'm seeing is this, when the form definition is switched, fields of type ['string', 'number'] are being populated like this in my model:
```
"number-of-volumes":"retain",
"volume":"retain",
"issue":"retain"
```
without any intervention from me, other than switching the form definition. If there is an existing value in one of these fields, it is overwritten by 'retain'.

I am completely mystified as to what could be happening here. It only seems to happen with fields of type ['string', 'number'], no others.

Any ideas?

**Comment by Anthropic** [comment]
@AndrewIsh can you supply a gist or method for replicating the issue?

**Comment by Anthropic** [comment]
@AndrewIsh without further information I'm closing the issue for now, please re-open if you can provide more information and need further support.
