### ISSUE TITLE
angular-schema-form and json-refs 

### ISSUE THREAD

**Issue by parvanova** [json-schema-form/angular-schema-form#564]
Hello,

first of all thank you for the great module!
I as many others was looking for solution for resolving $ref in schemas. And after reading the issues where it is discussed decided to try the workaround that was shared in this issue - https://github.com/Textalk/angular-schema-form/issues/118.
I can say it works but after a few clicks on the page. 
When the page is loaded the form is rendered without $refs being resolved. So the form element for the schema property where the $ref is user is not displayed. But after 1- 2 clicks the form is being redrawn and the refs are resolved.

Here is the plinkr - http://plnkr.co/edit/JtEKcdmqvzPFUh0YOqYy?p=preview

Can you please advice what am I doing wrong?
Thank you

**Comment by Anthropic** [comment]
You're setting the schema twice, you want to save it as a different variable first, then set it as the schema for ASF once the load of refs has completed.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by Anthropic** [comment]
As of 1.0.0-alpha.2 $ref is supported as a preprocessing step.
