### ISSUE TITLE
Conditional field not removed from model

### ISSUE THREAD

**Issue by PhilBroadbent** [json-schema-form/angular-schema-form#565]
Hi, I'm having a problem with the "condition" parameter. It's not removing the value from the model. This is the case for both 'select' and 'date' types . Below example is user selects something from select dropdown, then the date field is shown/hidden - but the date value in the model doesn't disappear. (And same for another select field if this condition is applied)

Schema:

```
type: "object"
properties: Object
    settlementdate: Object
        condition: "model.settlementtype==='0'"
        fixtag: 64
        format: "date"
        name: "settlementdate"
        required: false
        title: "Settlement Date"
        type: "string"
        uiType: "date"
settlementtype: Object
    default: "0"
    fixtag: 63
    name: "settlementtype"
    onChange: "dropdownChanged()"
    required: true
    title: "Settlement Type*"
    type: "string"
    uiType: "select"
```

Part of form:

```
condition: "model.settlementtype==='0'"
format: "yyyymmdd"
key: "settlementdate"
maxDate: Fri Oct 02 2015 13:29:03 GMT+0100 (GMT Daylight Time)
onChange: undefined
```

Any advice please?

**Comment by Anthropic** [comment]
@PhilBroadbent did you figure out how to deal with it? If not, can you make a gist (from the demo app)?

**Comment by Anthropic** [comment]
I think this is the same as #769 which I believe is fixed in the latest alpha so given the age of this I will close it for now.
