### ISSUE TITLE
Angular Form Object for validation in decorator?

### ISSUE THREAD

**Issue by inquire** [json-schema-form/angular-schema-form#566]
Hi guys, i'm trying to access the angular form in the decorator template that you define when you want to add a custom directive, but i can't seem to find a way on how to do it. I get something called "form" but that is not the angular form. Help?

**Comment by Anthropic** [comment]
What are you trying to do, there are plenty of ways to access data in your root scope, which is usually on the form tag?

**Comment by inquire** [comment]
I figured it out, i had to use the evalInScope function, but it was a bit to hidden in the documentation. :)
