### ISSUE TITLE
sending a arrayIndex as a parameter to onclick button function

### ISSUE THREAD

**Issue by franklopez** [json-schema-form/angular-schema-form#568]
Hi I have this issue:

form: 
{
          "type": "button",
          "htmlClass" : "bt-down",
          "onClick" : "showCountries(arrayIndex)",
          "icon": "fa fa-search"
}

this in inside an array, and i want to call showCountries(arrayIndex) and have the index array value in my function how can i do this?

regards,

Francisco Lopes

**Comment by Anthropic** [comment]
Have you tried $index?

**Comment by franklopez** [comment]
nope it doesn't work either the value comes undefined to the function:

$scope.showCountries = function(index) {

**Comment by Anthropic** [comment]
Can you provide a more detailed example of what you are doing, like a plunker or something similar? May help to see where the problem is.

**Comment by vinceis1337** [comment]
@Anthropic I can give an example:

I want to open a website based on the input in the form.
If the user enters in the text field "www.reddit.com" I want to launch a onClick method `launchWebsite(url);`
However, this is in an array so my onClick method looks like:
`launchWebsite(model.websites[indexArray].url);`

`indexArray` returns as `undefined` in the onClick method though.
If I put `"condition": "model.websites[indexArray].url"` this works fine for hiding or showing the button, for example. But the onClick method does not understand `indexArray`.

**Comment by Anthropic** [comment]
Thanks @franklopez @vinceis1337 I will look into it, I have added this to a copy locally and so far so good, I am hoping it can be done as part of PR #652

**Comment by coxrichuk** [comment]
Has anyone had any success with passing the arrayindex / $index as a parameter to a function?

**Comment by Anthropic** [comment]
@coxrichuk it is partially working in the webpack branch but at the same time it has other things broken. But you could certainly take a look there for ideas on how it was fixed, but there are also other questions asked in issues that also provide further info on how it can be overcome.

**Comment by Anthropic** [comment]
This works in the alphas for v1.0.0, you can pass whatever($index)

**Comment by vinceis1337** [comment]
Excited to see this functionality in 1.0.0!
