### ISSUE TITLE
[Discussion] - json-schema builder

### ISSUE THREAD

**Issue by ryedin** [json-schema-form/angular-schema-form#569]
This is a very obvious use-case and I'm sure it has been discussed at some point, so my apologies if this is a duplicate issue/discussion. (BTW: is there a discussion group somewhere for this project?) 

So here's the question to stem the discussion: 

Has anyone attempted feeding the json-schema schema into ASF yet, in order to build a form that is capable of creating a json-schema?

**Comment by vicary** [comment]
This question has been asked many times, and the upfront limitation is the support of `$ref`, `oneOf`, `anyOf` and `allOf`... etc. They planned "this fall" and "soonish", not sure how it goes tho.

**Comment by Anthropic** [comment]
Someone started planning a schema builder asking for feedback on features, can't remember who, but there is a repo someone started for it. Sorry to be so vague, don't have time to look it up now.

**Comment by rowino** [comment]
Hi guys,  built a simple implemention of the builder. I would love to get feedback. http://ralphowino.github.io/schema-form-builder

**Comment by Anthropic** [comment]
@rowino I believe Nicklas just invited you to our Gitter, we are more than interested in what you have done, please join us in Gitter :)

**Comment by Anthropic** [comment]
I'm closing this issue as @vicary has really answered the issue, although I will add that there is a link to our Gitter group from the main page https://gitter.im/json-schema-form/angular-schema-form, see you there @ryedin  :)
