### ISSUE TITLE
override input templates

### ISSUE THREAD

**Issue by iivvoo** [json-schema-form/angular-schema-form#57]
I (think I) need to override the individual (html) field definitions. I want to render my form horizontally (class=form-horizontal) but I understand this requires the input control to be wrapped in a div with a specific grid sizing class (e.g. col-md-8)

What options are there (besides forking :) to override the fields templates?

**Comment by 111crb111** [comment]
Hi, i'm angularjs noob :) wher i need write this
```javascript
 .config(['schemaFormDecoratorsProvider', function(decoratorsProvider){
    decoratorsProvider.addMapping('bootstrapDecorator', 'ckeditor', 'path/to/ckeditor.html');
}])
```
i think need some file like extendForm.js but dont know how use that function :(

**Comment by aman-gautam** [comment]
@mike-marcacci Do we need to put the custom template in $templateCache? Is there a step by step example on how to override the input templates?

Thanks,
Aman
