### ISSUE TITLE
Determine form element that onChange() happened on?

### ISSUE THREAD

**Issue by dhiraj** [json-schema-form/angular-schema-form#575]
I want to wire up a generic onChange() handler in my controller, by iterating over the elements and attaching a handler for a certain type of element.

Problem: Such a handler would need to be able to determine the key of the element it ran on, but there is no way to get this from the onChange handler signature `onChange(modelValue,form)`. I would think that adding the particular form element that the onChange happened on would be sensible for this purpose. Perhaps the signature should instead be: `onChange(modelValue,form,element)` ?

I want to wire it up this way because my form will have n-level nested drop down select functionality to choose hierarchies like Country->State->City, etc.

Anyone have thoughts on this?

**Comment by Knuckles9090** [comment]
getInputElement = function(form){
              input = form.key;
			input = input.join(",");	//join array
			input = input.replace(/,/g,".");	//replace commas with dots
			return input;
		};

I used this function earlier this year. Basically call this function in the beginning of your onChange function to get the input element.

**Comment by Anthropic** [comment]
@dhiraj have a look at the external-options add-on, it isn't complete but should give you an idea on how to have related drop downs call each other.

Please re-open if you do not feel the question has been answered sufficiently.
