### ISSUE TITLE
Regarding required Array in schema

### ISSUE THREAD

**Issue by senthilsendhil** [json-schema-form/angular-schema-form#581]
Its not issue, just want to clarify something, I like to pick the required filed based on some precondition,

For example if user enter first name and Last name is mandatory, else last name is not mandatoy 

Please let me know anyone can help me

**Comment by Anthropic** [comment]
@senthilsendhil You can provide two versions of the same field in your form definition with a condition to determine which displays. Note: you will need to be careful what your destroy behaviour is!

Please re-open if you do not feel the question has been answered sufficiently.
