### ISSUE TITLE
Clearing a schema form

### ISSUE THREAD

**Issue by parky128** [json-schema-form/angular-schema-form#584]
Hi,

Is there a way to destroy the rendered form?

I have a select input for the user to choose from a list of available schemas, I am adding a clear button, to reset the input, and so I need to remove the rendered fields when doing so. I tried setting the sf-form, sf-model and sf-schema directive attributes to undefined\null\empty objects but whatever I try i cannot get the rendered form to go away.

I have probably missed something in the docs, can someone point me in the right direction?

Thanks

**Comment by parky128** [comment]
I have also tried:

$scope.$broadcast('schemaFormRedraw');

after setting the schema, form and model directive attributes to empty objects, but this had no affect.

**Comment by noren** [comment]
+1

**Comment by noren** [comment]
Hi, I found that you need to start of from assiging form definition to the variable and then assinging it to the view using angular.copy, then inside onChange event you modify you schema and again the assigin it to the view variable again via angular.copy after that broadcasting the 'schemaFormRedraw' event. following comment was very helpful https://github.com/Textalk/angular-schema-form/issues/428

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
