### ISSUE TITLE
CKEDITOR Issue: Source Mode Does Not Trigger On Key Up Change Event 

### ISSUE THREAD

**Issue by chiewmey** [json-schema-form/angular-schema-form#586]
I found it only trigger key up change event with Rich Text mode, how can I call this event in Source Mode?

**Comment by nicklasb** [comment]
CKEditor is not a part of ASF AFAIK? Perhaps you meant to post this in some add-on:s issues?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
