### ISSUE TITLE
$asyncValidator fails because of $validators.schemaForm

### ISSUE THREAD

**Issue by petermekhaeil** [json-schema-form/angular-schema-form#594]
Hello,

We are having this issue that we are struggling to understand why its happening.

We are generating dynamic schema forms which have custom validators appointed to them, and this one custom validator is making a $http call and returns a promise based on the results of the $http response.

If our custom validator is valid, the form is still invalid because of ngModel.$validators.schemaForm in the schemaValidate directive.

Q1) Can someone please explain to me the purpose of this $validators.schemaForm validator and possibly why it would return true only if our $asyncValidator has passed?

Q2) I can understand this question can be hard without references to any code samples, but our $asyncValidator returns a promise from within a $http call because we need to validate the response returned from this $http - is this bad practice in angular's $asyncValidator? Could a promise within a promise be the cause of inconsistency in what gets returned to the validator?

Cheers,
Peter

**Comment by Anthropic** [comment]
@petermekhaeil sorry I couldn't help on this one sooner, I didn't really know the answer myself.

I'm going to close it due to age, but if it is still something you want to know please re-open and I will do my best to figure it out for you.
