### ISSUE TITLE
Allow evaluation on readonly like condition

### ISSUE THREAD

**Issue by robinduckett** [json-schema-form/angular-schema-form#597]
I don't know if this is a bug, or a feature, but currently, the "readonly" option which applies whether a form element should be disabled or not, take only a boolean value. If you pass in a model string, such as you can do with condition, it does not get evaluated, and gets cast as false, all the time.

https://gist.github.com/70a6463541309b29bacd

http://schemaform.io/examples/bootstrap-example.html#/70a6463541309b29bacd

It seems unintuitive that you can do this with conditional but not with readonly

**Comment by Anthropic** [comment]
@robinduckett thanks for the suggestion, it doesn't currently get evaluated, conditional is the only value evaluated. We are going to be looking into ways to enhance the setting of rules for various fields at the moment actually.

**Comment by robinduckett** [comment]
Thanks for getting back to me. Please let me know how it goes! Thanks.

**Comment by aman-gautam** [comment]
This would be a really great feature!

**Comment by Anthropic** [comment]
CLosing this in favour of #879 I do want it, just have some more core work to be able to. I am trying to swap validators first that should give me more options.
