### ISSUE TITLE
Question - Injecting custom validation on form fields

### ISSUE THREAD

**Issue by kazoompa** [json-schema-form/angular-schema-form#601]
Hi,

I have been Google-ing a lot on this and I couldn't find any descent answer, here is our setup:

The form schema and definition are returned from our Java server to our Angular client as a JSON document. We would like to add a custom validator on a form field. Since the form definition is returned as a string JSON, we cannot have the $validators set on the field as described in the documentation. We need to parse the form definition, find the valid field and then add our custom validator on the fields $validators list. Is there any way to do this nicely?

Thanks.

**Comment by Knuckles9090** [comment]
I used the onChange attribute to send the value of the input to a custom validator function. For example
"onChange": "validateSSN(modelValue, form)". Then in this function you could broadcast an schemaerror, if the value does not match a pattern or whatever criteria you need it to pass.

**Comment by kazoompa** [comment]
Thanks for the suggestion but the rendered form is client dependent and most of the users are researches who know nothing about programming. My idea is along the line of having a registry of validators per client in have a mechanism of identifying the field at parse time, inject the validator and let angular & schema-form take care of the rest. Right now I am playing the JSON.parse(json, reviver). I thought the reviver can provide me the name of the field which can be the key to my registry. Using the reviver may be help me inject the validator.

Cheers and waiting for some juicy solution ;)

**Comment by Anthropic** [comment]
@kazoompa can you add validators to tv4 with a directive by modifying the decorator?

**Comment by Anthropic** [comment]
Closing due to lack of recent comments
