### ISSUE TITLE
Index of tab in array/tabarray

### ISSUE THREAD

**Issue by tkitv** [json-schema-form/angular-schema-form#607]
Hi,

I need to set the values of other items of a tabarray in the success callback after backend validation. My form looks like this:

     {
          key: "Parkey",
          type: "tabarray",
          title: "{{$index }}",     //works     
          items: [
             "Parkey[].Number",
             "Parkey[].Name",
            {
               key: "Parkey[].BP",
               validationMessage: {
                        'bp': 'BP invalid'
                    },
                    $asyncValidators: {
                        bp: function (value) {
                            var deferred = $q.defer();
                            $timeout(function () {
                                viewModelHelper.apiGet('api/Dwh/ValidateBP?BP=' + value, null, function       (result) {                                
                                  if (result.data.length > 0) {                                       
                                        $scope.model.Parkey[***NEED INDEX HERE****].Name= result.data[0].Name;
                                        $scope.model.Parkey[***NEED INDEX HERE****].Number= result.data[0].Number;                                        
                                        deferred.resolve();
                                    }
                                    else deferred.reject();
                                });                               
                            }, 500);
                            return deferred.promise;
                        }
                    }
                }     
        ]

So how can I get that index? 

br

**Comment by nicklasb** [comment]
Could you please explain further?

**Comment by Anthropic** [comment]
@tkitv keep an eye on this PR it will allow you to find the value you are looking for when we are ready to merge it:
https://github.com/json-schema-form/angular-schema-form/pull/652

I'll close this issue for now.

**Comment by raquintero** [comment]
@Anthropic Has this exact issue been fixed somewhere?  I need an index value to pass along in an onChange event.
