### ISSUE TITLE
Fieldsets not working with multiple decorators

### ISSUE THREAD

**Issue by mogmog** [json-schema-form/angular-schema-form#608]
I am fighting with a very strange issue.

To best understand it, you will need to check out the demo app I have made;

https://github.com/mogmog/asfdemo.git

I am trying to create 2 decorators - one read only, and one regular edit style. THese have been created in app.js

https://raw.githubusercontent.com/mogmog/asfdemo/master/app/app.js

When I do this, if my form does not contain a fieldset, everything is fine (View2). Two forms are displayed, one read only, one not.

If however my form contains a fieldset (View 1), then the read only decorator is applied to both forms, which seems very wrong. Any ideas?

**Comment by Anthropic** [comment]
@mogmog the form only uses one decorator, can you make a plunker or jsfiddle?

**Comment by Anthropic** [comment]
@mogmog, I have to close this for now, if you can provide a gist or plunker, please re-open the issue and I'll do my best to help!
