### ISSUE TITLE
Font-Awesome Support

### ISSUE THREAD

**Issue by apinnecke** [json-schema-form/angular-schema-form#609]
Would be nice to support FA, would like to use Font-Awesome rather then Glyphicons. Is it already possible and I'm missing some things?

**Comment by Knuckles9090** [comment]
Its already possible, show me what you are trying to do

**Comment by apinnecke** [comment]
Due to missing docs on that topic, i tried nothing yet. Could you provide some example code?

**Comment by Knuckles9090** [comment]
Do you want to use them fieldAddons or where specifically?

**Comment by Anthropic** [comment]
@Knuckles9090 thanks for responding to the issue I appreciate it!

As the OP hasn't responded I'm closing the issue, please feel free to re-open and continue discussion if @apinnecke responds.
