### ISSUE TITLE
Is there an easy way to apply different styling via CSS to every required field?

### ISSUE THREAD

**Issue by israelidanny** [json-schema-form/angular-schema-form#612]
I'm trying to apply specific CSS for any field that is required. 

I know I can add custom classes, but the schema might change, and I'm wondering if there's a way to style something just by knowing that it is a required field.

**Comment by nicklasb** [comment]
Good idea, but meanwhile, can't this help you out?
https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#inline-feedback-icons

**Comment by israelidanny** [comment]
Well, the whole idea is to let the user know what is required and what isn't *before* validation, for a good UX

**Comment by nicklasb** [comment]
Isn't that what it does? 
"ex. displaying an asterisk on required fields"
And then the example looks att form.required?

**Comment by nicklasb** [comment]
Not sure if form.require mirror what the schema.required say, but it feels like it should if is doesn't.

**Comment by fpernia** [comment]
It will be a great feature "know what is required and what isn't before validation" @israelidanny

**Comment by israelidanny** [comment]
What does `not screened` mean? :) I understand the consensus is that it's still not there? Could I contribute it ? Where would I start looking?

**Comment by nicklasb** [comment]
If means that we had a drive to get rid of a lot of old issues, and this one haven't been deemed either way yet. You could certainly contribute, If you want to learn about the structure of ASF, an article has been started at the wiki: https://github.com/json-schema-form/angular-schema-form/wiki/Architecture

**Comment by nicklasb** [comment]
However, part of the core is being broken out(https://github.com/json-schema-form/json-schema-form-core/tree/feature/first-steps), so at this exact moment PR:s is a bit problematic. But look into it, implement it and it could probably quite easily be refactored into the new structure.

**Comment by Anthropic** [comment]
Updated bootstrap repo, added required to css on outer div. This can be used like
```css
.required label::before {
  content: "* ";
}
```
This is in the first stage of work for 1.0.0 alpha 5 in the developer branch of bootstrap repo.
