### ISSUE TITLE
is it possible to validate one form with the $scope.broadcast?

### ISSUE THREAD

**Issue by Sef1995** [json-schema-form/angular-schema-form#616]
Hi there,

I'm using angular schema form my project and I was wondering if it is possible to broadcast a "schemaFormValidate" but only for one form?

**Comment by Sef1995** [comment]
I used this pull request to fix this; https://github.com/Textalk/angular-schema-form/pull/589

**Comment by nicklasb** [comment]
That is a good idea indeed.
