### ISSUE TITLE
How the field input binds to the model in the new builder

### ISSUE THREAD

**Issue by stevehu** [json-schema-form/angular-schema-form#618]
@davidlgj Your articles on medium helped a lot to understand the new builder you are working on; however, I am having hard time to understand how the field binds to the model right now? Is sfSelect obsolete?  If so, how do you decide which deep variable to be bound in the fieldset/array?
Above question will greatly help me to complete fieldset and array migration to react-schema-form.

https://github.com/networknt/react-schema-form

Thanks.

**Comment by nicklasb** [comment]
Wow, you have really gotten some work done there lately, @stevehu!
Is there any common code that can be shared between the projects?

WRT @davidlgj, he has been on parental leave for a while now, don't know when he's back, he haven't been on gitter either although you could try there.

**Comment by stevehu** [comment]
@nicklasb I have tried to put some common functions into the utils module but modified some of them. As you can see from the demo, it works so far. react is much easier than angular:)

**Comment by nicklasb** [comment]
@stevehu, yes, React is a different approach. 
In my opinion, React is more for web sites and Angular more for web-based desktop applications if you know what I mean. Or at least that would be where I make the choice.

**Comment by stevehu** [comment]
@nicklasb I had been working on Angular 1.x for over two years before switching to React. It wasn't easy as I had over 100 angular components need to be rewritten in my framework:( I don't know the current angular 2.0 status as it is none of my business. In my opinion, angular is suitable for small applications as the component encapsulation is poor. Once you have dozens components interact with each other, you will be lost in the communication. I will write an article to compare them once I have time.

**Comment by Anthropic** [comment]
I'm going to close this if that's ok @stevehu as this conversation can happen on Gitter more easily now as we move toward a unified core. Hope you got some of the info you were after by now :)

**Comment by stevehu** [comment]
Yes. I worked off an old version of the builder and it is relatively de-coupled with Angular. Thanks.
