### ISSUE TITLE
How to split the data model and data submitted to the server?

### ISSUE THREAD

**Issue by Chills719** [json-schema-form/angular-schema-form#620]
example:
$scope[attrs.ngModel][field.model] = "man";

The form will be displayed in the letters "man",
Finally on the model is also a letter in the "man", this time I want to change the value of the resulting model to 0,what should i do?

**Comment by nicklasb** [comment]
I am not at all sure what you mean, but if you wan't to do something if something happens, there is the onChange option.
https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#onchange

**Comment by Anthropic** [comment]
@Chills719 are you referring to a titleMap also in the documentation Nicklas has linked to?

Please re-open if you do not feel the question has been answered sufficiently.
