### ISSUE TITLE
Angular 2.0 and Latest Thoughts

### ISSUE THREAD

**Issue by rayhooker** [json-schema-form/angular-schema-form#621]
I wanted to get an update on your thoughts about angular-schema-form and Angular 2.0.  I developed a prototype and about to move into full scale development.  I found your framework excellent and helped to get a lot of functionality quickly.  The frustration was that some of the aspects of Angular 1.0 made it difficult that I think are addressed by the changes in Angular 2.0.  

Your biggest "competitor" formly plans to sunset in favor of Angular 2.0 form.  This is a problem because.. unless I missed something.. I don't see the ability in 2.0 forms to define a form as well as it's schema strictly using JSON (i.e., data for both).. meaning truly dynamic forms. It can see refactoring, but there still seems to be a need.  Thoughts and plans?

**Comment by gjk0090** [comment]
@rayhooker Hey bro I just saw the same issue you raised at Formly :)
I'm in same situation as you. 
These two are great frameworks but we definitely want to catch up with latest versions. 
Could you share me anything else you've found?
(Is it good to talk about other frameworks here?)

**Comment by rayhooker** [comment]
Well kudos of course to the work done here for schema-form. I would assume that with schema built in to For Angular 2.0 that at minimum it would need to be refactored to focus primarily on the generation of the form from a json schema.  Also I imagine it could be refactored and perhaps simplified.  

I also am doing a spike on React to build a project and try out two React projects similar to schema form here.  Clearly if the authors of this project have plans for migrating to Angular 2.0, I am very interested as I already have a working prototype with Angular 1.x and Schema Form.

**Comment by Anthropic** [comment]
It is definitely something we'll be looking at sooner rather than later now ng2 is in beta, the more the community wants the more it gets, if there is interest then people will find the time to help and progress the tool.

**Comment by nicklasb** [comment]
@rayhooker  It seems that Angular 2 will not have a support for json schema? They "leave that to the community"?
https://github.com/angular/angular/issues/1034

**Comment by Anthropic** [comment]
@rayhooker we are separating the core out of the angular schema form repo into its own repo and plan to start on Angular 1+2 and React versions that feed off a unified core. You can keep track of the discussions via the Gitter groups we have going for each repo.

**Comment by mhelvens** [comment]
Is there a separate repo or issue to track progress on the Angular 2 version?

**Comment by nicklasb** [comment]
Just for information for this thread, I have previously posted it in the gitter feed, but I will repost it here, for those who may consider A2 support a showstopper, there is an interim solution:

It is possible to combine ASF and Angular 2 components using ngUpgrade.

@rowino and his team has helped me rewrite an admin interface for a framework I am creating(aren't we all) in a hybrid Angular 1/Angular 2 environment.

It is written in Typescript, uses SystemJS/JSPM and has a plugin structure, so its technically pretty advanced and perhaps it is not the most simple example.

But its there, a simpler example should not be too hard to extract from it at some point.

Actually running the system and viewing the content currently takes some effort, currently, so you have to take my word for it that it works. :-)

The code resides here:
https://github.com/OptimalBPM/of-admin/tree/master/ui

**Comment by mhelvens** [comment]
So is there a separate repo or issue to track progress on the dedicated Angular 2 version of JSON Schema Form (based on that unified core mentioned above)?

**Comment by Anthropic** [comment]
@mhelvens not yet, still a bit more to do before we can start it
