### ISSUE TITLE
titleMap:{name:'1',value:'name'}  need to map name and value with actual field

### ISSUE THREAD

**Issue by fssAnkur** [json-schema-form/angular-schema-form#622]
titleMap:{name:'1',value:'name'} here name and value is fixed standard for titleMap. but it is not possible to get json from server side with name/value header every time so is it possible to map name/value property?

**Comment by fox1t** [comment]
I have similar question about enum prop of the schema.

**Comment by nicklasb** [comment]
No, there is no such functionality in ASF. However there is in the [angular-schema-form-dynamic-select add-on](https://github.com/OptimalBPM/angular-schema-form-dynamic-select) add-on (that I maintain). Mentioning that since I presume you ask about selects?

**Comment by Anthropic** [comment]
@fssAnkur we are looking at this as part of the new core and @nicklasb 's add-on can certainly help. I am closing this issue, please re-open if you have more to discuss, but we are considering better methods for providing more basic options in the core schema, these will be discussed in the json-schema-form repo soon as we start to plan ahead.
