### ISSUE TITLE
Cannot use the latest version

### ISSUE THREAD

**Issue by abku** [json-schema-form/angular-schema-form#627]
Hi,

I just downloaded the latest zip and added it to my code.  I get an error when I try to add it to my module.  angular.module('myApp', ['ngRoute', 'ngGrid', 'schemaForm']);
Here is the error:

Error: [$injector:modulerr] Failed to instantiate module myApp due to:
[$injector:modulerr] Failed to instantiate module schemaForm due to:
r is undefined
@http://localhost/libs/angular-schema-form/schema-form.min.js:1:599
invoke@http://localhost/libs/angular/angular.js:4523:14
instantiate@http://localhost/libs/angular/angular.js:4531:27
provider@http://localhost/libs/angular/angular.js:4365:1
supportObject/<@http://localhost/libs/angular/angular.js:4357:16
runInvokeQueue@http://localhost/libs/angular/angular.js:4429:11
loadModules/<@http://localhost/libs/angular/angular.js:4437:11
forEach@http://localhost/libs/angular/angular.js:340:11
loadModules@http://localhost/libs/angular/angular.js:4419:5
loadModules/<@http://localhost/libs/angular/angular.js:4436:40
forEach@http://localhost/libs/angular/angular.js:340:11
loadModules@http://localhost/libs/angular/angular.js:4419:5
createInjector@http://localhost/libs/angular/angular.js:4344:11
bootstrap/doBootstrap@http://localhost/libs/angular/angular.js:1676:20
bootstrap@http://localhost/libs/angular/angular.js:1697:1
angularInit@http://localhost/libs/angular/angular.js:1591:5
@http://localhost/libs/angular/angular.js:29013:5
n.Callbacks/j@http://localhost/libs/jquery/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@http://localhost/libs/jquery/jquery-2.1.4.min.js:2:27738
.ready@http://localhost/libs/jquery/jquery-2.1.4.min.js:2:29530
I@http://localhost/libs/jquery/jquery-2.1.4.min.js:2:29721

Am I doing anything wrong?  How do I fix this?  I am using latest version of everything as this is a new project.

**Comment by nicklasb** [comment]
Hi, 

Sorry, not enough information (for me at least), please create a plunkr or jsfiddle.

**Comment by hanula** [comment]
@abku try installing all dependencies.

**Comment by Anthropic** [comment]
Please re-open with more information
