### ISSUE TITLE
Signature Add-on

### ISSUE THREAD

**Issue by ibuilder** [json-schema-form/angular-schema-form#628]
Has anyone made a signature pad add-on yet?  Maybe using this library..

https://github.com/szimek/signature_pad

**Comment by nicklasb** [comment]
I haven't seen any, but it shouldn't be that difficult. 
There are guides and examples (and a generator) on how to write add-ons at: https://github.com/OptimalBPM/angular-schema-form-add-ons
The official guid is at: https://github.com/Textalk/angular-schema-form/blob/master/docs/extending.md

**Comment by JamesGuthrie** [comment]
I have created [angular-schema-form-signature](https://github.com/JamesGuthrie/angular-schema-form-signature). It's based on my explicit use-case, and as such has quite limited functionality for now, I would appreciate feedback on how you would like to be able to customise the signature field.

**Comment by nicklasb** [comment]
Ok, I had a quick look, and I have the following feedback:
Expand on the documentation, explain in short what the signature is and what data it generates, do not expect people to follow links too much, those are for reference stuff.
With regards to options, I added some new bullets to the add-ons-repo wiki:
https://github.com/json-schema-form/angular-schema-form-add-ons/wiki/Creating-a-new-add-on#do
