### ISSUE TITLE
Custom field options

### ISSUE THREAD

**Issue by dorin-niscu** [json-schema-form/angular-schema-form#629]
In this moment **ng-model**, **id** and **name** are generated based on form.key
I need to set them separately for a multilingual website.

**Example**: 
**id** and **name** could be **title_en** / **title_es** but **ng-model** needs to be **[en][title]** / **[es][title]**.

I can not obtain it only by modifying **form.key** into **en.title** / **es.title** because **id** becomes **title** in both cases.

I tried to add **id** and **name** options but it does not work as expected.

`<input ng-if="!form.fieldAddonLeft && !form.fieldAddonRight" ng-show="form.key" type="string" step="any" sf-changed="form" placeholder="Title" class="form-control  ng-valid-schema-form ng-touched" id="title_en" ng-model-options="form.ngModelOptions" ng-model="model['en']['title']" ng-disabled="form.readonly" schema-validate="form" name="title_en" aria-describedby="titleStatus">`

**Comment by nicklasb** [comment]
Hi, an example on plunkr or jsfiddle would help here.

**Comment by Anthropic** [comment]
@dorin-niscu would it be enough to have control over a filter on what is set as name in the form?

**Comment by Anthropic** [comment]
@dorin-niscu the id is now handled with a function call that makes it a full path including array indexes, there is a class added to the parent that shows the schema path. Closing this for now, let me know if you have further questions, there are other tickets that provide information on how to work with i18n if it is stilll causing headaches.
