### ISSUE TITLE
bootstrap V4

### ISSUE THREAD

**Issue by flythird** [json-schema-form/angular-schema-form#631]
Hello from france ! 

i discover angular-schema-form  and i have a question : the bootstrap v4 alpha version is plugged on my project and so there is some disfonctions.

Is it possible to see a future new version working with bootstrap V4. ?

I don't know this subject....may be somebody made some css modifications or customized css options 
to work with bootstrap v4.. i'am not afraid otherwise it's panic

thanks for your attention

**Comment by Anthropic** [comment]
@flythird Je suis desole, je ne parle pas francais!
The boostrap decorator has moved to here: https://github.com/json-schema-form/angular-schema-form-bootstrap

Please make the suggestion there, it will need a pull request from someone to be updated though.

**Comment by Anthropic** [comment]
Closing this issue here, the only way it will get updated is if someone makes a PR to bring it up to date. I really would love that to happen, perhaps a fork of the decorator would be a good start to move toward a consensus on an upgrade after the 1.0.0 version is out.
