### ISSUE TITLE
Converting an empty string to undefined

### ISSUE THREAD

**Issue by plaa** [json-schema-form/angular-schema-form#640]
We're having trouble creating an optional email field.  Our JSON schema has type: 'string', format: 'email', which means that the field, if present, is validated on server side to be an email address.

We want the field to be optional, so that if the user does not type anything, it is left missing.  What is currently happening is that the empty text field is converted into an empty string, which fails the email validation server-side.

Is there a way instruct Angular schema form to convert an empty string into a missing value?  I'd think this would have other uses as well wrt optional fields.

Overall there seems to be a disparity between how JSON schema validation and Angular schema form interprets 'required' fields:  A JSON schema will validate a required field if it is an empty string, but Angular schema form interprets a required field to mean a non-empty string.

**Comment by Anthropic** [comment]
@plaa I believe this is more of an Angular behaviour than a ASF behaviour from memory. There are a few ways to do it, you can have a tick box in the form definition that determines if the email is required, such as say, contact method, this allows you to set a destroy behaviour to remove the value from the form.

Please re-open if you do not feel the question has been answered sufficiently.
