### ISSUE TITLE
Array validation seems to be broken when additional items are added

### ISSUE THREAD

**Issue by Choc13** [json-schema-form/angular-schema-form#641]
If an additional item is added to an `array` input field then it initially has the classes `form-control`, `ng-invalid`, `ng-invalid-tv4-302`, `ng-empty`, `ng-invalid-schema-form`, `ng-touched`, but I was expecting it to have `form-control`, `ng-empty`, `ng-valid-schema-form`, `ng-touched`.

Here is a [Plunker](http://plnkr.co/edit/gessHBhR3TDb3N5Xf3Zx?p=preview) showing this; just add an additional item to the array and it will immediately be in an invalid state.

Interestingly this doesn't seem to be the case for the array example on the [demo site](http://schemaform.io/examples/bootstrap-example.html). This behaves as I would expect it to, I have a feeling this is using the version of the bootstrap decorators prior to them being moved to a separate repository and hence something seems to have changed in the latest version.

Also, this may or may not be related, but as soon as a second item is added to the array a `Required` validation message appears for the entire array object. This sort of makes sense given that the second item is invalid, but if I then remove the second item this validation message remains. Further still if I remove the first item then the `Required` validation message disappears, which is not what I would expect given that the `comments` item is required as part of the JSON schema and is now completely empty, so I would expect the `required` validation to trigger at this point.

**Comment by romiem** [comment]
+1 Agree that this is strange behaviour. I would expect that when a new item is added to the array, it should have an untouched state, and not show an error message until it has become dirty.

**Comment by grobgl** [comment]
The bug has been introduced in version 0.8.11. Check out a working example running 0.8.10 in [this Plunker](http://plnkr.co/edit/tw7iRtcBE8ADLf4dsPzy?p=preview).

**Comment by Anthropic** [comment]
@grobgl thank you for confirming that, a big help :)

**Comment by grobgl** [comment]
Getting rid of the `firstDigest` variable (which has been introduced in 0.8.11) entirely seems to fix the issue, but I'm not sure if that has any other implications.

**Comment by slyadams** [comment]
Is this also the root cause for this issue: [Plunk](https://plnkr.co/edit/zfb9uGvmkPukOAZtuzk7)?

**Comment by Anthropic** [comment]
This should be working in the latest alphas.
