### ISSUE TITLE
default selection for radios

### ISSUE THREAD

**Issue by nisan250** [json-schema-form/angular-schema-form#645]
is it possible to make a default selection fr the radio button?
i trying to render radio buttons (rounded ones) and no one is selected? i need the first one to be selected. 

i tried using the event "sf-render-finished" but the form is not on the DOM yet.

**Comment by Anthropic** [comment]
Do you have a default value in the schema that matches the value in your titleMap or enum?

If you want help it is often best to make a gist from the demo site of what you are trying to achieve.

**Comment by Anthropic** [comment]
@nisan250 as you haven't responded I'm closing the issue, please re-open if you feel it wasn't answered and you require further information.
