### ISSUE TITLE
Custom Type - Issue

### ISSUE THREAD

**Issue by pbijvani** [json-schema-form/angular-schema-form#646]
I have created a custom type using directive for my need. I have kept type of form as 'myCustomType' which set model value of type array. 
Now if i set type of schema as 'array', it doesnt render form. 
If I set type of schema as 'string' or something else, it gives error 'invalid type, string expected' 
If I set type of schema as 'somecustometype', it works fine but required validation doesnt work.

How to approach this issue?

Ideally I should set type as array, because custom type is giving back array, but this doesnt render form. Or If i set my custom type on scheme, how to implement required validation?

Please help

**Comment by Anthropic** [comment]
Hi @pbijvani it is usual for the correct type to be in the schema but the custom type in the form definition. Can you make a gist of show an example?

**Comment by Anthropic** [comment]
@pbijvani with no response for nearly a month I'm closing the issue, please re-open if you require further assistance, happy to help.
