### ISSUE TITLE
Stick to the angular npm convention

### ISSUE THREAD

**Issue by xbill82** [json-schema-form/angular-schema-form#650]
Hi, thanks for the great package!

It would be great that the npm distrib could ship with an `index.js` that `require`s the non minified dist (so that Webpack users can choose whether they minify it or keep it clear for debug purposes) and `module.exports` the name of the module, so that you can do

```javascript
angular.module('yoloModule', [require('angular-schema-form')])
```

**Comment by Anthropic** [comment]
Thanks for the submission @xbill82 someone else is working on the webpack stuff, but for me do you have a link to the "standard" way of doing it you are referring to so I can pass it along?

**Comment by nicklasb** [comment]
But can't webpack read the "main" entry point of the package.json file? 
Because that is the standard AFAIK.

**Comment by Anthropic** [comment]
Please re-open if you can supply more details.
