### ISSUE TITLE
using select  box:  the first option empty with value="?".

### ISSUE THREAD

**Issue by nisan250** [json-schema-form/angular-schema-form#653]
the oneOf is not supported in angular schema form and we developed our on oneOf function which not showing the first option in the select box.

the select box have options, every option choose another schema.
the select box render correctly but i always get the first option empty with value="?".
what should i do to render the select box without the empty option?

**Comment by joelwkent** [comment]
The empty option is there because the initial value referenced by the model is not in the list of select options. To remove the empty option you need initialise your model value. You can do this using the  `default` parameter in the schema or by setting the value in the model

Setting a default value in the schema:

```
'key': 'mySelect',
'enum': ['opt1','opt2','opt3'],
'default': 'opt1'
```

or initialise the mode value:

`model = { mySelect: 'opt1'}`

**Comment by Anthropic** [comment]
@nisan250 just to add to @joelwkent 's answer, this is how ngModel behaves when dealing with selects, it can be a huge nuisance at times and can require changes that don't feel right like adding defaults you normally wouldn't feel you need to.

Anyway if you feel you need more info on this please re-open the issue but I am closing it now, thanks :)

**Comment by sandeepbhatt** [comment]
Hi , I want to remove empty row from json:from which is created through below json

{
    "type": "object",
    "required": ["editors_used"],
    "properties": {
        "editors_used": {
            "type": "array",
            "title": "What editors do you use?",
            "minItems": 1,
            "items": {
                "type": "string",
                "enum": [
                    "vim", "emacs", "sublime", "kate"
                ],"default":"vim"
            },
            "additionalItems": false
        }
    }
}
