### ISSUE TITLE
Is there a way to generate some inputs from a json and include them in existing form

### ISSUE THREAD

**Issue by amenzoweb** [json-schema-form/angular-schema-form#654]
Hello thank you for your rich set of directive, i have a question , i made a form in my app but i would like to generate some other inputs via schema and add them to my form. its possible? 

i know that we cant make form inside another form. 

Thank you in advance

**Comment by Anthropic** [comment]
@amenzoweb 
Yes, you don't need to use a form tag for the parent directive attributes, it can work on a div just the same. But you may not get the desired name attribute on the form variable, but you can get around that by mapping the model value into a hidden field with the name you desire.

Please close the issue if that answers your question :)
