### ISSUE TITLE
Array property is not being validated

### ISSUE THREAD

**Issue by FrancoAA** [json-schema-form/angular-schema-form#657]
Hi there,
First of all I want to say thank you, because this library is soo useful and It saves a ton of time!!
I have this schema, the problem is that even when the field is required no validation is performed:

```javascript
{
    "type": "object",
    "properties": {
      "URL": {
        "type": "array",
        "title": "URL"
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["URL"]
  }
```

I think that the problem is related to the fact that after typing something inside of the field even if I empty the field on the model the field is not being set to null instead It is set to an empty string.
**Is It there any possible solution for this problem?**
I have found that I can solved the problem if I change the schema to make it look like this:

```javascript
{
    "type": "object",
    "properties": {
      "URLs": {
        "type": "array",
        "title": "URLs",
        "items": {
          "type": "object",
          "properties": {
            "url": {
              "title": "URL",
              "type": "string"
            }
          },
          "required": ["url"]
        }
      }
    }
  }
```

But is not fun to have to change all the schemas I have like hundreds of them.

Thanks in advance!

**Comment by Anthropic** [comment]
@FrancoAA can you make a gist using the demo?

I have had similar issues with the array handling, it does need to be reworked, we are re-writing much of the functionality at the moment. minLength was what I used to get around it in my case, but I am not sure about your options if you have so many schemas that would need updating, so it could be something we look at if a test or gist is available.

**Comment by FrancoAA** [comment]
@Anthropic Thanks for your reply,
 This is embarrassing the solution is soo simple, adding a **required** equals true on the schema for the field solves the problem.

```javascript
{
    "type": "object",
    "properties": {
      "URL": {
        "items": {
          "type": "string",
          "required": true
        },
        "type": "array",
        "title": "URLs"
      }
    }
  };
```

 Thanks for your time.
