### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by miecio1212** [json-schema-form/angular-schema-form#659]
Why I get this error ?? 
everything works ok untill I use arrays 
angular.js:13424 TypeError: Cannot read property 'type' of undefined
    at defaultFormDefinition (schema-form.js:1050)
    at Array.array (schema-form.js:1221)
    at defaultFormDefinition (schema-form.js:1054)
    at schema-form.js:1417
    at Object.forEach (angular.js:335)
    at Object.service.defaults (schema-form.js:1414)
    at Object.service.merge (schema-form.js:1313)
    at render (schema-form.js:2582)
    at schema-form.js:2678
    at Scope.$digest (angular.js:16860)

        $scope.schema = {
            type: "object",
            properties: {
                name: {type: "string", minLength: 2, title: "Name", description: "Name or alias"},
                title: {
                    type: "string",
                    enum: ['dr', 'jr', 'sir', 'mrs', 'mr', 'NaN', 'dj']
                },
                cos: {
                    type: "array",
                    enum: ['dr', 'jr', 'sir', 'mrs', 'mr', 'NaN', 'dj']
                }
            }
        };

        $scope.form = [
            "*",
            {
                type: "submit",
                title: "Save"
            }
        ];

        $scope.model = {};

<script src="./bower_components/angular/angular.js"></script>
<script src="./bower_components/angular-schema-form/dist/schema-form.js"></script>
<script src="./bower_components/tv4/tv4.js"></script>
<script src="./bower_components/objectpath/lib/ObjectPath.js"></script>
<script src="./bower_components/angular-schema-form/dist/bootstrap-decorator.js"></script>

**Comment by Anthropic** [comment]
Using enum, the type should be string, not array. Array requires an item definition.
Check out the example app to see it in action.

Please re-open if you have further questions.

**Comment by miecio1212** [comment]
from docs :
"type": "array" and a "enum" in array type	checkboxes

**Comment by Anthropic** [comment]
@miecio1212 yes but they are for the **form** definition, you put array in the **schema** definition.

Try:
```javascript
$scope.schema = {
  "type": "object",
  "properties": {
    "name": {"type": "string", "minLength": 2, "title": "Name", "description": "Name or alias"},
    "title": {
      "type": "string",
      "enum": ["dr", "jr", "sir", "mrs", "mr", "NaN", "dj"]
    },
    "cos": {
      "type": "array",
      "items": {
        "enum": ["dr", "jr", "sir", "mrs", "mr", "NaN", "dj"]
      }
    }
  }
};

$scope.form = [
  "name",
  "title",
  {
    "key": "cos",
    "type": "checkboxes"
  },
  {
    "type": "submit",
    "title": "Save"
  }
];
```
