### ISSUE TITLE
Passing option to a specific field without overidding the others

### ISSUE THREAD

**Issue by LeonardoGentile** [json-schema-form/angular-schema-form#668]
Hello,
I'm retrieving my schema from backend metadata and I'm rendering all of the fields, so that my `$scope.form = ["*"]`. 
I'm trying to maintain the things as generic as possible so I don't want to modify/override the fields in the `$scope.form`. The problem is that I know that between these fields there is one I'm interested on and I want to pass specific options only for this one.

Right now, following the docs I should have to:
```
$scope.form = [
  "field1",
  "field2",
  {
     key: "field3",
     options: { // things here }
]
```
In this case I want to pass an options object only for "field3" without having to override field1 and field2 (that could be unknown fields to me). Is it possible? How?

**Comment by joelwkent** [comment]
One possible solution would be to use [x-schema-form](https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#form-defaults-in-schema) to insert your options into the schema.

So say the backend returns a schema like:
```
$scope.schema = {
  "type": "object",
  "title": "Comment",
  "properties": {
    "field1": {
      "title": "Name",
      "type": "string"
    },
    "field2": {
      "title": "Email",
      "type": "string"
    },
    "field3": {
      "title": "Comment",
      "type": "string"
    }
  }
}
```

Then before you render the form you could insert the options into the schema like so
`$scope.schema.properties.field3["x-schema-form"] = {options: {opt1: "value1"}};`

and keep your form as:
`$scope.form = ["*"]`

I have not tested this but I think it would work. Also I have not tested `x-schema-form` with the new builder but I assume it still works.

**Comment by LeonardoGentile** [comment]
Seems to work, thanks!

**Comment by joelwkent** [comment]
Great, thanks for confirming.
