### ISSUE TITLE
Problems with Condition

### ISSUE THREAD

**Issue by example2049** [json-schema-form/angular-schema-form#670]
I have some problems using condition for a key. I don't know if it getting the variable from the scope. I can show you the problem with the following example
Javascript:
var myApp = angular.module("myApp", ['schemaForm']);
myApp.controller("myCtrl", function ($scope) {
	$scope.schema = {
		"type": "object",
		"title": "Comment",
		"properties": {
			"name": {
				"title": "Name",
				"type": "string"
			},
			"email": {
				"title": "Email",
				"type": "string"
			}
		}

	};

	$scope.form = [
		"name",
		{key: "email",
			condition: "name=='abc'"
		},
		{
			"type": "submit",
			"style": "btn-info",
			"title": "OK"
		}
	];

	//$scope.model = {};

});
_____________________________________________________________________
HTML:

<!DOCTYPE html>

<html ng-app="myApp">
  <head>
    <title>TODO supply a title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="bower_components/angular/angular.js" type="text/javascript"></script>
	<script src="bower_components/angular-sanitize/angular-sanitize.js" type="text/javascript"></script>
	<script src="bower_components/tv4/tv4.js" type="text/javascript"></script>
	<script src="bower_components/objectpath/lib/ObjectPath.js" type="text/javascript"></script>
	<script src="bower_components/angular-schema-form/dist/schema-form.js" type="text/javascript"></script>
	<script src="bower_components/angular-schema-form/dist/bootstrap-decorator.js" type="text/javascript"></script>
	<script src="js/app.js" type="text/javascript"></script>
  </head>
  <body ng-controller="myCtrl">
    <form sf-schema="schema" sf-form="form" sf-model="model"></form>
  </body>
</html>

I'm trying to display the email textfield when the user enters abc in the name textfield. Unfortunately, the textbox is nor displayed. If I change the conidtion to 3<4 the email textfield is displayed.

**Comment by Anthropic** [comment]
@example2049 can you make a gist using the demo app or a plunker please?

**Comment by joelwkent** [comment]
Hi @example2049 I believe your condition needs to be:
condition: "model.name=='abc'"

Also your $scope.model is commented out

**Comment by example2049** [comment]
Thanks, for the help. The problem was the model.property
