### ISSUE TITLE
Disable add link in tabarray like in array

### ISSUE THREAD

**Issue by Machadalo** [json-schema-form/angular-schema-form#671]
Hi I have a situation where I want to disable to the add link in tab functionality. Could you please let me know how can this be achieved. Thanks in advance

**Comment by Anthropic** [comment]
@Machadalo please read the documentation for array, your answer is there:
https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#array
"To suppress add and remove buttons set add to null and remove to null."

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by Anthropic** [comment]
Actually you said tab array, my bad.

**Comment by Machadalo** [comment]
Yes, Its a tab array. Could you please help me on this

**Comment by Anthropic** [comment]
@joelwkent you just did a PR on tabarray, did you see anything that would explain why this wouldn't be working?

**Comment by Machadalo** [comment]
Did not found solution to disable add link?

**Comment by joelwkent** [comment]
Tab array does not currently support hidding the add and remove buttons like array. @Machadalo would you like to raise a pull request to add this? Otherwise I'm happy to add this functionality as I currently have a pull request open regarding tab array.

**Comment by Machadalo** [comment]
It would be great if you can add this functionality.. Thanks in advance

**Comment by joelwkent** [comment]
No problem @Machadalo, I'll expand [PR 19](https://github.com/json-schema-form/angular-schema-form-bootstrap/pull/19) to include this enhancement. I'll close this issue. Please re-open if you do not feel the question has been answered sufficiently.
