### ISSUE TITLE
Inconsistences when try creating a lumx-decorator

### ISSUE THREAD

**Issue by thiagog3** [json-schema-form/angular-schema-form#675]
#### Enhancement

I'm trying to create a new decorator based on lumx angular components [http://ui.lumapps.com/](http://ui.lumapps.com/). First of all, I forked bootstrap-decorator and only implement a default template to test input decorator. Something like this:

``` html
<div class="p+ pt0 pb0 {{form.htmlClass}}"
     ng-class="{ '{{'schema-form-'+form.type}}': true, 'has-error': form.disableErrorState !== true && hasError(), 'has-success': form.disableSuccessState !== true && hasSuccess(), 'has-feedback': form.feedback !== false }">

  <lx-text-field lx-label="{{form.title}}" lx-error="form.disableErrorState !== true && hasError()">
    <input ng-show="form.key"
         type="{{form.type}}"
         sf-changed="form"
         sf-field-model
         schema-validate="form">
    </lx-text-field>

  <div class="text-field-error" sf-message="form.description"></div>
</div>
```
#### Expected behaviour

I expected that validations working as well, including messages of regex invalidation (like bootstrap-decorator works)
#### Actual behaviour

It actually broken validations and any behaviors about validations like function hasError() not working good.
#### Gist/Plunker/Demo

[http://plnkr.co/edit/J8thbO?p=preview](http://plnkr.co/edit/J8thbO?p=preview)
#### Related issues

This maybe related to element transclusion. But I really I don't know. I had tried many things but I can't found a solution. Can anyone have any idea about it? 

Thanks dudes!

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@thiagog3 you may want to compare with the material design decorator instead of the bootstrap one. It will show you which hoops need jumping through to get things to work together perhaps a little clearer. That said it still needs some work to neaten it up further.

**Comment by Anthropic** [comment]
@thiagog3 how is your LumX decorator going? Did you finish it off?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
