### ISSUE TITLE
HTML generator

### ISSUE THREAD

**Issue by thunderer199** [json-schema-form/angular-schema-form#677]
Hello, guys
Are there any possibilities for generating form one time?
There is pretty much overhead for generating form each time
I want that server will response with already generated form

**Comment by Anthropic** [comment]
@thunderer199 yes this is something we are looking at already, at the moment we are re-working the core of the library into a pure javascript core in webpack and which is the json-schema-form-core repository. Once that is completed then it shouldn't be too hard to implement a node server to generate the form. There is plenty of interest in it happening, but as this is a community driven project, timelines are hard to estimate unless someone takes interest in contributing.

Please re-open if you do not feel the question has been answered sufficiently :)
