### ISSUE TITLE
Can anyone explain why my custom validation Plunk is not working?

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#679]
I'm experimenting with using a custom function for validation, making use of the schemaForm.error.* broadcast. For some reason, none of my form fields are being marked as invalid following validation and I can't figure out why. Is anyone able to shed any light please?

#### Plunker
[Custom validation](https://plnkr.co/edit/lGouIF?p=preview)

**Comment by Anthropic** [comment]
@AndrewIsh for custom validation I hook straight into ngModel validation.
Look at https://github.com/Anthropic/angular-schema-form-external-options/blob/master/bootstrap-external-options.js#L187 it may give you some ideas on how to achieve your outcome.

**Comment by Anthropic** [comment]
You can also try looking at the custom validators example in the decorator repo.

**Comment by AndrewIsh** [comment]
Thanks very much @Anthropic, I'll take a look

**Comment by AndrewIsh** [comment]
@Anthropic Hi again. Those both prove extremely helpful, thanks. I've got a slightly different use case and I'm struggling to see how I can apply this technique to it. I was wondering if you might be able to enlighten me.

I'm getting my form definition from an API as a JSON document. I don't particularly want to hold my validator functions in the form definition, since that opens up a man in the middle vulnerability. I'd rather add them once I've got my form definition in my application.

So, I'm getting my form definition via $http, assigning it to a property of my controller, then referencing that property in the sf-form attribute of the <form> element. This works well.

I'm not clear how I can add my $validators to my controls though. I initially thought it would just be a case of something along the lines of:
```
myController.myForm.myControl.ngModel = function(ngModel) {
    ngModel.$validators.myMail = function(values) {
	return values !== 'david.lgj@gmail.com';
    };
}
myController.myForm.myControl.validationMessage: {
    'myMail': "Thats my mail!"
}
```
But when I load the form, I get the following (which suggests to me that Angular knows there's a validator, it just can't access it for some reason):
```
angular-83f99ac….js:12221 TypeError: validator is not a function
    at https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:24706:22
    at forEach (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:350:20)
    at processSyncValidators (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:24705:7)
    at $$runValidators (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:24677:10)
    at Object.ngModelWatch (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:24956:14)
    at Scope.$digest (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:15548:40)
    at Scope.$apply (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:15824:24)
    at done (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:10263:47)
    at completeRequest (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:10435:7)
    at XMLHttpRequest.requestLoaded (https://213.138.111.239:3000/packed/angular-83f99acfa1459b09ffb65652e056b1ec.js:10376:9)
```

I've been fighting with this for a while, can you see what foolish mistake I might be making?

Many thanks in advance! :)

**Comment by Anthropic** [comment]
If you need that level of assistance you need to make a plunker or gist, did you mean for ngModel to be set to a function though?

**Comment by AndrewIsh** [comment]
@Anthropic Good point about the ngModel being set to a function, thanks :) I'll see if I can come up with a Plunker to more clearly illustrate my problem.

**Comment by AndrewIsh** [comment]
I've actually simplified my validation now and moved it into the schema (as simple 'pattern' properties). So I'll close this. Thanks.
