### ISSUE TITLE
Pristine option does nothing

### ISSUE THREAD

**Issue by dorin-niscu** [json-schema-form/angular-schema-form#680]
I tried sf-options="{ pristine: {errors: false, success: false}}".

It comes in scope.options but the options are ignored. It still validates the input no matter if it is pristine or not.

I did a fix but I find it more like a workaround.

\'has-error\': form.disableErrorState !== true && hasError() && **!ngModel.$pristine**, \'has-success\': form.disableSuccessState !== true && hasSuccess() && **!ngModel.$pristine**

**Comment by Anthropic** [comment]
Could you please make a plunker or gist to demonstrate, it would help us a lot?

**Comment by dorin-niscu** [comment]
I added a demo: http://plnkr.co/edit/lYUgSKaW72vCm82G2dg1?p=preview

**Comment by dorin-niscu** [comment]
Removing "|| !scope.ngModel.$isEmpty(scope.ngModel.$modelValue)" will fix the problem without using the global option.

```
scope.hasSuccess = function() { 
	if (!scope.ngModel) { 
		return false; 
	} 
	return scope.ngModel.$valid && 
	(!scope.ngModel.$pristine || !scope.ngModel.$isEmpty(scope.ngModel.$modelValue)); 
}; 
```
