### ISSUE TITLE
Validation immediately upon form load

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#682]
#### Plunker

[Example](https://plnkr.co/edit/KzbiJv?p=preview)
#### Expected behaviour

When the form is loaded it is immediately validated.
#### Actual behaviour

The form is not validated upon load, it is not validated until the model changes and a validation is triggered by the watch on the model.

Are my expectations wrong, I'd have thought that sending the schemaFormValidate broadcast as the final action in the controller would trigger an immediate validation, showing the errors, but that's not the case. Am I doing something wrong?

@json-schema-form/angular-schema-form-lead

**Comment by AndrewIsh** [comment]
Also, as an aside, when the validation does take place, the first array element does not display the validation message

**Comment by Anthropic** [comment]
@AndrewIsh would love to know if anything has changed with the alpha releases regarding this? Probably not, but it would help to know.

**Comment by Anthropic** [comment]
This should be working, so I will close this until I hear otherwise.
