### ISSUE TITLE
Angular-schema-form doesn't work for me

### ISSUE THREAD

**Issue by DianaStockford** [json-schema-form/angular-schema-form#684]
Hello,

I try to use your angular-schema-form. I have created a simple html page using your simple example, but it doesn't work. I get the following error:

[$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=questModule&p1=Erro…

It happens when I use ['schemaForm'] module in angular.module("questModule", ['schemaForm']);

[test_angSchemaForm.zip](https://github.com/json-schema-form/angular-schema-form/files/261136/test_angSchemaForm.zip)

I tried to use different examples with angular-schema-form but they don't work also.
Could you please help me?

The html page and js file please see in attachment.

Regards,
Diana

**Comment by Anthropic** [comment]
@DianaStockford can you make a plunker please? It helps us to support you, I am at home on mobile so I can't open zips.

That error is usually relating to the order the files are added in an angular app. But we can know better with a plunker.

**Comment by DianaStockford** [comment]
Hi,

I have created an example on Plunker. It doesn't work also. Please see the link below

https://plnkr.co/edit/U5GeUXCoHr1GYaA7fYXU?p=preview

I'm not sure that I made all correct...

Regards,
Diana

**Comment by Anthropic** [comment]
@DianaStockford try using the release version, it's currently using development branch which is undergoing a lot of change at the moment.

**Comment by Anthropic** [comment]
@DianaStockford did you sort out the issue?

I'm doing housekeeping, so I will close this as it has been a while, if you still have an issue please re-open and let me know.
