### ISSUE TITLE
model is not updated correctly when non-conditional fields are falsey

### ISSUE THREAD

**Issue by donalmurtagh** [json-schema-form/angular-schema-form#685]
In [this Plunker demo](http://plnkr.co/edit/CSd5tT?p=preview) I've defined a form with 3 fields, 2 of which depend on the other field.

``` javascript
  $scope.form = [{
      type: 'section',
      "condition": "model.toggle === 'yes'",
      items: [{
        key: "deleted",
      }]
    }, {
      "key": "retained",
      "condition": "model.toggle === 'yes'"
    }, {
      "key": "toggle",
    }
  ];
```
#### Expected behaviour

If the value of the `toggle` field is not `'yes'`, the model value of `deleted` and `retained` should both be deleted because they both use the default `destroyStrategy = 'remove'`.
#### Actual behaviour

Although both form fields are hidden when `toggle !== 'yes'` only the model value of `deleted` is removed. You can verify this via the "Log model to console" button
#### Gist/Plunker/Demo

http://plnkr.co/edit/CSd5tT?p=preview

**Comment by donalmurtagh** [comment]
I might have some time to investigate this today, but before I do, I'd like to understand the expected behaviour of nested conditions. For example, given the following form definition

````javascript
  var form = [
    {
      type: "section",
      condition: "model.page === 1",
      destroyStrategy: "retain",
      items: [
        {
          key: "nested",
          condition: "model.foo",
          destroyStrategy: "remove"
        }
      ]
    }
  ];
````
The first question is whether or not such nesting is supported, i.e. if `model.page !== 1` will all fields in `items` be retained in the model, regardless of whether they declare their own conditions? If the answer to that question is "yes" then it seems nested conditions are not supported. 

IMO, the most useful behaviour is that the *closest* condition to a field in the hierarchy governs how that field is handled. For example

- model: `{model.page: 1, model.foo: false}` => `nested` field is hidden and model value is removed
- model: `{model.page: 2, model.foo: true}` => `nested` field is hidden (because the `items` condition is false), but the model value is retained
- model: `{model.page: 2, model.foo: false}` => `nested` field is hidden (because the `items` condition is false), but the model value is removed

**Comment by Anthropic** [comment]
Your assumptions would match my own :)

**Comment by Anthropic** [comment]
It should work, but it may not, we probably need test cases to match those scenarios to build against.

**Comment by donalmurtagh** [comment]
My (manual) testing indicates that it does not currently work as described above. The ASF docs are fairly silent on the subject of the behaviour of nested conditions.

**Comment by Anthropic** [comment]
The original post issue should be fixed now. The destroy strategy means when the display item is destroyed, so if the parent is destroyed the children are too.

Closing as I don't think there's anything left to do, please re-open if you have something to add or create a new issue for any related suggestions.
