### ISSUE TITLE
$ref

### ISSUE THREAD

**Issue by example2049** [json-schema-form/angular-schema-form#687]
Hi guys

Do you have a simple example of the use of $ref with Angular-Schema-Form? The example in https://github.com/json-schema-form/angular-schema-form/issues/69 is not clear and I don't understand if  you provide support for it.

Thanks for all

**Comment by Anthropic** [comment]
@example2049 it isn't supported yet, it is planned, but no timeline has been determined, I'd follow #69  to get notified of updates. We are closer to being ready to start implementing it, but other than that only using the example provided in that ticket would be my only suggestion prior to me actually trying to build it.

**Comment by Anthropic** [comment]
As of 1.0.0-alpha.2 $ref is supported as a preprocessing step.
