### ISSUE TITLE
Changing form's readonly property has no effect

### ISSUE THREAD

**Issue by AndrewIsh** [json-schema-form/angular-schema-form#688]
#### Plunker
[Example](https://plnkr.co/edit/ijhY8C?p=preview)

#### Expected behaviour
Toggling `sfOptions.formDefaults.readonly` should toggle the form's readonly appearance in the view

#### Actual behaviour
Toggling `sfOptions.formDefaults.readonly` appears to make no difference at all to the form's appearance

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@AndrewIsh the field you are trying to change is a default, not the actual value, so it which would only be used when the form is first created, you would need to drop the form and create again to change that value.

I reload the schema with readonly changed at the root level for my work.

**Comment by AndrewIsh** [comment]
@Anthropic Many thanks for that, that makes sense.

> I reload the schema with readonly changed at the root level for my work.

Could you please elaborate on this? You say you change it at root level, do you mean at the root level of the form? i.e. `$scope.myForm.readonly = true;`?

**Comment by Anthropic** [comment]
@AndrewIsh I process it server side, so the parent object of the schema gets tagged readonly {readonly: true, [normal object params]}, without looking into it I believe the form only updates if the root object is replaced, it doesn't watch deeply into the object once the form is made, again that's what I think without looking into it.

**Comment by raoulus** [comment]
It would be great if parts of the form could be updated/refreshed without re-rendering the whole thing. I also would like to change the readonly flag in runtime. When you update a big form the page jumps and it flickers for a second.

**Comment by AndrewIsh** [comment]
@Anthropic Interesting. For my particular use case, I'm only going to be setting readonly before the form is created anyway, so this will work fine for me. But I think @raoulus has a point, re-rendering the whole form when the readonly property changes feels a bit heavy handed, but I can see why it is the way it is.

**Comment by Anthropic** [comment]
@AndrewIsh updating parts of the form is something we want, just a matter of resources to change it.

@raoulus we agree, there is a plan to allow a locals scope to be passed in and watched, it could be added to conditionals. But it requires work so I don't know the timeline.

**Comment by Anthropic** [comment]
Feel free to re-open if you have more to add on this topic :)
