### ISSUE TITLE
Support for autocomplete 

### ISSUE THREAD

**Issue by rnjailamba** [json-schema-form/angular-schema-form#692]
#### Enhancement
As a user/developer, i would like autocomplete extension to this library.

**Comment by Anthropic** [comment]
@rnjailamba this could be done as an add-on, I have implemented something like this in the Material decorator but that isn't really production ready, but you could certainly take a look and see if you can make an add-on from it.

**Comment by rnjailamba** [comment]
Great ill have a look at it.

**Comment by poornerd** [comment]
@rnjailamba did you ever implement the autocomplete?  I need autocomplete as well....

**Comment by rnjailamba** [comment]
@poornerd  Hi there is an autocomplete example here https://github.com/json-schema-form/angular-schema-form-material/blob/develop/examples/material-example.html

**Comment by devendrainfotech** [comment]
Hey, I am not able to find the autocomplete example from the above link. can you care to share again.

**Comment by rnjailamba** [comment]
@devendrainfotech  please check the examples here - https://github.com/json-schema-form/angular-schema-form-material
