### ISSUE TITLE
What mechanism should I use to place all the error messages into a single error box within the form?

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [json-schema-form/angular-schema-form#693]
#### Question / Enhancement 
As a user/developer, when I use angular-schema-form I want a mechanism to place all the error messages into a single error box within the form.

See [this plunker](http://plnkr.co/edit/nOjrSupkVf4L4VuhvxVO?p=preview) for an example; you can move the HTML including the _dl-error-box-container_ directive anywhere in the form.

**Comment by Anthropic** [comment]
@dematic-rodrigo-silveira I am trying to find time to look at this for you, I probably wont get a chance until the weekend though unfortunately.

**Comment by Anthropic** [comment]
Just a thought, have you tried looking through the error object ngcontroller adds to the form?
```html
<ul>
  <li ng-repeat="(key, errors) in form.$error track by $index"> <strong>{{ key }}</strong> errors
    <ul>
      <li ng-repeat="e in errors">{{ e.$name }} has an error: <strong>{{ key }}</strong>.</li>
    </ul>
  </li>
</ul>
```

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
