### ISSUE TITLE
Is there a mechanim to to use the AngularJS ng-plurarity directive

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [json-schema-form/angular-schema-form#696]
#### Question / Enhancement 
As a user/developer, when I use angular-schema-form I want a mechanism to use the AngularJS +ng-plurarity+ directive to use the proper sentences with regard to count and gender.

See [this plunker](http://plnkr.co/edit/nOjrSupkVf4L4VuhvxVO?p=preview) for an example. As you will see, the +minlength+ and +maxlength+ validation messages are wrapped up on templates encapsulating the _ng-plurarity_ directive

**Comment by Anthropic** [comment]
@dematic-rodrigo-silveira you can create your own decorator easily and modify to do what you like. Take a look at the extension framework in the documentation.

**Comment by Anthropic** [comment]
As mentioned in your other post you can use the new builder to add the value to the source template as required prior to it being added to the form.

Please re-open if you do not feel the question has been answered sufficiently..
