### ISSUE TITLE
Not shown select in an array 

### ISSUE THREAD

**Issue by lollocavs** [json-schema-form/angular-schema-form#698]
I try to implement a multi array form with same select item.  The schema snippet is as follow:
`"technical": {"type": "array", "title": "Technical", "x-schema-form": {"htmlClass": "col-md-4 col-lg-4"},
			"items": {
				"type": "object",
				"properties": {
					"techName": {
						"type": "select",
						"title": "Name",
						"required": true,
						"titleMap": "$scope.Specifications"
					},
					"techValue": {
						"type": "string",
						"title": "Value"
					}
				}
			}
		},`
where `$scope.Specifications` is an array of key/value objects. 
While the form array is:

`{  
         "type":"fieldset",
         "title":"Specifications",
         "items":[  
            "technical", // ...more arrays
         ]
      },`

And the result is:
<img width="319" alt="schermata 2016-05-21 alle 10 58 39" src="https://cloud.githubusercontent.com/assets/3180432/15447450/0b16e0ae-1f43-11e6-87bb-b8c7c9cd7a91.png">

What is the problem? I try to find the solution in the documentation, but I can't.

Thanks in advance.

**Comment by Anthropic** [comment]
@lollocavs you can try one of the add-ons for dynamic selects, there are two of them at least and they can load their titleMaps. Thing is titleMap is part of our form definition, it is not part of json-schema so it cannot be in the schema snippet anyway. You must load it as part of the form definition.

Please re-open if you do not feel the question has been answered sufficiently.
