### ISSUE TITLE
Remove bootstrap-decorator.js from bower main section

### ISSUE THREAD

**Issue by LeonardoGentile** [json-schema-form/angular-schema-form#699]
On my project dev workflow I'm using [main-bower-files](https://github.com/ck86/main-bower-files) and gulp to inject the scripts exported by the `main` section of my installed bower_components.

As suggested on the [docs](https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#important) I did not rely on the bootstrap-decorator shipped with this project but I've installed it as a separate dependencies with `bower install angular-schema-form-bootstrap`. Its main bower section is:

```
"main": "bootstrap-decorator.min.js",
```

The problem is that you are still including the bootstrap-decorator into this project (as you suggested you shouldn't) and also you export it in the main section of the bower file: 

```
"main": [
    "dist/schema-form.js",
    "dist/bootstrap-decorator.js"
  ],
```

By having 2 bootstrap-decorators in my index.html led to have duplicates custom add-on and I had a really hard time figuring out what was really going on. 

I think you should completely decouple the bootstrap-decorator from the project or at least remove it from bower. I'm not sure if it was by choice or you just forgot it, in any case I can provide a PR if you agree.

On a side note the [bower specs](https://github.com/bower/spec/blob/master/json.md#main) recommends 

> Only one file per filetype [...] Do not include minified files.

So maybe you should export the non-minified file in main section of the `bootstrap-decorator` project and if you need more than one js file maybe it should be a dependency

**Comment by Anthropic** [comment]
This is updated in the Alpha releases, they will be pushed to bower as part of v1.0.0
