### ISSUE TITLE
date support

### ISSUE THREAD

**Issue by iivvoo** [json-schema-form/angular-schema-form#7]
What are the current plans for supporting date (and time) entry? I've noticed there's a "feature/datepicker" branch - is this still being managed? It seems to lag a bit behind master.

I might consider working on this myself. If so, would the feature/datepicker branch be a good start, or should I start from scratch?

**Comment by ravivit9** [comment]
Hi Iivo, Do you have an example (JSON schema & form) for the date picker implementation?

**Comment by davidlgj** [comment]
@ravivit9 it is used in the demo, http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html, select "kitchen sink" :-)
