### ISSUE TITLE
Weird behavior of 'condition' option with negative conditions

### ISSUE THREAD

**Issue by warmy1004** [json-schema-form/angular-schema-form#702]
#### Enhancement
I used two more negative conditions ( such as condition:"model.mainQuestion2 !== 'a' || model.mainQuestion2 !== 'd'", ) to show and hide a conditional question. 

#### Expected behaviour
I expected the conditional question will not show when 'a' or 'd' is displayed. 

#### Actual behaviour
It actually the conditional question didn't hide. 

#### Gist/Plunker/Demo
https://plnkr.co/edit/aNjJd6WjfWUGwDx4bydm?p=preview

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@warmy1004 use && not || when using negatives.
