### ISSUE TITLE
DestroyStrategy option is not working properly

### ISSUE THREAD

**Issue by warmy1004** [json-schema-form/angular-schema-form#703]
#### Enhancement

In my case, three conditional questions (text, select, and radios-inline types) are showing and hiding based on the main question's value. Any previously entered input for these conditional questions should be removed or set to be empty when these conditional questions are removed. But, destroyStrategy for them is not working properly. 
#### Expected behaviour

I expected the previously entered data for conditional questions will be removed (which is default) for text and radios-inline types and set to be empty for the select type when form elements are disappeared from the screen.
#### Actual behaviour

If valid data is entered, the data is always retained (it is not removed or set to be empty). However, if invalid data is entered, this invalid data is cleaned up (removed) when the form element is removed from the screen. 
For valid data, $destroy event seems to be not calling properly.
#### Gist/Plunker/Demo

https://plnkr.co/edit/rYuk0YmBDN3k3sTJusAy?p=preview
#### Related issues

This is/maybe related to ...#689

@json-schema-form/angular-schema-form-lead

**Comment by warmy1004** [comment]
For your information, here is version information which I am using in Plunker.
angularjs & angular-sanitize : v 1.4.3
schema-form : v 0.8.13
bootstrap-decorator.js : v 0.8.13 which is provided in the schema-form-v.0.8.13 folder
ObjectPath: v 1.2.1
tv4: v 1.0.17

**Comment by Anthropic** [comment]
@warmy1004 thanks for the additional info, once the webpack/babel branch is stabilised we will be able to look at this.

**Comment by warmy1004** [comment]
I want to share with you what I found for this issue. 
I can't be fully sure, but I think this issue is caused by a mismatch between actual form's structure from a canonical form definition and a needed structure for angularjs's destroy event. 
When the angularjs is broadcasting destroy event based (the current angularjs's code is _this.$broadcast('$destroy');_ ), this broadcast destroy event can't be caught properly by schema-form because '_this_' doesn't have a form information. Instead, this.$parent has this form information, so if I change the above angularjs's destroy code to '_this.$parent.$broadcast('$destroy');'_ destroyStrategy is working for me. 
Hopefully, it will help you to solve this issue.

**Comment by Anthropic** [comment]
@warmy1004 thanks for the info, I appreciate your follow up, once the webpack/babel branch is merged to dev, hopefully someone can do a PR to correct the behaviour or add a test case for me to fix against.

**Comment by Anthropic** [comment]
@warmy1004 how does this one look on the latest dist folder files in dev branch? Are you able to confirm it is working again after all the changes I made to fix destroy behaviour?

**Comment by warmy1004** [comment]
@Anthropic I retested it and this is fixed in the alpha 4 version. Thank you.

**Comment by Anthropic** [comment]
Woo hoooo!
