### ISSUE TITLE
Set array items as select options

### ISSUE THREAD

**Issue by snoosmoomrik** [json-schema-form/angular-schema-form#706]
I have this schema:
```
{
  "type": "object",
  "properties": {
    "list": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "number"
          }
        }
      }
    },
    "select": {
      "type": "string"
    }
  }
};
```

And this form definition:
```
["list", {
  "key": "select",
  "type": "select",
  "titleMap": {"1": "item 1", "2": "item 2"} // TODO: Get actual list items' name props instead of this hardcode
}];

```
Is it possible to show all list items names in select box?
Maybe my situation has a simple solution but I can't find it anywhere.

[plunker](https://plnkr.co/edit/OclcXl6V5fcAoMFWKq3z?p=preview)

**Comment by kyse** [comment]
Grab a dynamic/external select add-on that allows you to cusotmize the titleMap input, and for the titleMap sourrce method, target the list.  I use ui-select for my custom select which has a "refresh" option.  It essentially targets my api when it needs an updated source.  You could probably direct the refresh method to target the list array instead.  Could possibly extend/decorate ui-select to add a watcher to the array and update the titleMap if needed.  I'd be surprised if that functionality didn't already exist in some add-on already however.

**Comment by Anthropic** [comment]
@snoosmoomrik not sure why the titleMap isn't in the correct format?
```json
[
  {"name": "item 1", "value":1},
  {"name": "item 2", "value":2}
]
```
https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#select-and-checkboxes

**Comment by snoosmoomrik** [comment]
@Anthropic this format is correct and it works. The problem is that in my case I need to track changes in `list` array and update this ittleMap dynamicly according to list items. I'm using angular's $watch for now to do this but I wonder, is there any other way to declare this behavior in schema or form? Here is my last approach: [plunker](https://plnkr.co/edit/OclcXl6V5fcAoMFWKq3z?p=preview)
@kyse thanks. I'll try to find something suitable.

**Comment by Anthropic** [comment]
@snoosmoomrik ha learn something new every day, I didn't even know we supported that format, now I have to update some code to support it in the Material decorator, oh dear...

So this will work with the Material decorator select in theory, I haven't tested it, but it is capable of watching an object and updating from it. External-Options add-on can also do it but not sure if it would need some tweaking to work correctly, I suspect so. Both of those allow defining the source of a drop down as a local object, which could be your model's data in theory. But I never actually built them to support object properties only the list format with name/value/group. But you could certainly look at the external-options add-on and try to make it work for your case.

**Comment by kyse** [comment]
Wouldn't the refresh option on ui-select-choices give you an updated list when you need?  Perhaps that only updates if you do searches.

**Comment by snoosmoomrik** [comment]
This can help. Thank you.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
