### ISSUE TITLE
Dynamically extending schema

### ISSUE THREAD

**Issue by slyadams** [json-schema-form/angular-schema-form#710]
I'm looking at integrating asf with an existing system which consists of around 400 object types in our back-end, which is exposed through a RESTful webservice which supports an OPTIONS call to get the 'schema' of each object type. I've written a shim to convert the OPTIONS output into an asf schema. So far so good and I'm very impressed with the framework.

One of the big issues with our existing form system is performance, most notably because many of our objects have 'child' objects, and those children might also have children! :-)

An example I use is if there was:

1. A Country object
1. A City object (child of Country)
1. A District object (child of City)
1. An Official object (child of District, and possibly others)

We would typically present this as a single form with a tabbed layout to make it easy to use. I can get this working fine, but am concerned in the real system where some objects have up to 15 nested children types, the overhead of the additional OPTION and GET calls will drive performance down.

One way we're looking at addressing this is to only render the 'core' part of the form and then load more schema as the user requires it, for example if a user clicks on a tab (or checks a checkbox etc.), the OPTIONS for the object types required in that tab/section are loaded and the form redrawn.

Would appreciate any thoughts the experts would have on this,

Many thanks in advance!

**Comment by Anthropic** [comment]
@slyadams best way to think of it I would suggest is that an add-on is simply an angular template you are choosing to have in a position in your form based on schema, it is conceivable that you could create an add on template that has its own schema-form in the child template, that schema form could be generated from loaded data in the same way I load titlemaps and add options in my external-options add-on's template. It could have its own model or extend the model of the root schema based on directive logic added to the template.

**Comment by slyadams** [comment]
So basically the overall schema-form would be made up of multiple smaller schema-forms?

**Comment by Anthropic** [comment]
Yes, that's how I would imagine it working, you can do quite a lot with the builder, ie. if there is a link item in the schema defining the new schema url, then you can have a builder append another node to the template output to be added to the page, which would then load a directive to handle the load and display.

**Comment by Anthropic** [comment]
take a look at the Material design decorator, it is more up to date than the bootstrap one and may give you a better look at what you can do with the builder.

**Comment by slyadams** [comment]
When you say 'link item', you mean just adding a new custom key?

**Comment by Anthropic** [comment]
In json-schema's hypermedia schema there is a link item to define a url, if you look at the external-options add-on you can see how it can be used.

**Comment by nicklasb** [comment]
Actually I made an add-on that has as one of its features that it loads another schema.
https://github.com/OptimalBPM/angular-schema-form-complex-ui

An important think to remember is that you cannot nest the `<form>`-tag, so use divs instead.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently :)
