### ISSUE TITLE
Validation of type 'object' in a new addon

### ISSUE THREAD

**Issue by ymarcon** [json-schema-form/angular-schema-form#711]
Hi

I am currently developing a new add-on called [sf-localized-string](https://github.com/obiba/sf-localized-string) that allows to capture a "value" in different languages. Then instead of a simple 'string' field, the value is an 'object' with a property for each declared language.

I am trying to validate the value as follow: if at least one text is provided, texts for the other languages must be provided too; for instance when there is a text in English, there must be a text in French. To achieve that I have defined in my add-on a specific $validators function to the field form.

#### Expected behaviour
I expected that the $validators would be called whenever the value of type 'object' is modified (=the value of one of its property has changed).

#### Actual behaviour
The $validators is called when a new 'object' value is assigned, showing the validation error status for the field. But the validation status is not updated after entering a text for another language.

#### Plunker
You can see it in action in this [plunker: xUAqgTIfezw21cZoZMiY](https://plnkr.co/edit/xUAqgTIfezw21cZoZMiY?p=preview).

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Not sure if it will help, but take a look at this https://github.com/Anthropic/angular-schema-form-external-options/blob/master/src/angular-external-options.js#L185 I had to disable validation for items within the object and then validate independently. You would also need to make sure the object item is in the form definition as a section or there is nothing attaching it to the model directly I suspect.

**Comment by kazoompa** [comment]
@Anthropic, by validate independently you mean each object field has to have its own validator? Could elaborate a little more?

Thanks.

**Comment by Anthropic** [comment]
@kazoompa no I mean I validate the whole object and disabled validation on the child fields. That way tv4 can determine if the whole group is valid rather than the fields independently.

I created a directive for a class I added to a section, which attached the validation for the object.

**Comment by ymarcon** [comment]
@Anthropic Thanks to your comment I have added a [controller](https://github.com/obiba/sf-localized-string/blob/master/src/module.js#L46-L61) that is deep-watching the model value and triggers the object validation. It works but I still would have expected the schemaform framework to do it automatically.

**Comment by Anthropic** [comment]
@ymarcon the use of oneOf manyOf is on the roadmap of desired features, it is just tricky to quantify the desired outcome precisely and we don't have a finalised timeframe given most of the work really needs to be done by PRs.
