### ISSUE TITLE
Need help with array validation?

### ISSUE THREAD

**Issue by anushkamahesh** [json-schema-form/angular-schema-form#716]
##### Expected behaviour
When you type only the validation should work on the input field.

##### Actual behaviour 
Below is the code i used to create a array of input with button. It always show **Required** message at the bottom and  show **Required** in the input even. 
```javascript
form= [
   {
       'type': 'help',
       'helpvalue': '<p>Click New List to add new List</p>'
  }, {
       'key': 'data',
       'add': 'New',
       'feedback': "{ 'glyphicon': false, 'glyphicon-asterisk': form.required && !hasSuccess() && !hasError() ,'glyphicon-ok': hasSuccess(), 'glyphicon-remove': hasError() }",
        'style': {
             'add': 'btn-success'
         },
         'items': [
             'data[].name', {
                  'type': 'button',
                   'style': 'btn-success',
                    'title': 'Save',
                     'onClick': 'saveItem()'
                }
           ],
          'startEmpty': true
      }
]
```
```javascript
schema= {
  'type': 'object',
  'title': 'Comment',
   'properties': {
        'data': {
             'type': 'array',
             'maxItems': 1,
              'items': {
                    'type': 'object',
                     'properties': {
                          'name': {
                               'title': 'Name',
                               'type': 'string'
                            }
                        },
                        'required': ['name']
                     }
                 }
          }
     }
```

Below image shows my issue

![Required message issue](https://cloud.githubusercontent.com/assets/1327120/16081160/f95719ce-3329-11e6-94e2-8144fdce0daf.png)

**Comment by Anthropic** [comment]
@anushkamahesh in the documentation look for validateOnRender under global options. You need to set it to false if you want to avoid the default behaviour.

Please use gist to provide schema/form code examples it is much easier to help, in this case I already knew the answer, but for most things it really helps.

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by anushkamahesh** [comment]
it says **validateOnRender	boolean	Should form be validated on initial render? Default false**
Check this one `https://embed.plnkr.co/NT6cvVybfuZnFIhgU1Xm/, Close the current one exist on the view. Then you can see the issue

**Comment by Anthropic** [comment]
@anushkamahesh ok I think I understand what your issue is now thanks for the plunker.

You have set both the comments array as required and the field as required which is why the word required would appear, are they not supposed to be required? If you want a clearer message then you can set validationMessage on the form definition for both array and field to override.

Setting minItems as well as maxItems will also provide better messages at the array level.
