### ISSUE TITLE
Confusion about enum and titleMap in select

### ISSUE THREAD

**Issue by HeerRik** [json-schema-form/angular-schema-form#717]
#### Problem
So I'm getting to understand this great library, though I am still running into some troubles using the `select` field.
#### Expected behaviour
Reading through the documentation and checking the code
``` javascript
if (stripNullType(schema.type) === 'string' && schema['enum'])
```
It is clear that I am required to use an `enum`, which requires some data.
Now there is also this part:
``` javascript
if (!f.titleMap) {
        f.titleMap = enumToTitleMap(schema['enum']);
}
```
Suggesting that a titleMap can be used, and when it does not exist, enum will become titleMap.
But since enum appears not to handle value:key objects, and only values, the incorrect value will be assigned to the model

If someone could please provide a code example for a select box using enum and titlemap I would be forever grateful.

Cheers

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@HeerRik there's a bunch of titleMap examples in the demo page: http://schemaform.io/examples/bootstrap-example.html

The schema is based on json-schema, that does not support titleMap as it is a data model definition syntax only. The form definition is where you can apply a titleMap. The schema enum must contain valid VALUES only, not keys.

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by HeerRik** [comment]
First off, thanks for your reply
So if I create a string type with an enum in the schema, and then a select type with the titleMap in the form defenition, they should work together right? Right now I for some reason get a select box and a string box under 1 title. Do you need a fiddle or something to see or do you happen to know the problem?

**Comment by Anthropic** [comment]
@HeerRik yes I would need a gist, I suggest using the titleMap demo to replicate what you are trying to do and save to gist and then post that and re-open :)

**Comment by yuvi116** [comment]
@Anthropic , Can we reset the selected titleMap value based on some condition ?
