### ISSUE TITLE
postProcess Examples

### ISSUE THREAD

**Issue by dkengaroo** [json-schema-form/angular-schema-form#72]
Hiya,

I was wondering if you could provide me some more examples with the postProcess function.
For example: 
I used "*" in the form. However, now I want to hide some properties. 
schemaFormProvider.postProcess(function(form){
       //what do I do with form here
        return form;
    })

Other than reverse() what are some 1 line examples that I could do in the postProcess?

Thanks!

**Comment by subhendupsingh** [comment]
I have done some changes to the form in postprocess function but they are not reflecting. 

.config(function(schemaFormProvider){

        schemaFormProvider.postProcess(function(form){
           for(var i=0;i<form.length;i++){
                if(form[i].schema.title=="Currency"){
                    form[i].schema.title="Subhendu";
                    break;
                 //   form[i].schema.enum=['INR','KES'];
                }
            }
            console.log(form);
            return form;
        })

    });
