### ISSUE TITLE
Fill a form from a json

### ISSUE THREAD

**Issue by galtet** [json-schema-form/angular-schema-form#720]
#### Question
I would like an option to fill a form from a json - i didn't find an option to do so, and i think it would be a good idea to support this option.
Is this option exists ? or am i missing something ?

**Comment by Anthropic** [comment]
@galtet can you elaborate? Do you mean set the default data from json? You can certainly set your model to be data from a JSON file on load if you wish. Just read it in from your filesystem and then set the model.

Please re-open if I haven't answered your request and you can provide more info so the question can been answered sufficiently.

**Comment by galtet** [comment]
what i mean is - to be able to load the schema from a jsonschema, and to load the data on the fields from another json. I didnt find it in the the documentation.

**Comment by Anthropic** [comment]
Do you mean select lists? If so then there are a few add-ons already made for doing that and the Material design decorator does it (but still needs work).
