### ISSUE TITLE
titleMap with tabs not working and could not able to find example with titleMap with tabs

### ISSUE THREAD

**Issue by harshdoshi999** [json-schema-form/angular-schema-form#721]
I am trying to use titleMap with tabs but can not able to do it. it throws js error.

**TypeError: Cannot read property 'key' of null
    at {{sitename}}/angular-schema-form/dist/schema-form.js:1334:16**

I am also not able to find the suitable demo for this over internet.

**Comment by Anthropic** [comment]
The error indicates that you have not set a valid form definition, what is your form and schema?

Not sure what you mean by titleMap with tabs, you mean titleMap on a select inside tabs?
