### ISSUE TITLE
Using the "boolean" schema type results into "$sce:unsafe" error

### ISSUE THREAD

**Issue by laura-h** [json-schema-form/angular-schema-form#724]
#### Enhancement
I am  using the angular-schema-form together with ng6-starter. 

I'm trying to create a checkbox using the "boolean" schema type. Here is how I do it: 

```
var schema = {
  "type": "object",
  "properties": {
   ...
    "terms_and_cond": { 
            "type": "boolean", 
            "title": "I accept the terms & conditions" 
     }
  }
}

var form = [
  ...
 {
      "type": "fieldset",
      "items": [
        "terms_and_cond"
      ]
    }
]
```

#### Expected behaviour
I expected the checkbox to be rendered. 

#### Actual behaviour
I'm getting this error: "Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context."

@json-schema-form/angular-schema-form-lead

**Comment by laura-h** [comment]
Never mind. I just needed to add the "angular-sanitize" module. I'm pretty new at Angular. Was sure I was doing a newbie mistake :)

**Comment by legend80s** [comment]
+1 angular-sanitize
