### ISSUE TITLE
Problems creating an addon with script tags in template

### ISSUE THREAD

**Issue by loopyluke** [json-schema-form/angular-schema-form#728]
As the title says I'm having a problem creating an add-on that uses a script tag in the template. 

This is my ol3-map.js where the addon is defined:
```
angular.module('ol3-map', ['schemaForm']).config(['schemaFormProvider', 'schemaFormDecoratorsProvider', 'sfBuilderProvider', 'sfPathProvider',
  function(schemaFormProvider, schemaFormDecoratorsProvider, sfBuilderProvider, sfPathProvider) {
  schemaFormDecoratorsProvider.defineAddOn(
    'bootstrapDecorator',         // Name of the decorator you want to add to.
    'ol3map',                     // Form type that should render this add-on
    'directives/decorators/bootstrap/ol3-map/ol3-map.html',    // Template name in $templateCache
    sfBuilderProvider.stdBuilders // List of builder functions to apply.
  );
}]);
```

And the ol3-map.html template:
```
<div class="form-group" sf-field-model ng-class="{'has-error': hasError()}">
  <label class="control-label {{form.labelHtmlClass}}" ng-class="{'sr-only': !showTitle()}" for="{{form.key.slice(-1)[0]}}">{{form.title}}</label>
  <div ng-init="">

    <div id="map" class="map" style="width: 100%; height: 100%"></div>

    <script type="text/javascript">
      var raster = new ol.layer.Tile({
        source: new ol.source.MapQuest({layer: 'sat'})
      });

      var map = new ol.Map({
        layers: [raster],
        target: 'map',
        view: new ol.View({
          center: [-11000000, 4600000],
          zoom: 4
        })
      });

   // Trimmed more OpenLayers setup stuff...

    </script>
</div>
  <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
</div>

```

With the two files as above, the map fails to load due to the script not being executed, though the tag and its contents exist in the DOM. However if I replace the `schemaFormDecoratorsProvider.defineAddOn` method in ol3-map.js with:
```
schemaFormDecoratorsProvider.addMapping('bootstrapDecorator', 'ol3map',
  'directives/decorators/bootstrap/ol3-map/ol3-map.html');
```
The JS loads and the map displays properly. I'm currently using a local copy of http://schemaform.io/examples/bootstrap-example.html to test components, in case there's something that page is doing that I am unaware of.

Looking through the source for angular-schema-form it appears the only difference between defineAddon and addMapping is that defineAddon forces `replace: true`, though I can't figure out why that would cause the problem. Should I just use addMapping instead, even if it is deprecated? Any help or suggestions on going about this would be appreciated.

**Comment by Anthropic** [comment]
If you change the replace: true in the source of the page you are testing with does it then work for you?

**Comment by Anthropic** [comment]
Can you make a plunker?

**Comment by loopyluke** [comment]
I think it's all sorted now, solved my problem by creating an angular directive in ol3-map.js and linking it to a div in the ol3-map.html template.
