### ISSUE TITLE
When changing a field, update other fields

### ISSUE THREAD

**Issue by laura-h** [json-schema-form/angular-schema-form#733]
I am working on an app that at some point shows a user's location on a map. 
It should go like this: 
- the user enters his zipcode
- the app sends a google geocoder api request and brings back the city, state and neighborhood. This will later be changed to another service, but this is just for testing
- with these values I want to populate some fields (city, state and neighborhood)

Currently, I am doing this using jQuery:

```
this.onZipChange = (modelValue, form) => {
            let address = {
                address: modelValue + ', Mexico'
            };

            this.geoCodeSubmit(address, (action, state, res) => {
                const contentType = res.headers.get('Content-Type');
                if (contentType && ~contentType.indexOf('json')) {
                    return res.json().then((json) => {
                        let address = json[0];
                        if (address.city) {
                            $('#city').val(address.city);
                        }
                        if (address.extra.neighborhood) {
                            $('#colonia').val(address.extra.neighborhood);
                        }
                        if (address.country) {
                            $('#state').val(address.country);
                        }
                    });
                }
            });
        };
```

But this way, the fields are not validated instantly. Is there any way to do this without using jQuery?

**Comment by Anthropic** [comment]
@laura-h Is there a reason you don't just update the model directly as the data returns?

**Comment by laura-h** [comment]
@Anthropic because I always tend to not see the obvious solution :) Thank you.

But now I am facing another issue. I turned the `neighborhood` field into a `select`, which should be empty at first, until the user enters a zipcode. Do you know know how I can add options to the select dynamically?  Should I open a separate ticket for this question?

**Comment by Anthropic** [comment]
@laura-h there are a few add-ons designed for handling this, angular-schema-form-external-options angular-schema-form-dynamic-select the later is better supported, the Material design decorator has it built in but only very basicly.

Please re-open if you do not feel the question has been answered sufficiently :)
