### ISSUE TITLE
Is there any way to use regular expression with a modifier in schema.pattern?

### ISSUE THREAD

**Issue by warmy1004** [json-schema-form/angular-schema-form#735]
#### Enhancement

I want to make a pattern to ignore case by adding a flag 'i' within schema.pattern property. 
The current tv4 is just using a regular constructor as _var regexp = new RegExp(schema.pattern);_  and there is no option to add any specific flag (like i for ignoring case) for constructing a regular expression from a received pattern. So, I don't know how I can make a case-insensitive pattern in schema property. 
Is there any recommended way for a case-insensitive pattern?
#### Expected behaviour

I expected I can use a regular expression for allowing a case-insensitive one as well.
#### Actual behaviour

It is actually not working and I can't find a way for this case without changing tv4.js/schema-form.js code directly.
#### Gist/Plunker/Demo

https://plnkr.co/edit/gfD2sFxBASf4HdSYJlbG?p=preview
#### Related issues

This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Hey @warmy1004 the pattern behaviour is part of JSON-schema definition and not this library, so short answer is not until they change it. I do recommend adding an issue in the schema-form-spec repo and push them to think about a solution, now draft 6 is out they are more likely to have some time for that sort of consideration. That said I haven't even checked if this changed at all already. Anyway I am closing this issue as it isn't something I would do without it being changed there first. I am hoping to make it possible to use alternate validators which would hopefully sort it out in future anyway :)
