### ISSUE TITLE
Default value not updated when using condition

### ISSUE THREAD

**Issue by MGouaillier** [json-schema-form/angular-schema-form#740]
Hello, i noticed a bug when using angular schema form,

When using a condition, the default value of the key is not applied to the field.
If you try checking the box, you'll see the value is updated but if you click it again, the default value isn't displayed.

Also, you will notice both values are in the model at te beginning of the example, which is a problem

See example here : 

http://schemaform.io/examples/bootstrap-example.html#/55b1f6aa01e2fb19466c10b0d31edff3

Is this problem fixable by using a hack or something ?

**Comment by Anthropic** [comment]
@MGouaillier try setting your destroyStrategy
https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#destroystrategy

**Comment by MGouaillier** [comment]
Thank you so much, it worked perfectly fine

**Comment by Anthropic** [comment]
@MGouaillier thank you for updating the issue with your outcome :)
