### ISSUE TITLE
Hidden field in form

### ISSUE THREAD

**Issue by jeremysolarz** [json-schema-form/angular-schema-form#75]
Angular schema form seems like a pretty nice tool to use.

One thing I couldn't find is how to render hidden fields with it.

Do you currently support hidden fields (for e.g. ID field)

**Comment by vamsi12345** [comment]
Hi, I just started using the Angular schema from in my custom directive,
I have to set a default value to a field, how do I do it.
I have tried value, setValue, they did not work.

**Comment by gaganmalhotra** [comment]
Hey @davidlgj , 
Does angular schema form also support conditional showing hiding form fields on certain select dropdown values. Currently I'm trying out using the condition property in Form array and changing its values as per the change in the select. Is there any other way to do it?

**Comment by Anthropic** [comment]
@gaganmalhotra you would use dynamic select add-on and retrieve the options from your server based on criteria.
