### ISSUE TITLE
Removing an invalid array item doesn't work properly

### ISSUE THREAD

**Issue by MGouaillier** [json-schema-form/angular-schema-form#750]
Hi !
I have this issue when using the array type of angular schema form. 
When you add two or more items to an arrray and fill them with invalid values, the deletion process is not working correctly.

See video example here : [http://recordit.co/xCDIUi3L8S](http://recordit.co/xCDIUi3L8S)
See angular schema form demo here : [http://schemaform.io/examples/bootstrap-example.html#/e32e956f05ed01bc216aec559f5126e5](http://schemaform.io/examples/bootstrap-example.html#/e32e956f05ed01bc216aec559f5126e5)

I tried to set the destroyStrategy to different values, but, to my knowledge, nothing seems to solve this issue.

I think this issue is highly related to #732 
@json-schema-form/angular-schema-form-lead

**Comment by nicklasb** [comment]
Hi, your links didn't work, fixed them for you.

**Comment by nicklasb** [comment]
Agree, it just deletes the last in the list, it doesn't expect more items to be added, probably.

**Comment by Anthropic** [comment]
@MGouaillier this was an easy one, array template was using `track by $index`, needed to be `track by $id(item)` which uses $$hash instead. I have committed the change for release in alpha 4
