### ISSUE TITLE
Question about Angular 1.5x support.

### ISSUE THREAD

**Issue by coderabsolute** [json-schema-form/angular-schema-form#753]
The documentation has mentioned that Angular 1.3x is supported but not sure has anyone tried with 1.5x? What advise would you give to someone who is starting a new project (admin interface from scratch) by next week?

**Comment by nicklasb** [comment]
I use it with 1.5.7, seems to work.

**Comment by ri0t** [comment]
Combining that with ES6 and Webpack - my experience so far is mixed to bad.

The basics work, but not one of the 5 plugins i used to use, works perfectly - 4 of them not at all.

**Comment by ri0t** [comment]
@nicklasb actually - your's is the only one that works (partially) - i do have working strapselects,
but no
* ckeditor
* colorpicker
* datepicker
* timepicker

**Comment by Anthropic** [comment]
@ri0t did you find any reasons as to why they are not working we may be able to fix?

**Comment by nicklasb** [comment]
@coderabsolute I am actually using it in a hybrid Angular 1/Angular 2 application right now.
I will clear up these docs a bit later on(as I didn't write them), but if you want to, Angular 2 is *possible* for the rest of the application:
https://github.com/OptimalBPM/of-admin/wiki/App-Entry-&-Bootstrapping

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently I'm spring cleaning quiet issues.
