### ISSUE TITLE
Change title dynamically 

### ISSUE THREAD

**Issue by milansgowda** [json-schema-form/angular-schema-form#754]
#### Question

As a user  I should be able to change the title/dynamically of the form dynamically. Currently i can change the value of inputs, is there a way where i can change title/label dynamically
#### Expected behaviour

{
    "key": "comment",
    "type": "textarea",
   "title":"user.title",
    "placeholder": "Make a comment"
  }
where i can set value for comment like $scope.model.comment ="Comment description" and it would change the value.  Same set $scope.user.title = "First Name" it should display "First Name" as title
#### Actual behaviour

It actually showing user.title as title

@json-schema-form/angular-schema-form-lead

**Comment by MGouaillier** [comment]
Hello :)
See : #538 

Hope this can help

**Comment by Anthropic** [comment]
Using the new builder this may be possible without the overhead added by two new watchers per field if the suggested PR doesn't cover what you are after.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently I'm spring cleaning quiet issues.
