### ISSUE TITLE
Form and schema management - How to?

### ISSUE THREAD

**Issue by nicklasb** [json-schema-form/angular-schema-form#757]
Hi all,
Like many others that use ASF, I want to generalize structure, validation and the input forms in [my framework/system](https://github.com/OptimalBPM/of), and the problem, after learning ASF, is managing them.

A solution may be important for how [our form repository ](https://github.com/json-schema-form/json-schema-form-repository) should be structured to make it easier to use and extend.

Turning to my case, I have moved stuff around in all kinds of ways, and I have problems with landing in a solution I really like. It would also be great if we could help people out with providing a common solution. 

Currently, I link schemas and forms using a prefix-name-convention. For example, the `of://node.json` schema is handled by the form that matches `of://node.json` in the dict of forms I have. However, while, well, working, it is very restricted and was always a temporary solution. It is a result of me wanting to explore ASF rather than naming conventions, because I thought the namespaces would be easier and could be left for later, given my far greater experience with that. Seems I wasn't completely right. :-)

So what I think I want is:
- A namespace-based solution
- Individual form _files_ for version management and distribution (rather than updating db:s)
- It should be possible to add to existing namespaces

The base issues are:
1. Should forms and schemas be in the same folder? 
   They are all .json files, and obviously one could name forms .form. However, that kind of screws with editors. And I sort of don't like it. 
   Also, it is highly likely that an organization have common structural definitions and validation rules in their schemas, but that the frontend forms are different depending on the system. So I lean towards separating the two.
2. Should the namespace be in the name of the file like of.node.contact.person?
   Or directories, of/node/contact/person.json? I am leaning on directories, because working with a certain subset is kind of common. And might cause less conflicts. I _feel_. But I don't _know_. Adding new namespaces is then just to add new folders. 
   For example, adding stuff from the jsf repository would be to add another root folder and add the [jsf/autodealer.json](https://github.com/json-schema-form/json-schema-form-repository/blob/master/schemas/autodealer.json) there to add `jsf/autodealer.json`to the schemas.
3. How do one connect the forms to the schemas?
   I feel that there should be an implicit way, using names and so forth in a separate database feels unnecessary, rather I would prefer naming the forms in some nice way. Like `of.node.contact.person.sparse.json`. That would tell the system that it is the "sparse" form for the "person" structure. That could enable a convention, where words like "sparse", "compact", "full", "required" would denote specific kinds of forms that would be possible to either hard code or make selectable in the UI logic.
4. Overriding 
   I build my system using plugins, so I _have to_ do this, however many systems use modules to add and override functionality, so there should be I need to be able to dynamically add definitions to the (running) system. I am currently adding to namespaces by something like naming `of.node.contact.newschema`, then my system adds that functionality to the cumulated `of.node.contact`namespace it keeps in memory.  
   However, it makes the directories-based approaches in point 1 slightly more complicated as you will need to add the folder structure, and all overrides aren't directly visible. Not a big problem, but still.

What do you think?

@json-schema-form/angular-schema-form-lead

**Comment by nicklasb** [comment]
I am seeing now that I went for the dotted representation even though I "leaned towards" the slash one. :-)
Dotted does look nicer. :-)

**Comment by nicklasb** [comment]
So I am now implementing a directory-based solution. I will see how it works and create an issue in the json-schema-form repo, detailing it and propose that we try to see if that is valuable for the community. 

I would really like to try and find some kind of "typical" implementation that we think will work for most.

**Comment by Anthropic** [comment]
@nicklasb can I close this? I think if you come up with a preferred solution you can make it available and see how many are interested in the approach and maybe start a new repo for it in future?

**Comment by nicklasb** [comment]
Would like to have gotten a diskussion going, but sure, closing.
