### ISSUE TITLE
Issue in integrating multiselect field into schema form

### ISSUE THREAD

**Issue by SureshArav** [json-schema-form/angular-schema-form#758]
#### Enhancement
Adding a new input field into schema form

#### Expected behaviour
onDropdownHide should be triggered on close of dropdown

#### Actual behaviour
It actually ...onDropdownHide not getting triggered

#### Gist/Plunker/Demo
http://plnkr.co/edit/ZapAPvU2dwM0lM9Q5IDx?p=preview

@json-schema-form/angular-schema-form-lead

**Comment by SureshArav** [comment]
working plunker

http://plnkr.co/edit/ZapAPvU2dwM0lM9Q5IDx?p=preview

**Comment by nicklasb** [comment]
Ok, so is your goal here to build an add-on to use the external component Bootstrap Multiselect in ASF? Good stuff! 
If so, first take a look on the [angular-schema-form-add-ons repo](https://github.com/json-schema-form/angular-schema-form-add-ons), you should consider the naming of you project. 

Then, this is a very complicated question that requires people to basically learn your project, and no offence, but that won't happen, so you need to be more specific.

That aside, I could not find that onDropdownHide is called anywhere by your add-on? And neither that it is presented to the multiselect anywhere?

**Comment by Anthropic** [comment]
Due to a month without response I am closing.
Please re-open if you do not feel the question has been answered sufficiently.
