### ISSUE TITLE
Render tab content on select

### ISSUE THREAD

**Issue by mgabetta** [json-schema-form/angular-schema-form#760]
Hi everybody!

I'm looking for a way to speed up the loading of my large form. It contains many large arrays which elements are rendered with selects.

Since each array is contained inside a tab, I was thinking about the possibility of generating the tab html content only after the tab selection. Thus only the first tab content would be generated initially.

I'm almost sure that this is not possible with ASF as it is now and I'm available to fork the project and try to implement the solution.

Are there any efforts in this direction? Which part of the ASF library should I start understanding/modifying?

**Comment by Anthropic** [comment]
@mgabetta It's a bit confusing at the moment as we are transitioning to webpack/babel, so part of the code is in angular-schema-form-core which is read into angular-schema-form which is read into angular-schema-form-material (I haven't done the bootstrap version yet)

You can message me questions on Gitter directly and I am happy to help you with any questions, sorry fot he delay I was on holiday.

**Comment by Anthropic** [comment]
Not sure if you ended up forking and giving it a try or not, but on thinking about it, you could create an add-on that simply adds a sub form with sf-schema+sf-form etc... and by passing the current object in as the model it would extend and then destroy when that node was trimmed. Anyway I am closing this for now, please re-open or message me on Gitter to follow up on the topic :)
