### ISSUE TITLE
Common fields removes from tabs if I I will remove any tab.

### ISSUE THREAD

**Issue by gladiussdv** [json-schema-form/angular-schema-form#762]
#### Expected behaviour

Common fields for all tabs should be safety from removing until there are any tabs
#### Actual behaviour

It actually removes common fields if any tabs will be removed

**Comment by nicklasb** [comment]
Hi @gladiussdv,
I am not sure I understand what you are saying, could you please rephrase that?

**Comment by gladiussdv** [comment]
Ok. For example. I have 3 tabs. Is there correct way to create field that would be the same for all tabs?
So if I will create tab I have this field in the new tab and in the old tabs too.
If I will remove tab I have this field in the remained tabs.


A schematic json representation:
tabs {
  tab: [
     {nameForTab1: "nameTab1"},
     {nameForTab2: "nameTab2"},
     {nameForTab3: "nameTab3"}
  ],
  commonField: "this is common text, that should be displayed for all tabs. If all tab will be removed this field is removed. If one tab or more still present then this field is present for all tabs. If this field will be changed in the one tab then this field is changed for all tabs"
}

**Comment by Anthropic** [comment]
@nicklasb this is regarding having a static section that displays on all tabs.

@gladiussdv this should be possible in the alpha if you use the $ref capability, so I will close this issue.
