### ISSUE TITLE
Angular 2.0 Integration

### ISSUE THREAD

**Issue by anupamarachuri** [json-schema-form/angular-schema-form#764]
Could you please provide a way to integrate with Angular 2.0. Basically our requirement is to include the dynamic form only for few pages and static for few. Could you please let us know how we can leverage this using the angular-schema-form.

**Comment by Anthropic** [comment]
@anupamarachuri as Angular 2 has not been released we haven't started migrating the framework to ng2 yet. If you had ng2 with the ng1 compatibility module I would expect that to work, but I haven't tried so I can't be sure. We will be trying to implement for ng2 but there's no timeline on that yet.

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by Anthropic** [comment]
@anupamarachuri there is work being done by @nicklasb on a demo of how to use the current version in an ng2 app and we have started work on making the code re-usable for ng2, but no timeline just yet.

**Comment by nicklasb** [comment]
I will start doing that soon™, meanwhile the documentation describes how it works:
https://github.com/OptimalBPM/of-admin/wiki/App-Entry-&-Bootstrapping
