### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by snoosmoomrik** [json-schema-form/angular-schema-form#766]
I tried to add an empty array in my model

#### Expected behaviour
I expected that array type schema form will not contain any items

#### Actual behaviour
It actually pushed one object in my array and showed it in from

#### Jsfiddle
[Empty array](http://jsfiddle.net/Lvc0u55v/9237/)

@json-schema-form/angular-schema-form-lead

**Comment by saltwalwei** [comment]
You can start with an empty array, just add `"startEmpty": true` to the form definition

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
