### ISSUE TITLE
Model inside Array is not cleaned when Condition fails

### ISSUE THREAD

**Issue by doomie999** [json-schema-form/angular-schema-form#769]
#### Expected behaviour
- _Given_ that a Condition is set on a property inside an Array
- _When_ the Condition is false
- _Then_ that property of the Model (that element inside the Array) should be cleaned as per the DestroyStrategy
#### Actual behaviour
- That property of the Model (that Element inside the Array) retains any previous value entered, instead of being removed as per the default DestroyStrategy
#### Gist/Plunker/Demo

[Plunker of the bug](https://plnkr.co/edit/slvZmu2s4s6WKOBj4OTL?p=preview)
The Array contains Objects with several properties:
- helloText
  - conditional on a property outside the Array
- foobar
  - used as target of condition
- fooText
  - conditional on property inside the Array (foobar)
- barText
  - conditional on property inside the Array (foobar)

Upon filling in helloText, fooText, barText, note that:
- helloText retains its value even when hello is toggled to false
- fooText retains its value even when foobar is switched to bar
- barText retains its value even when foobar is switched to foo
#### Other notes

I've coded up a small fix for this, and will be adding a Pull Request subsequently.

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@doomie999 we love PRs, so thank you for your efforts, I will continue to follow the PR so we can get it merged :)

**Comment by Anthropic** [comment]
Made a gist link to test locally and want to remember it:
http://schemaform.io/examples/bootstrap-example.html#/f7078098dc03151c5a0cc18c6452aaea

**Comment by Anthropic** [comment]
@doomie999 pleased to say this appears to be working in alpha.4 after some other remotely related changes to fix array behaviour. I have tested at depth yet, but I don't see why it wouldn't work, I will try to create a unit test at depth soon.
