### ISSUE TITLE
How to uncheck all other checkboxes using one of the checkbox in angular schema form?

### ISSUE THREAD

**Issue by gaganmalhotra** [json-schema-form/angular-schema-form#772]
schema: {
   "freeOptions": {
          "type": "array",
		"items": {
			"type": "string",
			"enum": [
				"Demo...",
				"Free edition ...",
				"Free trial ...",
				"None..."
			]
		}
	}
}
if I need to uncheck all the checkboxes on click of "None" option, how to do it?

Im using the onChange property in the form but dont know how to retrieve which checkbox it clicked as the model updates after onChange command is completed and last click value is added to model array containing clicked options.

@davidlgj Hi David, if you could help out in this case...
thanks

**Comment by Anthropic** [comment]
@gaganmalhotra you would just use the onclick event of a button and then update the model directly in javascript, you don't need to make changes to the form just update the data model and Angular handles the rest.

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by gaganmalhotra** [comment]
Thanks for your reply @Anthropic , but i want the onClick event to be attached not to a button click but to a checkbox click which is made by using schema form. I have the schema formed as below: 

{
    "key" : "inputs.isSBSOnboardingCompleted",
    "type" : "radios",
    "title" : "Is SBS onboarding completed?",
    "titleMap": [
      { "name": "Yes" },
      { "name": "In progress" },
      { "name": "Planned for the future" },
      { "name": "No"}
    ]
  },


I want to attach an event on click of 'No' in titleMap above.

**Comment by yuvi116** [comment]
@gaganmalhotra , I am running into similar issue , did you found any solution ?
