### ISSUE TITLE
Can angular directive be assigned to fields generated by asf?

### ISSUE THREAD

**Issue by gaganmalhotra** [json-schema-form/angular-schema-form#773]
Have a couple of questions:
1) is there a way to attach a angular directive to angular schema form generated fields?
for example, 
schema:
```javascript
{
"respondantRole": {
          "type": "string",
          "enum": [
            "Offering manager",
            "Marketing manager",
            "Portfolio manager",
            "Developer",
            "Other"
          ]
        }
}
```
Form:
```javascript
{
    "key" : "respondantRole",
    "type" : "select",
    "title" : "What is your relationship to this offering?",
    "onChange":"valChange(modelValue, form)"
  }
```

Is there a possible way to add ng-click directive to any particular select option, for eg, if I want this function to execute only when 'Developer' option in the checkbox is clicked...how to implement it?

Also how can we attach any other directive to any angular schema generated fields?

2)
Schema:
```javascript
{
  "type": "object",
  "properties": { 
      "input": {
          "type": "string",
          "enum": ['a','b' ]
     }
}
```

Form:
```javascript
{
    "key" : "input",
    "type" : "radios",
    "title" : "TitleName",
    "onChange":"inputChange(modelValue, form)"
  },
```

Right now, when i define a function inputChange in the controller, what i get is the value 'true/false'  in the modelValue argument but not the text of the radio button, how can we extract the text ('a' or 'b') in the function definition.

@davidlgj  & @Anthropic 
Thanks.

**Comment by Anthropic** [comment]
@gaganmalhotra please use the template provided when creating issues and read the support requirements or you may not get an answer. Do not tag individual users in an initial question.

Please create a plunker to show what you are trying to do as it allows someone answering to make a quick change to it and send back to you with possible solution, otherwise we can't se what you are doing wrong.

Also please use markdown formatting for code snippets, I have updated your question to show you how.

**Comment by gaganmalhotra** [comment]
@Anthropic Thanks for the reply Marcel. i have updated it in Plunker below:
https://plnkr.co/edit/30BjICzgFsXlQ3ZgfkUi?p=preview

Please see in app.js where i need to show the value of the checkbox being selected...how to do that using angular schema form.

Also for the second question of mine i have updated it in the same question where i want to add any angular provided directive to a text field...how to deal with that situation?

Thanks,
Gagan

**Comment by Anthropic** [comment]
@gaganmalhotra in the plunker the field is of type select not checkboxes, I can see where there may be confusion, as checkbox values are not sent to your function, you can however use the $scope.model within your code as within the console.log below, this will provide you an array of all the selected options
```javascript
$scope.valChange = function(formKey, modelValue) {
    console.log($scope.model);
```
= {respondantRole: [ "Marketing manager", "Developer" ]}

Regarding click or focus events we currently only track the change event. If you want to add an additional directive for those events you can always update the template to add that behaviour.

Please re-open if you do not feel the question has been answered sufficiently.
