### ISSUE TITLE
How to use custom directive with angular schema form?

### ISSUE THREAD

**Issue by gaganmalhotra** [json-schema-form/angular-schema-form#777]
I have a custom directive that i want to use it with the date field created by the angular schema form. If you could guide me how to implement it.

I have updated the code with my custom directive to be used in the below plunker, if anyone could help me out on this one. Thanks!

Plunker:
https://plnkr.co/edit/30BjICzgFsXlQ3ZgfkUi?p=preview

I want to use the date picker directive to be rendered using the schema form and not by using my custom directive in the html.

Thanks.

**Comment by Anthropic** [comment]
@gaganmalhotra I'm not sure I follow what you mean, are you saying you want to add the directive, but not create a custom add-on? So leave the template as it is but have it act upon part of the template?

**Comment by gaganmalhotra** [comment]
I was thinking that without making a directive can we wrap an html template to be rendered using a decorator in the schema form. But i went ahead by making a decorator and it works fine. Thanks :)
