### ISSUE TITLE
How can I get the value of arrayIndex inside onChange method?

### ISSUE THREAD

**Issue by EtiAggarwal** [json-schema-form/angular-schema-form#778]
#### Enhancement

As a user/developer, when I call the onChange method I should be able to access the arrayIndex

@json-schema-form/angular-schema-form-lead

**Comment by joelwkent** [comment]
Hi, currently it is not possible to get the arrayIndex in an onChange function but there are plans to add it. I don't have the related issue/PR IDs to hand but I will try to dig them out and list them here shortly so you can can follow, and if you fancy, get involved in the developments.

**Comment by EtiAggarwal** [comment]
Thanks

**Comment by raquintero** [comment]
@joelwkent I would love to get involved with this too, as I need this asap or I will have to completely abandon ASF and move in another direction.  I've burned way too many hours fighting ASF.

I mean at this point, if someone who really knows ASF can just explain high level what needs to be done in order for input fields to have access to Array indexes, would be a tremendous help.  Heck, is there even a jquery hack to get the index that is created for each tab's class?

**Comment by joelwkent** [comment]
Hi @raquintero, apologies for not updating you but @Anthropic has made some progress on this, see this [commit](https://github.com/json-schema-form/angular-schema-form/commit/7d456822012bce7788c487a520fabfb1bf5fdc8f)). I have not had a chance to try it out yet but you could take a look at it, pull it down and see if it works for you.

**Comment by raquintero** [comment]
@joelwkent @Anthropic Awesome!  I will take a look asap!!!

**Comment by Anthropic** [comment]
@joelwkent @raquintero I have found a bug in it, but it is almost there, I am looking at it now to try to fix it, currently getting the wrong index for the last key. I think I have the controller or directive on the wrong tag. Hopefully find a solution today.

**Comment by raquintero** [comment]
As an update for this issue, I have added the change identified here: [714](https://github.com/json-schema-form/angular-schema-form/pull/714/files) and now in my `onChange` event, I pass (modelValue, form, scope).  I rearranged the scope to the last value, so as not to break my existing onChange functions.

I use it in my onChange function defined in my Controller like this:  
> var idx = scope.$parent.$parent.$index;  // to get the index of the array I am currently in
> var parentIdx = scope.$parent.$parent.$parent.$parent.$parent.$parent.$index;  // to get my parent's index.  

I use Chrome Tools to track down how many levels of $parent I need to go.  
This is obviously a hack, but it works for now.  Just fragile.

**Comment by EtiAggarwal** [comment]
Is there any update on this ?

**Comment by Anthropic** [comment]
It is working to some degree in the latest code I have but not ready for a release yet sorry I have some other bugs to overcome.

**Comment by Anthropic** [comment]
The latest 1.0.0-alpha release should have arrayIndices / $i as an array of the array path so I will close this as that change is tracked in another issue already.
