### ISSUE TITLE
Use form to set type as number

### ISSUE THREAD

**Issue by ayhlam** [json-schema-form/angular-schema-form#781]
#### Bug
As a user/developer, when I set the schema of type of a field to be a string, then set the type to be a number in the form, then the generated input box should work completely as a number box. This is similar to the way the form can treat enums. 

#### Expected behaviour
Similar to changing the form to `type="select"`, changing the form to `type="number"` should allow the user to input numbers and integers even though the schema has `type="string"`.

#### Actual behaviour
It returns an error `Invalid type, expected string`

#### Gist/Plunker/Demo
[Demonstrate expected behavior with `type="select"` form and `type="string"` schema](http://schemaform.io/examples/bootstrap-example.html#/5e05346a9db40e39a823844178d75394)

[Demonstrate error with `type="number"` form and `type="string"` schema](http://schemaform.io/examples/bootstrap-example.html#/2933cda3912c86bf0f8318a04f5a7519)

@json-schema-form/angular-schema-form-lead

**Comment by joelwkent** [comment]
Hi @ayhlam, thanks for your interest in ASF and thanks for your very detailed issue. It's great when people provide examples like this as it ensures there is no confusion.

The behaviour you are seeing is correct and there is no bug here. The schema defines the data model, structure, data types and validation. The form defines the UI. You can put a select (enum) on a schema data type "string" as the option selected is stored in the model as a string. But you cannot put a number input field on a schema data type "string" as they are different data types. You should use the "number" or "integer" type in your schema.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
