### ISSUE TITLE
Regarding passing the scope from decorator's directive to the parent controller

### ISSUE THREAD

**Issue by gaganmalhotra** [json-schema-form/angular-schema-form#782]
**Problem:
The Parent controller's scope is not passed on to decorator's scope/ directive's scope.**

Hello,

I'm currently stuck at understanding that how decorators can be used as flexible components because as we compare with directives, directives can have their own controller definition and handle manipulations without interacting with the parent controller. 
If we don't want to use directives and just make decorators, can we have controllers assigned to a particular decorator?

Also, there is another problem that i came across, we can share common objects among parent HTML scope(root level where we define form) and decorator's(or directive's) scope only by attaching an object to the $root which remains common. Is there another way we can share common data among different scope using angular schema form without exposing our data directly to the root level.

Would be thankful if someone resolves this issue im stuck at.
Thanks.

@json-schema-form/angular-schema-form-lead

**Comment by kyse** [comment]
you could add a builder to expose the scope to a property on the form definition.  That's how I exposed the selected tab in the tabs decorator.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
