### ISSUE TITLE
Radio button validation is not working

### ISSUE THREAD

**Issue by anushamca** [json-schema-form/angular-schema-form#786]
I have a simple form along with radio buttons.I made them as required. All are working properly except the radio buttons. Even if we select one of radio buttons still it is showing Required! error message.But I tested with my same schema and form on  http://schemaform.io/examples/bootstrap-example.html#/07e5173aa0ecd930fd1814073eaf3f8e its working as we expected,but in browser not working  I don't have any clue how to get fix it.Can any body help me please.

This is the schema what I used 

Schema 
{"type": "object","title": "Employee Information","htmlClass": "row","properties": {"abc":{"title":"abc","type":"string"},"upstream":{"title":"Up Stream","type":"string","enum":["23","34","34"]},"downspeed":{"title":"Down Speed","type":"array","items":{"type":"string","enum":["1","2","3"]}},"email1":{"title":"Email1","type":"string"},"email":{"title":"Email","type":"string"},"dropdown":{"title":"Dropdown","type":"string","enum":["A","B","C"]}},"required":["upstream","downspeed","email","dropdown"]}

Form 

[{"key":"abc","type":"number"},{"key":"upstream","validationMessage":"Upstream is required","type":"radios","titleMap":[{"value":"23","name":"23"},{"value":"34","name":"34"},{"value":"34","name":"34"}]},{"key":"downspeed","validationMessage":"Down Speed is required","type":"checkboxes","titleMap":[{"value":"1","name":"1"},{"value":"2","name":"2"},{"value":"3","name":"3"}]},{"key":"email1","validationMessage":"Email1 is required","type":"string"},{"key":"email","validationMessage":"email is required","type":"email"},{"key":"dropdown","validationMessage":"Select at least one value","type":"select","titleMap":[{"value":"A","name":"A"},{"value":"B","name":"B"},{"value":"C","name":"C"}]},{"type": "submit","title": "Save"}]

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Maybe if you build a plunker based on your own code someone can compare between the two and see what you did differently?

**Comment by anushamca** [comment]
Here is the gist link http://schemaform.io/examples/bootstrap-example.html#/2c3ba5414ce1e0a3cf020a7c4bc78ffd

but in gist its working properly in browser not working.

This is my form 

<div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
	<div ng-controller="ConfigController">
		
		<form name="ngform" sf-model="modelData" sf-form="form"
			sf-schema="schema" ng-submit="submitForm(ngform,modelData)" >
		</form>


	</div>
</div>

**Comment by anushamca** [comment]
Also input type as number is also not working.

**Comment by Anthropic** [comment]
Can you make your page available or provide it as a plunker?

**Comment by anushamca** [comment]
I had fixed this issue long back.Sorry for not updated the status
