### ISSUE TITLE
Create object with field values

### ISSUE THREAD

**Issue by lorenzonet** [json-schema-form/angular-schema-form#789]
I'm new on angular-schema-form, my goal is to store form values in a database altogether, in a Json format similar to the schema, just only FieldID and Value.
I was wondering how I can accomplish this.
Afterwards when I want to review the record I'll merge the schema with the field values store in a Json object.

**Comment by lorenzonet** [comment]
I've realized right now that there's already the model object.

**Comment by Anthropic** [comment]
@lorenzonet thanks for self closing, appreciate your effort to do that :)
