### ISSUE TITLE
Feature Request: apply "readonly" to entire form

### ISSUE THREAD

**Issue by mike-marcacci** [json-schema-form/angular-schema-form#79]
Hi there. I have a use case where I need to toggle "readonly" on an entire form, rather than just a few elements. Perhaps we can look for an optional `sf-readonly` attribute on the form level?

Perhaps this could be added with #61.

**Comment by deepkamal** [comment]
forObject.schemaOptions.formDefaults.readOnly = true makes entire form readonly

its already there, unless am missing something?

**Comment by kupuguy** [comment]
@deepkamal I think what you're missing is that while setting `formObject.schemaOptions.formDefaults.readOnly = true` does indeed make the form readOnly there is then no easy way to make it editable again. Setting it to `false' and triggering the `schemaFormRedraw` event doesn't have any effect as the `readonly` attribute has been set on each field and only `readOnly=true` value is inherited from `formDefaults`, `readOnly=false` is ignored (as indeed it should be).
