### ISSUE TITLE
Thoughts on Web Workers

### ISSUE THREAD

**Issue by kyse** [json-schema-form/angular-schema-form#796]
My form is a ton of fields, and it kills the ui thread as it loads up.  Modal window animation is frozen till it finishes for instance.  I've adapted somewhat by waiting for the CSS animation to finish before initializing the form, but would be nice to have it run in another thread building out the form tree, then a final initialize loop to do actual Dom work.  With schema forms being so Dom manipulative intensive seems like a bad candidate for looking at web workers to try and solve the performance issue though.  So figured I'd write this and get some thoughts/feedback.

**Comment by Anthropic** [comment]
@kyse I have been thinking about this too, primarily if there's benefit in the core being sped up with web workers, I have been trying to find some good resources on the angular fragment store, from my understanding (and I could be VERY wrong) Angular created a worker with its own code for generating fragments, as I understand it they have most of angular 2 executed within the webworkers, I need more time to separate fact from fiction in what I just wrote though.

From what I have read, again, not much, you just can't use the built in dom, but you could use a library like jsdom within a worker. I was going to look at it for the json-schema-form-core for things like merge that are not using DOM and then progress to looking at ways it could be improved for builders and then maybe anything further. Any insight you can find/share would be greatly appreciated :)

**Comment by Anthropic** [comment]
I'm going to close this, it is always on my mind so if I can find a way for webworkers to help I certainly will be doing so, but I want to reduce the issue count, so I'm closing it :)
