### ISSUE TITLE
when using onfocus="flag=true" and onblur="flag=false" and clicking on the input field , it gives the error onfocus is not defined since the sf-schema or sf-form doesnt allow any function; Any solution for this or any update how to detect focus 

### ISSUE THREAD

**Issue by pradeep4smriti** [json-schema-form/angular-schema-form#797]
#### Enhancement
As a user/developer, when I ... I should be able to ...

#### Expected behaviour
I expected ...

#### Actual behaviour
It actually ...

#### Gist/Plunker/Demo
[Description](url)

#### Related issues
This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Hi @pradeep4smriti I'm sorry but if you aren't even going to put in the effort to fill in an issue template, how can you expect busy professionals to put in the effort to help you?

Please re-open if you can provide the issue in the required template with a demo.
