### ISSUE TITLE
Accordion or collapse

### ISSUE THREAD

**Issue by DLevai94** [json-schema-form/angular-schema-form#800]
#### Enhancement
As a developer, I want to be able to hide/show some fields of my form by using collapse or accordion. I tried it in this way: I created a checkbox and styled it to look like a button. And using condition to hide/show fields.

#### Expected behaviour
I expected it to work.

#### Actual behaviour
It actually validating the checkbox. And if it's in false, the form doesn't care about the hidden elements. But if the checkbox is true, it validates.

I want to find some way or use something to hide/show fields and validate the hidden fields too.

Can anybody help me how can I use something like a bootstrap collapse/accordion?

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Hi @DLevai94 try the code that @deyceg shared in #329 using UI Bootstrap's accordion.
https://gist.github.com/deyceg/6a3bfe870f258ef839b3aaf6b1c5a912

**Comment by mustafawani** [comment]
Can you please provide form schema for accordian
