### ISSUE TITLE
how to use form.$valid in controller? 

### ISSUE THREAD

**Issue by orbg** [json-schema-form/angular-schema-form#801]
#### Enhancement
I should be able to use form.$valid from within my controller functions.
At the moment i can us it from within a submit function as in your examples:
 
    $scope.onSubmit = function(form) {
        // First we broadcast an event so all fields validate themselves
        $scope.$broadcast('schemaFormValidate');

        // Then we check if the form is valid
        if (form.$valid) {
            // ... do whatever you need to do with your data.
        }
    };

### Actual behaviour
$scope.form.$valid is actually not available in my controller.
How to access this?

**Comment by orbg** [comment]
Sorry, found it. 
You can use formname.$valid
in my case this was not in the scope ..

**Comment by Anthropic** [comment]
Thank you @orbg for self closing, appreciate your time :)
