### ISSUE TITLE
How to get schema-validate to work with fields inside an object addon?

### ISSUE THREAD

**Issue by Lorless** [json-schema-form/angular-schema-form#802]
I have a scenario where I need an add on that produces some like 

`
{topKeyName: {
  value: 'something',
  unit: 1
}}
`

But I want to have validation on each of those fields. Why can't I do something like

`schema-validate="form.items[1]"`

for each field in my add on? Am I going about this the wrong way? I dont want to use the simpleTransclusion builder because it gives me no flexibility or control over the markup.

**Comment by Anthropic** [comment]
@Lorless thank you for self closing, appreciate your effort :)
