### ISSUE TITLE
actual tab of array in controller

### ISSUE THREAD

**Issue by orbg** [json-schema-form/angular-schema-form#804]
Is it possible to acces the index of the actual tab of an array within the controller?
Can I switch the actual tab from outside?

**Comment by Anthropic** [comment]
@orbg the templates generate angular code, you can make your own controller that attaches to the array elements and determines this value. There was another ticket in which an example was provided about interrogating array properties, try searching in the issue list for 'array'.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
