### ISSUE TITLE
angular schema form validation

### ISSUE THREAD

**Issue by dhamodharanbaskar** [json-schema-form/angular-schema-form#814]
need a create a form for jsonschema and validate it 
i have created a request and used json schema to create a form but i cant validate that form in browser
it not a full project its a demo project given for training purpose

#### Enhancement
As a user/developer, when I ... I should be able to ...

#### Expected behaviour
I expected ...

#### Actual behaviour
It actually ...

#### Gist/Plunker/Demo
[Description](url)

#### Related issues
This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@dhamodharanbaskar Why not take the demo we already made and use that?

**Comment by dhamodharanbaskar** [comment]
Sure where is the demo

**Comment by Anthropic** [comment]
The demo is linked from the main page of this repo, it is in the examples folder.

Please re-open if you can provide more information (gist/plunker) to help us to help you :)
