### ISSUE TITLE
angular json form validation

### ISSUE THREAD

**Issue by dhamodharanbaskar** [json-schema-form/angular-schema-form#815]
hi
need a validate json schema using the methods defined inside the json
gone through github and schema form
nothing gets clear since am a fresher
its a not a project just a demo given for the traning purpose
https://plnkr.co/edit/4mIteDMPQNw2q8TPzgrS?p=catalogue

**Comment by Anthropic** [comment]
@dhamodharanbaskar that plunker doesn't even include our library, so I am not sure what you want me to do. I've already told you that the demo http://schemaform.io/examples/bootstrap-example.html is the ideal place to start when building a demo. If you are struggling to know how to use Angular I suggest [Codecademy](https://www.codecademy.com/).
