### ISSUE TITLE
Error in parsing starting and closing brackets

### ISSUE THREAD

**Issue by yabasha** [json-schema-form/angular-schema-form#816]
#### Enhancement
As a developer, when I changed $interpolateProvider.startSymbol('%%'); the output 
of the form was not rendered with the fields names and placeholders, as the used starting and ending symbols in the form code is '{{ }}'

#### Expected behaviour
It should use the modified starting and closing symbols and render the form elements correctly

#### Actual behaviour
It actually doesn't parse the open and closing brackets

#### Gist/Plunker/Demo
[plunker demo](https://plnkr.co/edit/QkL97j068j1biX7jLBDh)

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@yabasha have you ever seen a library which changes its interpolation tags based on what the user has set as their start symbol?

**Comment by Anthropic** [comment]
Given the risks it could create I'm not inclined to change this, I'd recommend making a version of the decorator with your preferred markup.

https://docs.angularjs.org/api/ng/provider/$interpolateProvider
`"This feature is sometimes used to mix different markup languages, e.g. to wrap an AngularJS template within a Python Jinja template (or any other template language). Mixing templating languages is very dangerous. The embedding template language will not safely escape AngularJS expressions, so any user-controlled values in the template will cause Cross Site Scripting (XSS) security bugs!"`

If you can find examples of other libraries that have done it and include templates with changeable expression markers, I'd consider it though.
