### ISSUE TITLE
function stdFormObj not including properties { placeholder, labelHtmlClass, fieldHtmlClass, htmlClass, etc }

### ISSUE THREAD

**Issue by mnanom** [json-schema-form/angular-schema-form#817]
In function stdFormObj in file src/schem-form.js is undefined attributes globals.

**Comment by Anthropic** [comment]
@mnanom which version are you using and when do you get the error?

**Comment by mnanom** [comment]
Version 0.8.13

**Comment by Anthropic** [comment]
@mnanom any chance you could try the latest version in the feature/webpack-babel branch to see if it still occurs? What does the error look like?

**Comment by kyse** [comment]
I also ran into this.  Ended up resolving with a patch in the mean time, not sure how bad the extend call per field on performance is however.

Sorry, I've edited the vendor file a few times, not sure what the stock line # is, so pasting the surrounding code block as well.
```
        //extend with std form from schema.
        if (obj.key) {
          var strid = sfPathProvider.stringify(obj.key);
          if (lookup[strid]) {
            var schemaDefaults = lookup[strid];
            angular.forEach(schemaDefaults, function(value, attr) {
              if (obj[attr] === undefined) {
                obj[attr] = schemaDefaults[attr];
              }
              // When an individual field's form definition includes an ngModelOptions property,
              // we end up losing any ngModelOptions from the form's global sf-options.  Let's
              // create a copy of the global form settings, then pass along the individual field's
              // options.  Need to use merge here since ngModelOptions can contain nested
              // object properties.
              if (obj.ngModelOptions && schemaDefaults.ngModelOptions)
                  obj.ngModelOptions = angular.merge({},
                      schemaDefaults.ngModelOptions, obj.ngModelOptions);
            });
          }
        }
```

**Comment by Anthropic** [comment]
This has changed a lot in the alphas, not sure if it is still needed, I'm closing this until someone can make a plunker or demo for me to work with that shows the issue in the alphas. Kyse's code can be a workaround for old versions.
