### ISSUE TITLE
Document problem about "validationMessages"

### ISSUE THREAD

**Issue by blackmiaool** [json-schema-form/angular-schema-form#821]
@json-schema-form/angular-schema-form-lead

https://github.com/json-schema-form/angular-schema-form/blame/development/docs/index.md#L417

It's not a valid array. Maybe it should be:
```
[
  {
    "key": "name",
    "validationMessages": {
      "userNameAlreadyTaken":'The username is already taken'
    }
  }
]
```

**Comment by Anthropic** [comment]
@blackmiaool thanks I made the update :)
