### ISSUE TITLE
Change key dynicamally

### ISSUE THREAD

**Issue by Lorless** [json-schema-form/angular-schema-form#826]
Hi, I've got a scenario where I need to change the ng-model of a field. 

It looks something like this.

`model['color']['breakpoints']['2000']['fieldName'];`

and needs to look like this

`model['color']['breakpoints']['1000']['fieldName'];`

Is there some way i can easily go about this? At the moment Im modifying the form and the model manually and have a directive to update the ng-model on the input. Changes to the field update both the new and old models though. I cant seem to detach them.

**Comment by Anthropic** [comment]
Can you not have both in the form and use a condition to switch between them?

**Comment by kyse** [comment]
You could also look at a ngModel getterSetter scenario to dynamically target a key on the model from a field.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently I'm spring cleaning quiet issues.
