### ISSUE TITLE
New array example

### ISSUE THREAD

**Issue by zcapin** [json-schema-form/angular-schema-form#831]
Anyone using newArray.html from bootstrap decorator? I am looking at this example: https://github.com/json-schema-form/angular-schema-form-bootstrap/blob/develop/src/array.html#L3, and it seems that my new-sf-array is always null and i have a type error in watcher: https://github.com/json-schema-form/angular-schema-form/blob/0.8.13/src/directives/newArray.js#L68. Expression is "" + ".length" so i get this error: '[$parse:syntax] Syntax Error: Token '.' not a primary expression at column 1 of the expression [.length] starting at [.length]'.

Note that sf-array directive is working properly...

**Comment by Anthropic** [comment]
@zcapin if the expression is evaluating to "" + ".length" then I suspect the schema and form have a config issue. If you make a plunker/demo I am happy to take a quick look.

**Comment by zcapin** [comment]
It seems I did have a bug in my form config... :(

This plunker proves everything working fine

**Comment by zcapin** [comment]
It seems I did have a bug in my form config... :(

This plunker proves everything working fine. https://plnkr.co/edit/9GjN0bDNQm7t7pgm1KQu?p=preview
