### ISSUE TITLE
How to provide input id from the form schema?

### ISSUE THREAD

**Issue by shaun-here** [json-schema-form/angular-schema-form#832]
I want to add id to all html input fields through form schema.
How to do that?

**Comment by Anthropic** [comment]
@shaun-here what do you want to achieve, an id is already added, but ideally you would use the model data rather than need to script anything against the form ids. The new version fixes up the id and name values to be correctly applied with paths `form-obj-array-4-obj-property` for example.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
