### ISSUE TITLE
"ng-model" property of a form control

### ISSUE THREAD

**Issue by Nyasak** [json-schema-form/angular-schema-form#835]
I am trying to see how i can set the "ng-model" property of a from control, all i can see is the "title", "description", "name" etc what about "ng-model" ?

**Comment by Anthropic** [comment]
The model property is managed by the framework based on the schema and form definitions. If the form key is "user.name" the ng-model will be set to "model['user']['name']".

Please re-open if you do not feel the question has been answered sufficiently.
