### ISSUE TITLE
Get value from model without $$value$$

### ISSUE THREAD

**Issue by peckomingo** [json-schema-form/angular-schema-form#837]
I know that $$value$$ gets string replaced by SF with the link to the model in the background like this.
_model[theKeyFromForm]_. In some situation I can not use $$value$$ and I want to do it also "manually". Writing _model[myKey]_ works fine on flat structures. 

But is there a way or a API provided by SF to do it out of my controllers with more complicated keys like the ones from repeated rows and without $$value$$. For example I have the key _mySpecialKey[].fieldName_ which points to a value in a repeated row.
If I know the key is it possible to get the value without depending on $$value$$?

**Comment by Anthropic** [comment]
@peckomingo the model is just a normal javascript object structure and can be accessed from angular code in your controller  $scope.model.mySpecialKey[0].fieldName is that what you mean?

**Comment by peckomingo** [comment]
Somehow I mean this, yes... but...
Lets say I have such a key notated as a string in the scope of a form of a component like so:
scope.form.key = mySpecialKey[0].fieldName

before the form gets built the key stays the same, but when the form gets build and the json's merged this key mutates to a array construct.

So if I manually want to look for the model information in the key. How would I do this before and how would I do this after built of the form. Is there any kind of convenience API for this?

**Comment by Anthropic** [comment]
ObjectPath is included with the library and includes path traversal in normalised format and a combination of normalised or natural. "model['obj']['array'][4]['field']" vs "model.obj.array[4].field".
