### ISSUE TITLE
Remove bootstrap-decorator.js from bower distribution

### ISSUE THREAD

**Issue by donalmurtagh** [json-schema-form/angular-schema-form#842]
When I install v. 0.8.13 with bower, the `bower_components/angular-schema-form/dist` directory has the following contents
```
WHERE_IS_BOOTSTRAP_DECORATOR.md
bootstrap-decorator.js
bootstrap-decorator.min.js
schema-form.js
schema-form.min.js
```

`bootstrap-decorator.js` and (`bootstrap-decorator.min.js`) should not be included in this distribution, because the docs and `WHERE_IS_BOOTSTRAP_DECORATOR.md` state that this has been moved to a separate repository.

Also, `bootstrap-decorator.js` contains references to templates in `directives/decorators/bootstrap` that no longer exist.

I assume one should be using `bower_components/angular-schema-form-bootstrap/bootstrap-decorator.js`? If so, the version distributed with `angular-schema-form` should be removed to prevent this confusion from arising.

**Comment by Anthropic** [comment]
Duplicaate of #699
