### ISSUE TITLE
Password type input not using custom default template

### ISSUE THREAD

**Issue by wtm17** [json-schema-form/angular-schema-form#843]
When using `addMapping` method on `schemaFormDecoratorsProvider` to override the `default` template with a custom template, inputs of type `password` do not use the custom template. Inputs of type `text` and `email` do use the custom template.

Here is a plunker to demonstrate the issue:
https://plnkr.co/edit/6cW9LibLnO3NkMazJed7?p=preview

@json-schema-form/angular-schema-form-lead

**Comment by wtm17** [comment]
I have a fix for this. The password field gets updated when you add this line to the module config:

```
decoratorsProvider.addMapping('bootstrapDecorator', 'password', 'default.html');
```

I've updated the Plunker. I'm not sure if this is actually a bug - it may be functioning as intended.

**Comment by Anthropic** [comment]
Not sure if this has changed in the alpha releases, it may have, glad you sorted it :)
