### ISSUE TITLE
date picker addon page is not found ! 

### ISSUE THREAD

**Issue by akramabdulrahman** [json-schema-form/angular-schema-form#844]
#### Enhancement
As a user/developer, when I ... I should be able to ...

#### Expected behaviour
I expected the date picker addon page to be found

#### Actual behaviour
It actually gave me a 404 not found response 

#### Gist/Plunker/Demo
i've installed it yesterday to my project , i went back to it today to see how to customize stuff 
go to 
https://github.com/json-schema-form/angular-schema-form-datepicker
and see that its not there 
#### Related issues
This is/maybe related to how poorly dates were displayed on my end 
http://imgur.com/a/pBV24
i've placed the issue here , because this specific addon was mentioned here in the docs 

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@akramabdulrahman where was it mentioned here?
The plugin is not part of this org it is located at [github.com/**Textalk**/angular-schema-form-datepicker](https://github.com/Textalk/angular-schema-form-datepicker)

**Comment by akramabdulrahman** [comment]
well , it is mentioned in the full documentation section 
https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md
this snip shows where it is mentioned 
http://imgur.com/a/bo7xJ
sorry for the late response , and thanks for your fast response , people like you are awesome 👍

**Comment by Anthropic** [comment]
Awww you're making me blush 😊 

Updated, thank you for letting me know :)
