### ISSUE TITLE
Dynamic form schema

### ISSUE THREAD

**Issue by ssaallmmaann** [json-schema-form/angular-schema-form#845]
#### Enhancement
As a user/developer, I should be able to construct form by sending schema from external service. So, in theory, data and schema both are externallised unlike current implementation where i need to define schema before hand.

#### Expected behaviour
I expected that we can make the schema dynamic as well. Like sending schema information to build a form by calling a service instead of prdefined schemas.

#### Actual behaviour
Currently, it is required to set up the schema in advance. Where as the type of app i am working with doesnt know the type of form going to be used. 

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@ssaallmmaann I already load my schemas remotely, not sure what you mean, it is angular, you can set the schema and form values from a $http call if you like?

The latest alpha supports $ref as well. Can you make a plunker of what you are trying to do?

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently, I'm spring cleaning quiet issues.
