### ISSUE TITLE
two forms on the same page

### ISSUE THREAD

**Issue by mferreira92** [json-schema-form/angular-schema-form#854]
Hi,

I have a situation where I will need in the same page two schema forms. 

How can I load two completely different forms on the same same?

I've tested adding two examples on the same page, but it will load only the first form 
(e.g. http://schemaform.io/examples/bootstrap-example.html).

I've changed the div ID beucause it could be an overwrite, but still no luck. Do you have any guidance on this?

Thank you

**Comment by Anthropic** [comment]
You want the same schema with two different form definitions?

Can you make a plunker, I can tell you what you are doing wrong if I have a reference to refer to?

**Comment by Anthropic** [comment]
@mferreira92 here's a demo @johnslipper sent me, posting for anyone who finds this issue in future, it demonstrates different decorators on the same page, but ultimately covers this as well.
https://plnkr.co/edit/Rfy2vO3otiQDZTGzgTZi?p=preview

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by billdavidson4** [comment]
@Anthropic  : I have the need to have many forms on the same page and am trying to pass a schema in using {{schemaName}} notation which is failing.  The Plunker you shared seems to only handle different decorators via angular variable binding.  sf-use-decorator seems to allow for binding but not schema.  

Is there something I am missing or do you have thoughts on handling this use case?

**Comment by johnslipper** [comment]
Hi billdavidson4. Are you saying you are passing a variable curly braces to the sf-schema attribute? If so that is not required. 

If you are using a single element on the page to display different schemas then the form should re-render if you re-assign the variables used on the form. You could do this in the controller.

**Comment by billdavidson4** [comment]
Thanks @johnslipper.   I am dynamically generating a page, and need to pass a variable to the schema in order for it to pull the right schema.  OR, I am now trying to do this with the sf-insert-field to get the questions to show up in their correct location.

so basically it is like this:
ng-repeat:

<div id="someDynamicIdentifier">
some html
< : questions for form with id : someDynamicIdentifier >
</div>

repeat .... 
<div id="someDynamicIdentifier_z">
some html
< : questions for form with id : someDynamicIdentifier_z >
</div>

end.

Make sense?

**Comment by johnslipper** [comment]
I'm not sure I follow. Are you generating the page in angularJS? If you have multiple angular schema forms then using a controller function to determine which one is required first, then assigning that to your template variable would be a way. Am I close? If not can you give a code demo in something like plunkr?

**Comment by billdavidson4** [comment]
@johnslipper  - thank you.  You started me rethinking my implementation and it's not as clean as I hoped, but it totally works.

Thanks!

**Comment by Anthropic** [comment]
@johnslipper thank you for your time in assisting @billdavidson4, much appreciated sir.
