### ISSUE TITLE
Adding form fields on the fly

### ISSUE THREAD

**Issue by Lorless** [json-schema-form/angular-schema-form#856]
I have a scenario where I need to add form fields after the form has been rendered. Usually this just works with a little processing of the keys on my part. 

I've hit a problem where arrays added on the fly do not work correctly, mainly the add buttons do not increment the array number and drag and drop re-ordering does not work. Of course I could just call 'schemaFormRedraw' but the angular.copy(form) line completely severs all of the connections between the form I had and the one that is redrawn, accordions no longer work, directives lose all their bindings. 

It's impossible to use redraw without making sure every single binding you have is saved on a service somewhere which is  not practical. 

Any suggestions on where to go from here? Im considering writing a custom function to add new array objects with the proper key bindings somehow.

**Comment by Anthropic** [comment]
@Lorless which version are you using, an alpha? Arrays are working better in the alpha. Still some work needed on the alpha to get add-ons working properly again, but should be sorted very soon.

**Comment by Lorless** [comment]
@Anthropic 0.8.13 I think but its hard to know for sure since none of the files have version numbers. That appears to be the latest version though? Are you saying that adding array form fields after render might work in the latest version?

**Comment by Anthropic** [comment]
@Lorless the alphas have version numbers, I have added that in, I don't know how previous maintainer managed issues without knowing, surprised it didn't drive him nuts. Anyway alphas have version info headers in-file.

The alphas ensure that arrays have correct index values for items so the button should in theory no longer be confused, but I would need an example to test against to be sure.

**Comment by Anthropic** [comment]
Please re-open if you do not feel the question has been answered sufficiently I'm cleaning up quiet issues.
