### ISSUE TITLE
boolean values allow true only on generated schema

### ISSUE THREAD

**Issue by jagould** [json-schema-form/angular-schema-form#857]
We are generated schema automatically from java pojos using jackson libraries.  in that library boolean values automatically get "required", which makes sense as in java this is a primitive and so cannot contain null.  

Unfortunately, forms are now generating with a checkbox  that only allows "true" as the value.  This appears new as it did not occur in prior versions of angular-schema-form.  Also, I don't believe this matches the schema where required would allow true or false but not null.

@json-schema-form/angular-schema-form-lead

**Comment by jagould** [comment]
Rereading my post, apologies if my ranting is unclear.  So to clarify, the schema below has "myBoolean" as a required field.  The generated form using the default form ["*"] displays an error when the checkbox is empty even though the underlying json value is set to false, which is valid according to the schema.  This started occurring after upgrading to the latest download.  


{"$schema":"http://json-schema.org/draft-04/schema#",
"title":"my_schema",
"type":"object",
"additionalProperties":true,
"properties":{
"myArray":{"type":"array","items":{"type":"string","pattern":"^\\d+$"},
			"description":"string of numbers","title":"numbers"},
"myBoolean":{"type":"boolean","description":"If true, do something","title":"Do Something"}},
		"required":["myArray","myBoolean"]}}

**Comment by Anthropic** [comment]
@jagould thanks for the report :)

I can see what you mean, I made a Gist of the working one that doesn't work in the current version to test against:
http://schemaform.io/examples/bootstrap-example.html#/3bc648fe6e7d6e3e348b396fc41f8ede

**Comment by Anthropic** [comment]
This is ready to be released in the next alpha as it was a logic fail when I moved Angular specific code into the core and replaced it with code that wasn't identical.
