### ISSUE TITLE
Provide continued support for Internet Explorer

### ISSUE THREAD

**Issue by krptodr** [json-schema-form/angular-schema-form#864]
Can you please continue to develope ASF with support for Internet Explorer, when moving forward into versions 1+?

The business world is still heavily using IE due to many intranet sites using ActiveX controls.

**Comment by shravanmahankali** [comment]
+1

Also, can you provide some guidance on how to get latest alpha build?

**Comment by ramakrij** [comment]
+1. I dont think dropping support for IE completely is a step in the right direction. If there is any thing specific that causes this behaviour, I am happy to spend a few hours and help with some tasks if that would help.

**Comment by Anthropic** [comment]
@krptodr @shravanmahankali @ramakrij 
I've never dropped support for IE deliberately, I know plenty of poorly managed companies are stuck on legacy platforms, the corporate I work for only a few years ago adopted Chrome alongside IE, took most of a decade to get approval! No one has reported any issues specific to IE in Github that I'm aware of, so I can't fix what I don't know about :)

I don't use IE, so I would ask anyone reporting such issues do some evaluation to determine what the cause may be. Thanks for the offer @ramakrij by all means let me know what you think the issue may be!

I wont be able to work on support for versions prior to IE 11 personally though, I just don't have the resources, but again, happy to test PRs, if the tests pass there's a good chance I'll accept it, but happy to discuss anything before/during/after any work is done on a PR to fix IE support.

Please  open new issue for what you find may be wrong :)

**Comment by donalmurtagh** [comment]
> I've never dropped support for IE deliberately, I know plenty of poorly managed companies are stuck on legacy platforms

This is about the browser version that a product's users are using. This is not necessarily something that a company can control or even influence, regardless of how well managed it is.

**Comment by Anthropic** [comment]
@donalmurtagh I would disagree that's what it is about, the OP talks of ActiveX usage, end users wouldn't know their ActiveX from their X-Men. But in the corporate space the company does indeed tightly control browser usage in their SOE and even though Microsoft has expressly stated that users of older windows versions or corporation stuck in ActiveX​ hell should install Chrome alongside IE, many IT departments are under funded and resourced and haven't been able to upgrade their SOE, I work for one such corporation that has finally moved to Chrome after two year transition, so I know the pain and I'm happy to help. But given the lack of help I get I can't devote my limited time to the least used browser, I **need your help** and anyone else willing, if I'm to support a browser I don't use.

I assume it is related to unsupported JavaScript or the Babel compile, something some guidance on shims may be able to alleviate easily. I'll try to look at IE when I get to beta, it would be great if IE users could help with a few error reports, solution ideas or error console stacks in the meantime.

**Comment by donalmurtagh** [comment]
> But in the corporate space the company does indeed tightly control browser usage in their SOE

In my case the application which uses ASF is used by members of the public, and our analytics shown that a significant proportion of them access it via IE11. There's little we can do to encourage them to switch to another browser, and there are too many of them for us to drop support for IE11. The only option we seem to have then is to continue using 0.8.13, which is unappealing, because we've run into lots of bugs with this version. Although many of these have been fixed in the recent alphas, the fixes are not being backported to an 0.8.13 version, so if 1.0.0 is released without IE11 support, we're really stuck between a rock and a hard place.

> But given the lack of help I get I can't devote my limited time to the least used browser, I need your help and anyone else willing, if I'm to support a browser I don't use.

FWIW, I don't use IE either, it's those pesky users....

> I'll try to look at IE when I get to beta, it would be great if IE users could help with a few error reports, solution ideas or error console stacks in the meantime.

I'm pleased to hear that you might be able to give this some attention before 1.0 is finalised. It's a bit tricky for me to test IE as I use a Mac, but I'll try to use a VPN or browserstack to help out.

**Comment by Anthropic** [comment]
@donalmurtagh I did expect IE11 to have enough support to work to be honest, I just tried it and it doesn't show the form, but does not provide a single error or detail in console that could explain why...

F@#&. 😡

**Comment by Anthropic** [comment]
Hey @donalmurtagh @ramakrij @shravanmahankali @krptodr
I just tried with this [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) and it appears to work, I will look at either starting an additional file for backwards compatibility or get webpack/babel to add the polyfill, I'll decide once I know how many other issues may arise that need polyfills also. Can any of you find some time to test with the polyfill and see if there are any other issues you come across that clearly change behaviour between IE11 and Chrome?

**Comment by shravanmahankali** [comment]
Is there a plunker setup with issues being talked about, as earlier I had trouble (blank screen) using alpha library?
