### ISSUE TITLE
i18n demo

### ISSUE THREAD

**Issue by shravanmahankali** [json-schema-form/angular-schema-form#865]
#### Expected behaviour
I expected application to support internationalization and localization with modular and scalable approach.

#### Actual behaviour
No inbuilt support for i18n/ l10n. In-built messages are in English only.

#### Gist/Plunker/Demo
[Description] Based on schema-form.js v0.8.13 I have developed a dynamic forms example with internationalization and localization support for English and Spanish languages. Example is available at Plunker here - https://plnkr.co/edit/WKduZL0Xe2lmkV9N5mk8?p=preview. This example demonstrates the separation of schema and form JSON data to separate files and load them using $http to angular modules and bind it to sfSchema and sfForm directives. Please review this example at plunker and add it to the project examples.

#### Related issues
The default messages like: 202: String does not match: {{schema.pattern}} from schema-form are in English only and needs support for various languages.

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@shravanmahankali the demo in the link has errors, did you perhaps save an update that didn't get updated in the link?

**Comment by shravanmahankali** [comment]
@Anthropic sorry for the trouble, I have fixed the issues with the example at plunker, its working fine now. Please try now.

**Comment by Anthropic** [comment]
@shravanmahankali nice that works great, will no doubt help a lot of people! :)

**Comment by shravanmahankali** [comment]
Waiting to see my contribution of i18n/ l10n demo live. Let me know. 
Btw, any suggestions on 'Related issues' I have mentioned in this issue?

**Comment by Anthropic** [comment]
@shravanmahankali have you tried adding languages to tv4?https://github.com/geraintluff/tv4#addlanguagecode-map

Is that what you are after?

**Comment by Anthropic** [comment]
@shravanmahankali do you want to make a PR to add it to the documentation? Then you get added to the repo as a contributor, under a header of "i18n/ l10n" something along the lines of "While the library does not specifically address i18n/l10n it is certainly possible as this plunker demonstrates.". Would you like to do it or do you want me to add it?

**Comment by shravanmahankali** [comment]
@Anthropic I am not familiar with the PR process, can you guide me through?

**Comment by Anthropic** [comment]
Well these days you can make a PR directly from GitHub, you just select to edit a file in the dev branch https://github.com/json-schema-form/angular-schema-form/edit/development/docs/index.md then when you go to save it, at the bottom, you should see "Create a new branch for this commit and start a pull request". Are you familiar with Markdown? Don't update the table of content at the top I can do that afterwards for you.

**Comment by Anthropic** [comment]
The other way is to fork the repo and make the change in your own copy and then create a pull request from your repo to this one, it gives you a bit more control but ultimately does the same thing.

**Comment by shravanmahankali** [comment]
I realized by PR you meant a pull request and I can do that. So, once after I do a PR from development branch and then I'll integrate my i18n/l10n sample to the code. Is that correct? If so, I need to take a look at your code to find a way to integrate.

**Comment by Anthropic** [comment]
@shravanmahankali I just meant to add a section in the docs/index.md file to point to your plunker with a description about the link like what I wrote :)
