### ISSUE TITLE
destroyStrategy is not clearing the model in custom field

### ISSUE THREAD

**Issue by Lorless** [json-schema-form/angular-schema-form#867]
Hi,

My custom fields are not having their model destroyed when they are hidden. In a lot of cases ive simply wrapped the html from the original default field (like text input) in my own custom field and added some stuff. My custom declaration looks like this 

```
(function () {
  angular.module('cohesionApp').config(function (schemaFormDecoratorsProvider, sfBuilderProvider) {


    schemaFormDecoratorsProvider.defineAddOn(
      'bootstrapDecorator',           // Name of the decorator you want to add to.
      'cohTextBox',                     // Form type that should render this add-on
      'scripts/form-elements/coh-text-box/coh-text-box.html',  // Template name in $templateCache
      sfBuilderProvider.stdBuilders                     // List of builder functions to apply.
    );


  });
})();
```

I expected that the model would be destroyed as i have not made any changes to the global options for destroyStrategy. I actually purposely put destroyStrategy 'null' and destroyStrategy 'remove' on the field but this had no effect either. 

The model remained no matter what i did, though the conditions for showing hiding triggered properly.

I cant provide a plunkr... its way too complicated and big to set up. 

I can think of 2 things that might be causing this.

1. the keys and conditions are both being re-written on the fly as my form is very dynamic and can be reorganised. This hasn't caused any other bugs though and models are always linked up properly and conditions always trigger.

2. I am using a custom field i made myself

**Comment by Anthropic** [comment]
It all depends on your templates, can you share one? Destroy strategy is managed by sf-field directive, if you don't have that then it won't destroy anything and you would have to manage it yourself with your own directive.

**Comment by Lorless** [comment]
Sure, here is an example. You'll see its basically the same as the standard text box but its been wrapped with a few extra bits.

```
<div coh-id-tagger class="form-group coh-text-box {{form.htmlClass}}" ng-class="{'no-label': !showTitle()}" ng-hide="form.isActive===false">
  <!-- Surrounding DIV for sfField builder to add a sfField directive to. -->
  <div class="form-group-inner">

    <label class="control-label {{form.labelHtmlClass}}" ng-class="{'sr-only': !showTitle()}"
           for="{{form.key.slice(-1)[0]}}">{{form.title}}</label>
    <coh-helper-button info="form.helperInfo"></coh-helper-button>

    <var-switcher></var-switcher>
    <div class="coh-form-input" ng-show="!dir.proxyIsVariable">

      <div class="schema-form-{{form.type}}"
           ng-class="{'has-error': form.disableErrorState !== true && hasError(), 'has-success': form.disableSuccessState !== true && hasSuccess(), 'has-feedback': form.feedback !== false }">
        <input
          ng-if="!form.fieldAddonLeft && !form.fieldAddonRight" ng-show="form.key" type="text" step="any"
          sf-changed="form" placeholder="{{form.placeholder}}" class="form-control {{form.fieldHtmlClass}}"
          id="{{form.key.slice(-1)[0]}}" ng-model-options="form.ngModelOptions" sf-field-model="replaceAll"
          ng-model="$$value$$" unique-value
          ng-disabled="form.readonly" schema-validate="form" name="{{form.key.slice(-1)[0]}}"
          aria-describedby="{{form.key.slice(-1)[0] + 'Status'}}">
        <div ng-if="form.fieldAddonLeft || form.fieldAddonRight"
             ng-class="{'input-group': (form.fieldAddonLeft || form.fieldAddonRight)}">
          <span ng-if="form.fieldAddonLeft"
                class="input-group-addon"
                ng-bind-html="form.fieldAddonLeft"></span>
          <input ng-show="form.key" type="text" step="any" sf-changed="form" placeholder="{{form.placeholder}}"
                 class="form-control {{form.fieldHtmlClass}}" id="{{form.key.slice(-1)[0]}}"
                 ng-model-options="form.ngModelOptions" sf-field-model="replaceAll" ng-model="$$value$$"
                 ng-disabled="form.readonly" unique-value="$$value$$"
                 schema-validate="form" name="{{form.key.slice(-1)[0]}}"
                 aria-describedby="{{form.key.slice(-1)[0] + 'Status'}}">
          <span ng-if="form.fieldAddonRight"
                class="input-group-addon"
                ng-bind-html="form.fieldAddonRight"></span>
        </div>
        <span ng-if="form.feedback !== false" class="form-control-feedback"
              ng-class="evalInScope(form.feedback) || {'glyphicon': true, 'glyphicon-ok': hasSuccess(), 'glyphicon-remove': hasError() }"
              aria-hidden="true"></span>
        <span ng-if="hasError() || hasSuccess()"
              id="{{form.key.slice(-1)[0] + 'Status'}}"
              class="sr-only">{{ hasSuccess() ? '(success)' : '(error)' }}</span>
      </div>

    </div>

    <span class="coh-description" ng-class="{'coh-form-hidden': (hasError() || form.description) === false}" sf-message="form.description"></span>

  </div>
</div>
```

**Comment by Anthropic** [comment]
@Lorless any chance you can show an example of it rendered too, may help see what is and isn't working?

**Comment by Anthropic** [comment]
Are there any errors in console?

**Comment by Lorless** [comment]
Sure, here is the rendered field including its sf-decorator. There are no console errors. It appears that the destroy event in schema-form.js is never fired.

```
<sf-decorator ng-repeat="item in form.items" form="item" class="ng-scope"><!-- ngIf: evalExpr(form.condition,{ model: model, "arrayIndex": arrayIndex, "modelValue": model['styles']['xl']['padding-bottom']['value']}) --><div coh-id-tagger="" class="form-group coh-text-box" ng-class="{'no-label': !showTitle()}" ng-hide="form.isActive===false" ng-if="evalExpr(form.condition,{ model: model, &quot;arrayIndex&quot;: arrayIndex, &quot;modelValue&quot;: model['styles']['xl']['padding-bottom']['value']})" aria-hidden="false">
  <!-- Surrounding DIV for sfField builder to add a sfField directive to. -->
  <div class="form-group-inner">

    <label class="control-label " ng-class="{'sr-only': !showTitle()}" for="value">Padding bottom</label>
    <coh-helper-button info="form.helperInfo"><span ng-click="chb.openModal()" ng-show="!dir.proxyIsVariable&amp;&amp;form.info" class="coh-helper-button fntl-icon-help-circled ng-hide" role="button" tabindex="0" aria-hidden="true">
</span>
</coh-helper-button>

    <var-switcher><div>
  <div ng-show="dir.proxyIsVariable" class="form-group ng-hide" aria-hidden="true">
    <input class="form-control ng-pristine ng-untouched ng-valid ng-empty" id="styles:variable:6685" placeholder="Enter variable name" type="text" ng-change="dir.changeVariableValue()" ng-model="dir.proxyVariable" ng-disabled="form.disableVariable" aria-invalid="false">
  </div>
</div>
</var-switcher>
    <div class="coh-form-input" ng-show="!dir.proxyIsVariable" aria-hidden="false">

      <div class="schema-form-cohTextBox has-feedback" ng-class="{'has-error': form.disableErrorState !== true &amp;&amp; hasError(), 'has-success': form.disableSuccessState !== true &amp;&amp; hasSuccess(), 'has-feedback': form.feedback !== false }">
        <!-- ngIf: !form.fieldAddonLeft && !form.fieldAddonRight --><input ng-if="!form.fieldAddonLeft &amp;&amp; !form.fieldAddonRight" ng-show="form.key" type="text" step="any" sf-changed="form" placeholder="" class="form-control ng-touched" id="value" ng-model-options="form.ngModelOptions" sf-field-model="replaceAll" ng-model="model['styles']['xl']['padding-bottom']['value']" unique-value="" ng-disabled="form.readonly" schema-validate="form" name="value" aria-describedby="valueStatus" aria-hidden="false" aria-invalid="false"><!-- end ngIf: !form.fieldAddonLeft && !form.fieldAddonRight -->
        <!-- ngIf: form.fieldAddonLeft || form.fieldAddonRight -->
        <!-- ngIf: form.feedback !== false --><span ng-if="form.feedback !== false" class="form-control-feedback ng-scope glyphicon" ng-class="evalInScope(form.feedback) || {'glyphicon': true, 'glyphicon-ok': hasSuccess(), 'glyphicon-remove': hasError() }" aria-hidden="true"></span><!-- end ngIf: form.feedback !== false -->
        <!-- ngIf: hasError() || hasSuccess() -->
      </div>

    </div>

    <span class="coh-description" ng-class="{'coh-form-hidden': (hasError() || form.description) === false}" sf-message="form.description"></span>

  </div>
</div><!-- end ngIf: evalExpr(form.condition,{ model: model, "arrayIndex": arrayIndex, "modelValue": model['styles']['xl']['padding-bottom']['value']}) -->
</sf-decorator>
```

**Comment by Lorless** [comment]
@Anthropic So I've been investigating this and it seems that the custom directive is not to blame, ive tried it with the default text field and it still does not remove the model. I've put loggers on lines 2131 and 623 on schema-form.js just underneath the $destroy events but it seems they arent being fired at all.

**Comment by Lorless** [comment]
I've just realised that none of the fields inside my custom directives (apart from the very top level custom directive) have sf-field attached to their container divs. I think this may be because i've used 
` <sf-decorator ng-repeat="item in form.items" form="item"></sf-decorator>` in my custom directives where the custom directive has its own items array to render.

 If the sf-field directive is not present, would this stop any $destroy event firing?

**Comment by Anthropic** [comment]
@Lorless two quick responses, first, you mentioned schema-form.js I assume that means you are using 0.8.13, have you tried with the alphas, could you please if not?

Secondly, yes, `sf-field` is where the destroy activity is managed from, so I would expect that it needs to be in the template.

**Comment by Lorless** [comment]
@Anthropic I believe we tried to move over to the alpha a little while ago and it broke our system. We will of course migrate eventually but its hard to make a case for it right now. 

Is there any reason why the sf-field directive wouldn't be applied to items rendered from sf-decorator inside a custom field? That seems to be the heart of the problem. I have custom fields like accordions that render more form fields inside themselves using that sf-decorator with a repeat

**Comment by Anthropic** [comment]
@Lorless ideally if you are appending new items using a builder would be the better method, I haven't got time to provide more info tonight, if you haven't found a solution by 20 hours from now let me know nad I will try to help tomorrow night :)

**Comment by Lorless** [comment]
@Anthropic tried updating to v1.0.4 and well... nothing. The form doesn't render at all, not even a  lonely div. No errors either.

**Comment by Anthropic** [comment]
@Lorless are you on IE by any chance? If so you need a polyfill for Object.assign, I will be added it to the next alpha either directly or in a legacy browser support file.

**Comment by Lorless** [comment]
@Anthropic no, im on chrome, although i've just been informed i may need to install the bootstrap decorator separately.

**Comment by Lorless** [comment]
@Anthropic So i think i've hit the brick wall here. If i implement the builder function you suggested i think it will break the forms I have where the user can add form fields as they go. The current sf-decorator with repeat im using means any form fields added will simply be created when angular finishes its digest cycle. If i use the builder the only time any children will get built is on initialisation and on schemaFormRedraw which i cannot use due to the way the angular.copy() detaches the newly drawn form from the current one. 

Thanks for your help. I think i'll close this one.
