### ISSUE TITLE
File upload field?

### ISSUE THREAD

**Issue by etodanik** [json-schema-form/angular-schema-form#87]
How complicated would it be to create a File field support? I'd be happy for a few pointers since I'm going to need this functionality in my project.

**Comment by stefanhuber** [comment]
Has anybody released the Upload Field as an Open Source extension?

**Comment by FrankOrtmann** [comment]
I too would be interested in using such an extension.

**Comment by sndp-vrma** [comment]
https://github.com/chengz/schema-form-file-upload

This might help!!!!!!

**Comment by FrankOrtmann** [comment]
Thanks, will look into it!
