### ISSUE TITLE
form.key inside arrays

### ISSUE THREAD

**Issue by mnzaki** [json-schema-form/angular-schema-form#870]
#### Bug
`form.key` inside arrays appends the array path and empty string `""` after the actual key, for example giving `["names", 0, "names", ""]` for the first array item in an array with key `["names"]`.

#### Gist/Plunker/Demo
[Plunker demonstrating the issue](https://plnkr.co/edit/e7gj799X4ijPyUEbyA0n?p=preview)

@json-schema-form/angular-schema-form-lead

**Comment by mnzaki** [comment]
And it has more weird behavior when in arrays in objects. Plunker updated to demonstrate.

**Comment by Anthropic** [comment]
@mnzaki `"key": 'names[]'` should be `"key": 'names'`
You only need [] when there is a sub property like `names[].names`

Because it doesn't know the key it can't replace it with the index.

**Comment by mnzaki** [comment]
I updated the plunker to reflect that, but now the empty string gets replaced with `0` (for all keys), also `form.key` seems to be overridden by the last key always (try adding a new value to the array)

**Comment by mnzaki** [comment]
Also the behavior of `sfKeyController` seems to be broken for `type: "fieldset"`. The `fieldset` form addon adds an `sf-index="{{$index}}"` attribute, but there's no `$index` defined in that scope and that gets parsed into a `0`.

**Comment by Anthropic** [comment]
@mnzaki

**Comment by mnzaki** [comment]
I have been looking at code, and there seems to be a few problems.
For starters, `sfPath.parse("[]")` returns `[""]`, is this correct behavior?

If so then in `fieldset.html` addon template, `sf-key-controller sf-parent-key=\"[{{form.key.join('][')}}]\"  sf-index=\"{{$index}}\">` will produce incorrect results when `form.key` is empty, as that evaluates to `sf-parent-key="[]"` which is parsed to `[""]` and then the index (which is empty) is parsed to `0`.

**Comment by Anthropic** [comment]
@mnzaki right, makes sense, I didn't get a chance the other night, wife dragged me out shopping, very much against my will, will definitely take a look this weekend.

**Comment by mnzaki** [comment]
More analysis:

Another related problem is in [this line](https://github.com/json-schema-form/angular-schema-form/blob/104a3fa98d688b547feece7d4a38bc7c20adcf5e/src/directives/sf-field.directive.js#L34) in `sf-field.directive`:
```javascript
        scope.initialForm = Object.assign({}, sfSchema.lookup['f' + attrs.sfField]);
/*->*/  scope.form = sfSchema.lookup['f' + attrs.sfField];
```

Assigning the form object directly from the `sfSchema.lookup` will break for arrays as there's only 1 form item object for all the array items, so when changes are made to the object (ie, replacing the `""` with the index) it will affect all items. You can see this effect in the plunker, all items have the same `form.key` (with the indices for the last item processed, as it has replaced the previous ones of course), but the `completeKey` is correct as it is generated (new object) for each scope.

Changing this to the (IMHO) correct behavior of copying the item each time unfortunately causes breakage in certain areas that depend on the side-effect of `form.key` being the actual object that is in the lookup, which is also the actual object from inside the form passed to `sf-form` directive. The things that break are for example [this](https://github.com/json-schema-form/angular-schema-form/blob/104a3fa98d688b547feece7d4a38bc7c20adcf5e/src/directives/sf-schema.directive.spec.js#L2183) which sets a value on the supplied form object and then expects that this will propagate a change *without* broadcasting a `schemaFormRedraw` event.

I think that in a best case scenario this should not be supported (ie, making changes and not firing `schemaFormRedraw`), but unfortunately it might break existing code that depends on this behavior.

Also note the tests I just pushed and PRed, I purposefully left out the form object everywhere (so that the default is generated) as that triggers broken `form.key` even for the cases that normally work (like array of objects) if you supply the keys manually.

**Comment by mnzaki** [comment]
@Anthropic I think I broke something with the fixes related to this issue, please take a look at the test I just add [here](https://github.com/mnzaki/angular-schema-form/commit/7906ac66bbbda870f0e36a780db92ecc8c8f6287). When deleting items from an array of objects it deletes other items as well. The bug is triggered when the form object has a "fieldset" (as opposed to the object items directly referenced in the array form object items)

**Comment by mnzaki** [comment]
The issue may be faintly related to #750 and #769 and #689

**Comment by Anthropic** [comment]
Thanks, I am hoping to get some time this week to fix up some of the smaller issues like this. Thanks for the update.

**Comment by mnzaki** [comment]
@Anthropic please do take a look at #895 which adds a test and a fix for the issue I just mentioned.

**Comment by Anthropic** [comment]
@mnzaki The [should not delete innocent items on delete](https://travis-ci.org/json-schema-form/angular-schema-form/builds/242656408?utm_source=github_status&utm_medium=notification) test is failing, can you take a look at what would be causing that?
ps. it can sometimes be node version related.

**Comment by mnzaki** [comment]
@Anthropic that's again the same issue because I did not commit `dist` :D I do remember you said you fixed that but it doesn't look like it's pushed yet.

**Comment by Anthropic** [comment]
Ah yes, you even added a comment on it to that effect, sorry about that!

**Comment by Anthropic** [comment]
@mnzaki sat down at my home pc and immediately realised I couldn't sync latest changes as I had the build fix uncommitted, got one bug to fix then I should be able to push it.

**Comment by Anthropic** [comment]
Merged :)
