### ISSUE TITLE
Checkbox validation is not working with version 1.0-alpha4

### ISSUE THREAD

**Issue by warmy1004** [json-schema-form/angular-schema-form#875]
#### Enhancement
Validating a checkbox is not working. 

How to reproduce:
1. Select Yes for the first question
2. click 'Validate' button 

#### Expected behaviour
I expected 'Required' error message is displayed on the screen for the last question, checkbox one

#### Actual behaviour
It actually no error message is pop up and it's in a success stage instead of an error stage. The color is changed to green which means it's in a success stage.

#### Gist/Plunker/Demo

[Description]https://plnkr.co/edit/GpmbaMPZmtgofOdV0Fye?p=preview

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@warmy1004 your issue is actually resulting from something that was fixed, the previous behaviour was actually causing errors.

Add `"enum": [ true ]` to the schema to get the behaviour you are needing.
