### ISSUE TITLE
Schema groups / tabs / accordion

### ISSUE THREAD

**Issue by Schaussi** [json-schema-form/angular-schema-form#878]
Hi,
I am using a quite huge schema, so I am looking for the best way to only display partial data, if possible without creating a separate form definition ([*]).
What I found so far is #800, unfortunately in my test project I only see a minimal button without any function.

Basically, I would like to give a schema object (e.g. myschema.myobject) a certain type like "x-form-schema" : { "type": "tabOrGroupOrAccordionEtc" }, so it would display all underlying items e.g. as tabpages.

Meanwhile, is there maybe a recommended way to achieve this behavior without having to create a separate form definition?

Thank you

**Comment by Anthropic** [comment]
json-schema is a standardised format, but in the documentation there are details on how to add form definition rules to your schema. You can also make an add-on without the need to make an entire decorator.

**Comment by Schaussi** [comment]
x-schema-form would be perfect for my case, but I think it is not possible to tell e.g. myschema.myobject to generate all its underlying objects (but only 1 level) as tabs, as you have to also specify the "tabs" and "items" properties.
It would be great if one could use the star symbol for certain parts of the schema in the form definition, like "myschema.myobject.[*]".
Unfortunately, I am too little expert in JS and Angular for creating an add-on I think, so probably I will write the complete form definition. Anyway, thank you for your hints.

**Comment by Anthropic** [comment]
So is this closable if you have a solution then?

**Comment by Schaussi** [comment]
Yes, thank you.
