### ISSUE TITLE
Image fields

### ISSUE THREAD

**Issue by alexandroscgb** [json-schema-form/angular-schema-form#884]
Hi.

I was wondering if I cand add an image field to the form, like manully inserting a new field, I just don't see how.
It would be simple functionality of uploading an image to a server in a rest service.

Where can I look up this?

Thank you.

**Comment by Anthropic** [comment]
Check out this answer #364
There's also:
https://github.com/chengz/schema-form-file-upload
https://github.com/guillbdx/angular-schema-file-type
