### ISSUE TITLE
Enhancement: validate generated form-items

### ISSUE THREAD

**Issue by miukki** [json-schema-form/angular-schema-form#892]
lets say i have generated a few inputs 
`<input name="attr-dropdown-{{$index}}">
`
where is `{{$index}} ` 0,1,2

in scheme json i added: 
```json
    "^attr-dropdown-[0-9]+$": {
      "type": "number"
    },

```

so .. would be nice to have it

**Comment by Anthropic** [comment]
@miukki I think you need to bring this up in the json-schema org, we don't modify the schema standard in this project. If you want to propose a method to allow this based on the form definition I can look at it, but not on the schema.

Please re-open if you do not feel the question has been answered sufficiently.
