### ISSUE TITLE
Improve contribution docs

### ISSUE THREAD

**Issue by donalmurtagh** [json-schema-form/angular-schema-form#901]
I was trying to setup a local development environment for angular-schema-form. Here's what I did:

- Cloned all the repos into sibling folders, as described in `CONTRIBUTING.md`
- Installed karma (this was not mentioned in `CONTRIBUTING.md`)
- Ran `npm install` (this was not mentioned in `CONTRIBUTING.md`)
- Ran `bower install` (this was not mentioned in `CONTRIBUTING.md`)
- Ran `npm run test`

The guidelines for how to setup a local dev. environment should be complete: ideally, it should be possible to build and run the tests simply by copy-pasting a series of commands. Any assumptions that are made about the local environment (e.g. npm is already installed) should be documented.

@json-schema-form/angular-schema-form-lead

**Comment by donalmurtagh** [comment]
[npm-debug.log.txt](https://github.com/json-schema-form/angular-schema-form/files/1087747/npm-debug.log.txt)

**Comment by Anthropic** [comment]
@donalmurtagh was there anything else to add to this, did you need to install webpack/eslint globally with -g to get build to work for example?

**Comment by Anthropic** [comment]
@donalmurtagh would this suffice?
## How to setup to develop
To get started clone all json-schema-form library repos into sibling folders.
```bash
git clone https://github.com/json-schema-form/json-schema-form-core.git
git clone https://github.com/json-schema-form/angular-schema-form.git
git clone https://github.com/json-schema-form/angular-schema-form-bootstrap.git
git clone https://github.com/json-schema-form/angular-schema-form-material.git
```
Install dev/global dependencies and bower references to use demo site
```bash
npm install
npm install -g webpack eslint mocha # json-schema-form-core
npm install -g webpack eslint karma # angular-schema-form
bower install
```
Once cloned each repo has npm commands for assisting development
```bash
# Run unit tests
npm run test

# Run the build
npm run build

# Run the build and minify
npm run dist # not in json-schema-form-core

# Run the build and watch for changes
npm run watch
```

**Comment by Anthropic** [comment]
@donalmurtagh please re-open if you have more to add or think there's anything else I should add?
