### ISSUE TITLE
the second level array can't be display if there is a boolean property in the object

### ISSUE THREAD

**Issue by damonpu** [json-schema-form/angular-schema-form#912]
`{
  "type": "object",
  "title": "Comment",
  "required": [
    "comments"
  ],
  "properties": {
    "comments": {
      "type": "array",
      "maxItems": 2,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "email": {
            "title": "Email",
            "type": "string",
            "pattern": "^\\S+@\\S+$",
            "description": "Email will be used for evil."
          },
          "array2" : {
              "type":"array",
              "items":{
                 "type":"object",
                 "properties": {
                      "name": {
                        "title": "Name",
                        "type": "boolean"
                      }
                  }
              }
          },
          "spam": {
            "title": "Spam",
            "type": "boolean",
            "default": true
          },
          "comment": {
            "title": "Comment",
            "type": "string",
            "maxLength": 20,
            "validationMessage": "Don't be greedy!"
          }
        },
        "required": [
          "name",
          "comment"
        ]
      }
    }
  }
}`

[Description](url)
we try to use this tools to implement something for QA to generate json data, there is an issue when the schema have two level array and the second level array contain an object that has boolean type property, please use the json I post for testing

@json-schema-form/angular-schema-form-lead

**Comment by donalmurtagh** [comment]
@damonpu Could you create a Plunker demo that reproduces your issue. You could fork [this demo](https://plnkr.co/edit/H1ZEhzr5J9yRNouR5vVN?p=info), so that you don't have to create everything from scratch.

**Comment by damonpu** [comment]
should be the version issue, we now use the same version as the demo and the issue resolved, so close the issue, thanks for the help
