### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module myApp due to: [$injector:modulerr] Failed to instantiate module schemaForm due to: r is undefined

### ISSUE THREAD

**Issue by upgo** [json-schema-form/angular-schema-form#917]
I can't get angular-schema-form to work and am being served and error:

Error: [$injector:modulerr] Failed to instantiate module myApp due to: [$injector:modulerr] Failed to instantiate module schemaForm due to: r is undefined.

All the scripts are correctly loaded in the right order as described. The only thing I can figure is that require.js is somehow needed but is this a requirement for my app to have or is one of the modules requiring this?
 
BTW, i'm using Angular 1.6 if that's anything to go by.

**Comment by Anthropic** [comment]
@upgo I haven't tested it with 1.6 yet, it is hard to say from that message, I would need more info to be able to offer you some assistance.

**Comment by dsnoeck** [comment]
This drive me crazy for a full day, until I finally found the solution here: https://github.com/json-schema-form/angular-schema-form/issues/713

I'm also using Angular 1.6 with browserify.

**Comment by Anthropic** [comment]
Closed as it appears answered in #713

Please re-open if you do not feel the question has been answered sufficiently.
