### ISSUE TITLE
Duplicated field mixing asterix and declaration

### ISSUE THREAD

**Issue by amiceli** [json-schema-form/angular-schema-form#918]
#### Features
As a developer, when I define my form schema, I should be able to display remaning field with "*".

#### Expected behaviour

For example with that form definition : 

    vm.form  = [
        {
            "key"            : "name",
            validationMessage: {
                "nameContainsSpaces": "The name contains spaces"
            },
            $validators      : {
                nameContainsSpaces: function (value) {
                    return !(angular.isString(value) && value.indexOf(' ') > 0);
                }
            }
        },
        '*',
        {
            type : "submit",
            title: "Save"
        }
    ];

My form must display **name** field with custom validators, and other field not explicit declared.

#### Actual behaviour

Currently name field is displayed twice.

**Comment by Anthropic** [comment]
See #748 this is in the alpha version already using the key "..."
