### ISSUE TITLE
no value change when using arrow keys in microsoft egde

### ISSUE THREAD

**Issue by SweetSchilly** [json-schema-form/angular-schema-form#921]
We use an input-tag with numbers. If we use _arrow keys_, the values in the tree would be changed, but in **microsoft edge** there are no changing - no changing after enter key or tab key or otherwise. The value changes only when typing numbers. 

We tested this in Firefox and Google Chrome equally and there are no problems.

We hope, you can help us.
Thanks

**Comment by Anthropic** [comment]
@SweetSchilly it appears Microsoft Edge is an edge case 🤣 
But seriously Angular decided not to care about IE not supporting the required behaviour and someone on the issue posted a workaround if you have to support edge: https://github.com/angular/angular.js/issues/15366#issuecomment-258495347

I suspect eventually Edge will be fixed, so I am not inclined to put the workaround into this project if Angular don't see a reason to do so.

Please re-open if you do not feel the question has been answered sufficiently.
