### ISSUE TITLE
Can we have Multiple schemas and multiple models for one form???

### ISSUE THREAD

**Issue by arshad104** [json-schema-form/angular-schema-form#924]
Hi,

I am using angular schema forms for one of project. Just want to know can we have mutliple schemas and multiple models for a single form? If Yes, any example?

Thanks

**Comment by Anthropic** [comment]
Not really, you can add sf-schema attributes on a non-form tag and have multiple schema-form instances within one html form tag. Never tried to blend the data though. Be easier to use $ref to combine the schema under different parent object keys and do it that way I would expect.
