### ISSUE TITLE
Cascading menu to select value

### ISSUE THREAD

**Issue by Thorski** [json-schema-form/angular-schema-form#925]
#### Enhancement
Is it possible to make a cascading  menu for 
selecting a value.    Perhaps some array of arrays in titleMap?

Use case is user needs to pick a node in a large hierarchy of values.
<pre>
Root ->
  Top Level 1 ->
     Next Level 1-1 ->
       Third Level 1-1-1
       Third Level 1-1-2
     Next Level 1-2 ->
  ... etc
</pre>

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
@Thorski you can use arrays in arrays as long as the key names are unique, you could use a select (one of the dynamic select add-ons) which loads related level data if you know how many levels deep the user may go as well.

**Comment by Thorski** [comment]
@Anthropic thank you for your answer, but I cannot figure out how to structure this.   If you could provide a simple example I would greatly appreciate it.   Thank you.   

    "titleMap": [
      {
        "value": "1",
        "name": "Ohio",
        "type": "select",
        "children": [
          { "value": "2", "name": "Delaware" }
        ]
      },
    ]

**Comment by Anthropic** [comment]
Can you give me an example of the data you want from the output and perhaps an example of the tree?

**Comment by Thorski** [comment]
I had not looked at or seen the external options.   Thank you.   I have since wrapped ngx-tree-select in a custom widget and am using that.

**Comment by Anthropic** [comment]
Closing since you found a solution :)

Please re-open if you do not feel the question has been answered sufficiently.

**Comment by jasminecjc** [comment]
what's your solution for angular2-json-schema-form to implement the cascades

**Comment by Anthropic** [comment]
@jasminecjc angular2-json-schema-form is an unrelated project.
