### ISSUE TITLE
how to remove  empty option from drop down.

### ISSUE THREAD

**Issue by sandeepbhatt** [json-schema-form/angular-schema-form#926]
Hi , I want to remove empty option from json:from which is created through below json

{
"type": "object",
"required": ["editors_used"],
"properties": {
"editors_used": {
"type": "array",
"title": "What editors do you use?",
"minItems": 1,
"items": {
"type": "string",
"enum": [
"vim", "emacs", "sublime", "kate"
],"default":"vim"
},
"additionalItems": false
}
}
}

**Comment by Anthropic** [comment]
What do you mean? You require 1 item in order to be valid, what empty option are you talking about?

**Comment by Anthropic** [comment]
I need a gist of what you are doing to be able to help, this doesn't provide enough information for me to support your issue.

The example demo has a "Save to Gist" button you can use to create one from a schema and form definition.
