### ISSUE TITLE
Does this support onPaste event?

### ISSUE THREAD

**Issue by Tina92** [json-schema-form/angular-schema-form#933]
I want to get the date on clipboard. I can make it through the `ng-paste` directive usually. Now, can  this default input suppport `onPaste` event ?

**Comment by Anthropic** [comment]
Having never used it I can't be certain, but as is I doubt it, you would probably have to use a builder with the decorator to add the attribute.

**Comment by Tina92** [comment]
Yes, I use the bootstrap decorator, but I don't know how to add this attribute because `onPaste` is a event(function).

**Comment by Tina92** [comment]
Yeah, I hava solved this problem through the method about the decorator. 😊
Thank you !

**Comment by Anthropic** [comment]
Great, thanks for letting me know @Tina92
