### ISSUE TITLE
How to add fields to the schema dynamically

### ISSUE THREAD

**Issue by Jarzembowski** [json-schema-form/angular-schema-form#942]
I'm trying to add fields to the schema dynamically, but it only shows the first one I add.
For some reason, the "key" atribute changes from the second element on - maybe that's why only the first is showing.

Unfortunatelly, in this plnkr nothing happens, so I couldn't really recreate the same scenario - but the code is exactly the same.

https://plnkr.co/edit/6uD59yn7fIimTMuu6Qyq

**Comment by Anthropic** [comment]
@Jarzembowski did you solve this, I missed it as it came in while I was on holiday.

**Comment by Jarzembowski** [comment]
Yes, I did, thanks for asking.
To be honest I dont remember how I did, but it turned out ok.

**Comment by Anthropic** [comment]
No worries, feel free to comment further if you remember otherwise I will close this for now
