### ISSUE TITLE
Is there any ui form builder for this library

### ISSUE THREAD

**Issue by signalarun** [json-schema-form/angular-schema-form#944]
#### Enhancement
As a user/developer, when I ... I should be able to ...

#### Expected behaviour
I expected ...

#### Actual behaviour
It actually ...

#### Gist/Plunker/Demo

[Description](url)

#### Related issues
This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
There was one started by some other people at one point https://github.com/json-schema-form/json-schema-builder, but I don't think they still work on it. But you could take a look and see if it does what you are after.
