### ISSUE TITLE
Readonly on the form doesn't apply to selector and array types.

### ISSUE THREAD

**Issue by easonzhou** [json-schema-form/angular-schema-form#947]
#### Enhancement
As a user/developer, when I apply readonly on the form, readonly doesn't apply to single/multiple selector UI elements.

#### Expected behaviour
I expected that the whole form are readonly.

#### Actual behaviour
Actually only the text input fields are readonly, but the selector or multiple selectors are still editable and has no "readonly" look and feel

#### Gist/Plunker/Demo

Description
![srererer](https://user-images.githubusercontent.com/1154753/34594821-4a4936b0-f20e-11e7-834f-77217d49b7a8.png)

#### Related issues
This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
How are you doing it, if you apply readonly within the schema or form on a select it should work? If not you could try putting the fields within a fieldset and making the fieldset readonly.

**Comment by easonzhou** [comment]
OK. Tried with putting them into fieldset and it works.
