### ISSUE TITLE
onChange is not able to update schemaForm

### ISSUE THREAD

**Issue by AChakraborty1982** [json-schema-form/angular-schema-form#948]
https://plnkr.co/edit/AHemml?p=preview 

I am trying to use onChange and update the schema values, but i don't see any changes, can someone point me what is wrong in it.
`    
$scope.schema.properties.processor = ['dym', 'dym1'];
       
 $scope.form = angular.copy($scope.originalForm);
      
 $scope.$broadcast('schemaFormRedraw');
`
If I change the platform , i want to update the processors with new values. But the controls itself is changing to Textbox from Select.

**Comment by Anthropic** [comment]
`$scope.schema.properties.processor = ['dym', 'dym1'];`
should be
`$scope.schema.properties.processor.enum = ['dym', 'dym1'];`
