### ISSUE TITLE
Radio buttons across array

### ISSUE THREAD

**Issue by jarocks** [json-schema-form/angular-schema-form#949]
Is it possible in an array to only allow one radio button to be selected at a time across all the items? (Like shown) Or can this only be accomplished with additional code?
![image](https://media.giphy.com/media/xUNd9Mcdi69NmSK5Fe/giphy.gif)

**Comment by Anthropic** [comment]
It isn't possible at this stage without an addon.

It depends what the specific desired outcome is, if you simply wish to select one, and only one, of the array items you can certainly use the calculate add-on to manipulate values based on a selection. But it would probably be easiest to use a dynamic drop down add-on to read in the array and display the titles of the array items with their index above or below the actual array.
