### ISSUE TITLE
is Angular 4 support expected in future for this tool

### ISSUE THREAD

**Issue by bp117** [json-schema-form/angular-schema-form#952]
#### Enhancement
As a user/developer, when I ... I should be able to ...

#### Expected behaviour
I expected ...

#### Actual behaviour
It actually ...

#### Gist/Plunker/Demo

[Description](url)

#### Related issues
This is/maybe related to ...

@json-schema-form/angular-schema-form-lead

**Comment by Anthropic** [comment]
Duplicate of #774
