### ISSUE TITLE
What's wrong with schema and layout?

### ISSUE THREAD

**Issue by person2713** [json-schema-form/angular-schema-form#958]
```
`{
  "schema": {
  "type": "object",
  "properties": {
    "name": {
		"type": "string"
    },
	"Objects": {
	 "type": "array",
	  "items": {
		"type": "object",
		"properties": {
		  "object": {
			"type": "object",
			"properties": {
			  "objectId": {
				"type": "string"
			  },
			  "attributes": {
				"type": "array",
				"items": {
				  "type": "object",
				  "properties": {
					"attributeId": {
						"type": "string"
					},
					"attrbuteName": {
						"type": "string"
					},
					"value": {
					  "type": "string"
					}
				  }
				}
			  }
			}
		  }
		}
	  }
	}
  }
},
  "form": [
      "name",
      {
          "key" :"Objects",
          "items": [
              {
                "key":"Objects[].object",
                "items": [
                    "objectId",
                    {
                        "key": "attributes",
                        "items": [
                            "['attributes'][]attributeId",
                            "['attributes'][]attrbuteName",
                            "['attributes'][]value"
                        ]
                    }
                ]
              }
            ]
      }
]
}`
```
Why I don't see "attributeId", "attrbuteName" and "value"?

**Comment by scottux** [comment]
This is probably an issue best handled by a question on stackoverflow.com. Your syntax is off. In short, you need to use the full key like `Objects[].object.attributes[].attributeId`

**Comment by person2713** [comment]
You are right, thanks.

**Comment by person2713** [comment]
In general, my purpose is add appear Name of object when user input objectId. May be there is a better idea than add "attrbuteName" to schema and then customize it in layout?
Sample:
![image](https://user-images.githubusercontent.com/23407273/37391982-01bb7408-277e-11e8-8fd5-ebde014c9c48.png)

**Comment by scottux** [comment]
Start here for JSON Schema http://json-schema.org/learn/getting-started-step-by-step.html

And then for this library, https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#basic-usage and http://schemaform.io/examples/bootstrap-example.html are the best resources I have found.

**Comment by Anthropic** [comment]
Thanks @scottux 

@person2713 please comment if you want to re-open or do not feel the question has been answered sufficiently.
