### ISSUE TITLE
http://schemaform.io/ is down

### ISSUE THREAD

**Issue by Skepticism** [json-schema-form/angular-schema-form#960]
As a result, the examples referenced by the documentation are unavailable

**Comment by ggomez039** [comment]
when will this be resolved?

**Comment by lguerreromx** [comment]
Is there any news about this, is the site gonna be live again someday?

**Comment by Anthropic** [comment]
I'll find out what happened. It is just a hosted github page from the repo, but it seems to have disconnected for some reason.

**Comment by Anthropic** [comment]
@Skepticism @ggomez039 @lguerreromx @iamarcel @dwiyatci @leanand @iGormilhit @mbaez 

You can now use:
https://json-schema-form.github.io/angular-schema-form/examples/bootstrap-example.html

I have enabled this until I can sort out a new hosting arrangement.

**Comment by Anthropic** [comment]
Should be back now, the transfer has gone through and it is now managed by me moving forward.
