### ISSUE TITLE
 Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by yuttian** [json-schema-form/angular-schema-form#963]
base.js:9269 Uncaught Error: [$injector:modulerr] Failed to instantiate module angle due to:
Error: [$injector:modulerr] Failed to instantiate module schemaForm due to:
TypeError: Cannot read property 'parse' of undefined
    at Object.<anonymous> (http://192.168.3.25:8891/admin/app/js/base.js:56310:35)
    at invoke (http://192.168.3.25:8891/admin/app/js/base.js:13409:17)
    at Object.instantiate (http://192.168.3.25:8891/admin/app/js/base.js:13417:27)
    at provider (http://192.168.3.25:8891/admin/app/js/base.js:13252:36)
    at Object.provider (http://192.168.3.25:8891/admin/app/js/base.js:13244:16)
    at runInvokeQueue (http://192.168.3.25:8891/admin/app/js/base.js:13315:35)
    at http://192.168.3.25:8891/admin/app/js/base.js:13323:11
    at forEach (http://192.168.3.25:8891/admin/app/js/base.js:9529:20)
    at loadModules (http://192.168.3.25:8891/admin/app/js/base.js:13305:5)
    at http://192.168.3.25:8891/admin/app/js/base.js:13322:40
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=schemaForm&p1=TypeError%3A%20Cannot%20read%20property%20'parse'%20of%20undefined%0A%20%20%20%20at%20Object.%3Canonymous%3E%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A56310%3A35)%0A%20%20%20%20at%20invoke%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13409%3A17)%0A%20%20%20%20at%20Object.instantiate%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13417%3A27)%0A%20%20%20%20at%20provider%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13252%3A36)%0A%20%20%20%20at%20Object.provider%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13244%3A16)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13315%3A35)%0A%20%20%20%20at%20http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13323%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A9529%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13305%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.3.25%3A8891%2Fadmin%2Fapp%2Fjs%2Fbase.js%3A13322%3A40

**Comment by Anthropic** [comment]
Please comment if this is still an issue and you want to re-open and can provide more info (gist/plunker) to help us to help you :)

**Comment by balazsnemeth** [comment]
@yuttian I have the same issue, can you give me some hints how did you solve it?

**Comment by gregoryz7** [comment]
Hey I got this error when I forgot to include ObjectPath.js. I missed the second sentence under Script Loading in the documentation at first.  Thanks! -Z
