### ISSUE TITLE
TypeError: Cannot read property 'validateResult' of undefined

### ISSUE THREAD

**Issue by yuttian** [json-schema-form/angular-schema-form#964]
Whenever I hit the keyboard, the console would make a mistake. I don't know why.

![1525346843266](https://user-images.githubusercontent.com/24581796/39573993-0c9a7f0c-4f08-11e8-8582-fbf205c29587.jpg)

**Comment by Anthropic** [comment]
You haven't filled in the details I require to begin starting to help you, please make a plunker to demo the issue.
