### ISSUE TITLE
How to get the data in tabular form from Json-Schema

### ISSUE THREAD

**Issue by amithmahakala423** [json-schema-form/angular-schema-form#972]
I am using angular2-json-schema-form, to form html page. Some of the data i want to represent in the table using the attribute "format": "table". I am getting the following error: "unknown format "table" ignored in schema".

Do i need to install any table module using npm ?

"YextCategoryList": {
"type": "array",
"format": "table",
"addable" : false,
"removable":false,
"orderable": false,
"title": "Yext Category List",
"items": {
"type": "object",
"properties": {
"yextCategoryId": {
"title": "Yext Category Id",
"type": "string",
"readonly": true,
"default": "",
"examples": [ "123456" ]
},
"addedBy": {
"title": "Added By",
"type": "string",
"readonly": true,
"default": "",
"examples": [ "koushk01" ]
},
"addedDate": {
"title": "Added Date",
"readonly": true,
"default": "",
"examples": [ "2017-12-20T16:44:04.000Z" ]
},
"updatedBy": {
"title": "Updated By",
"type": "string",
"readonly": true,
"default": "",
"examples": [ "koushk01" ]
},
"updatedDate": {
"title": "Updated Date",
"tyre": "string",
"readonly": true,
"default": "",
"examples": [ "2017-12-20T16:44:04.000Z" ]
}
}
}
}

**Comment by Anthropic** [comment]
Wrong library **angular-schema-form** !== **angular2-json-schema-form**
