### ISSUE TITLE
Hide empty tabs

### ISSUE THREAD

**Issue by knasser** [json-schema-form/angular-schema-form#975]
#### Enhancement
As a user, when all the fields in a tab are hidden (because of a condition) , then the empty tab itself should be hidden

#### Expected behaviour
I expected  tabs without fields to be hidden from display

#### Actual behaviour
  empty tabs are actually still displayed

**Comment by Anthropic** [comment]
@knasser this would be available via [this issue #776](#776) so follow that one and/or add to it. You may also have some luck looking at some work others have tried.

**Comment by Anthropic** [comment]
ps. sorry for the late reply, I was on holiday.
