### ISSUE TITLE
npm angular-schema-form uses 0.8.13 rather than 0.8.14

### ISSUE THREAD

**Issue by physikerwelt** [json-schema-form/angular-schema-form#992]
the latest version from npm 0.8.13 is not compatible with the angular lts version. I think it would be good to publish the version 0.8.14 to npm so that people do not need to install it from github.

**Comment by Anthropic** [comment]
That was deliberate after 0.8.14 produced a few issues. I have to find time to resolve those issues first and I haven't had any free time lately.
